(ns test.malli.command
  "Commands index - re-exports all command namespaces"
  (:require [test.malli.cmd.lira :as lira]
            [test.malli.cmd.heatcamera :as heatcamera]
            [test.malli.cmd.system :as system]
            [test.malli.cmd.lrf :as lrf]
            [test.malli.cmd.compass :as compass]
            [test.malli.cmd.osd :as osd]
            [test.malli.cmd.lrf_calib :as lrf_calib]
            [test.malli.cmd.rotaryplatform :as rotaryplatform]
            [test.malli.cmd.gps :as gps]
            [test.malli.cmd.daycamglassheater :as daycamglassheater]
            [test.malli.cmd.cv :as cv]
            [test.malli.cmd.daycamera :as daycamera]))

;; Re-export all public functions from sub-namespaces
;; This supports testing without needing to know the internal namespace
;; structure

(def lira-build-root lira/build-root)
(def lira-parse-root lira/parse-root)
(def lira-build-refine-target lira/build-refine-target)
(def lira-parse-refine-target lira/parse-refine-target)
(def lira-build-jon-gui-data-lira-target lira/build-jon-gui-data-lira-target)
(def lira-parse-jon-gui-data-lira-target lira/parse-jon-gui-data-lira-target)
(def heatcamera-build-root heatcamera/build-root)
(def heatcamera-parse-root heatcamera/parse-root)
(def heatcamera-build-set-fx-mode heatcamera/build-set-fx-mode)
(def heatcamera-parse-set-fx-mode heatcamera/parse-set-fx-mode)
(def heatcamera-build-set-clahe-level heatcamera/build-set-clahe-level)
(def heatcamera-parse-set-clahe-level heatcamera/parse-set-clahe-level)
(def heatcamera-build-shift-clahe-level heatcamera/build-shift-clahe-level)
(def heatcamera-parse-shift-clahe-level heatcamera/parse-shift-clahe-level)
(def heatcamera-build-next-fx-mode heatcamera/build-next-fx-mode)
(def heatcamera-parse-next-fx-mode heatcamera/parse-next-fx-mode)
(def heatcamera-build-prev-fx-mode heatcamera/build-prev-fx-mode)
(def heatcamera-parse-prev-fx-mode heatcamera/parse-prev-fx-mode)
(def heatcamera-build-refresh-fx-mode heatcamera/build-refresh-fx-mode)
(def heatcamera-parse-refresh-fx-mode heatcamera/parse-refresh-fx-mode)
(def heatcamera-build-enable-dde heatcamera/build-enable-dde)
(def heatcamera-parse-enable-dde heatcamera/parse-enable-dde)
(def heatcamera-build-disable-dde heatcamera/build-disable-dde)
(def heatcamera-parse-disable-dde heatcamera/parse-disable-dde)
(def heatcamera-build-set-value heatcamera/build-set-value)
(def heatcamera-parse-set-value heatcamera/parse-set-value)
(def heatcamera-build-set-dde-level heatcamera/build-set-dde-level)
(def heatcamera-parse-set-dde-level heatcamera/parse-set-dde-level)
(def heatcamera-build-set-digital-zoom-level
  heatcamera/build-set-digital-zoom-level)
(def heatcamera-parse-set-digital-zoom-level
  heatcamera/parse-set-digital-zoom-level)
(def heatcamera-build-shift-dde heatcamera/build-shift-dde)
(def heatcamera-parse-shift-dde heatcamera/parse-shift-dde)
(def heatcamera-build-zoom-in heatcamera/build-zoom-in)
(def heatcamera-parse-zoom-in heatcamera/parse-zoom-in)
(def heatcamera-build-zoom-out heatcamera/build-zoom-out)
(def heatcamera-parse-zoom-out heatcamera/parse-zoom-out)
(def heatcamera-build-zoom-stop heatcamera/build-zoom-stop)
(def heatcamera-parse-zoom-stop heatcamera/parse-zoom-stop)
(def heatcamera-build-focus-in heatcamera/build-focus-in)
(def heatcamera-parse-focus-in heatcamera/parse-focus-in)
(def heatcamera-build-focus-out heatcamera/build-focus-out)
(def heatcamera-parse-focus-out heatcamera/parse-focus-out)
(def heatcamera-build-focus-stop heatcamera/build-focus-stop)
(def heatcamera-parse-focus-stop heatcamera/parse-focus-stop)
(def heatcamera-build-focus-step-plus heatcamera/build-focus-step-plus)
(def heatcamera-parse-focus-step-plus heatcamera/parse-focus-step-plus)
(def heatcamera-build-focus-step-minus heatcamera/build-focus-step-minus)
(def heatcamera-parse-focus-step-minus heatcamera/parse-focus-step-minus)
(def heatcamera-build-calibrate heatcamera/build-calibrate)
(def heatcamera-parse-calibrate heatcamera/parse-calibrate)
(def heatcamera-build-zoom heatcamera/build-zoom)
(def heatcamera-parse-zoom heatcamera/parse-zoom)
(def heatcamera-build-next-zoom-table-pos heatcamera/build-next-zoom-table-pos)
(def heatcamera-parse-next-zoom-table-pos heatcamera/parse-next-zoom-table-pos)
(def heatcamera-build-prev-zoom-table-pos heatcamera/build-prev-zoom-table-pos)
(def heatcamera-parse-prev-zoom-table-pos heatcamera/parse-prev-zoom-table-pos)
(def heatcamera-build-set-calib-mode heatcamera/build-set-calib-mode)
(def heatcamera-parse-set-calib-mode heatcamera/parse-set-calib-mode)
(def heatcamera-build-set-zoom-table-value
  heatcamera/build-set-zoom-table-value)
(def heatcamera-parse-set-zoom-table-value
  heatcamera/parse-set-zoom-table-value)
(def heatcamera-build-set-agc heatcamera/build-set-agc)
(def heatcamera-parse-set-agc heatcamera/parse-set-agc)
(def heatcamera-build-set-filters heatcamera/build-set-filters)
(def heatcamera-parse-set-filters heatcamera/parse-set-filters)
(def heatcamera-build-start heatcamera/build-start)
(def heatcamera-parse-start heatcamera/parse-start)
(def heatcamera-build-stop heatcamera/build-stop)
(def heatcamera-parse-stop heatcamera/parse-stop)
(def heatcamera-build-halt heatcamera/build-halt)
(def heatcamera-parse-halt heatcamera/parse-halt)
(def heatcamera-build-photo heatcamera/build-photo)
(def heatcamera-parse-photo heatcamera/parse-photo)
(def heatcamera-build-get-meteo heatcamera/build-get-meteo)
(def heatcamera-parse-get-meteo heatcamera/parse-get-meteo)
(def heatcamera-build-set-auto-focus heatcamera/build-set-auto-focus)
(def heatcamera-parse-set-auto-focus heatcamera/parse-set-auto-focus)
(def heatcamera-build-reset-zoom heatcamera/build-reset-zoom)
(def heatcamera-parse-reset-zoom heatcamera/parse-reset-zoom)
(def heatcamera-build-save-to-table heatcamera/build-save-to-table)
(def heatcamera-parse-save-to-table heatcamera/parse-save-to-table)
(def system-build-root system/build-root)
(def system-parse-root system/parse-root)
(def system-build-start-a-ll system/build-start-a-ll)
(def system-parse-start-a-ll system/parse-start-a-ll)
(def system-build-stop-a-ll system/build-stop-a-ll)
(def system-parse-stop-a-ll system/parse-stop-a-ll)
(def system-build-reboot system/build-reboot)
(def system-parse-reboot system/parse-reboot)
(def system-build-power-off system/build-power-off)
(def system-parse-power-off system/parse-power-off)
(def system-build-reset-configs system/build-reset-configs)
(def system-parse-reset-configs system/parse-reset-configs)
(def system-build-start-rec system/build-start-rec)
(def system-parse-start-rec system/parse-start-rec)
(def system-build-stop-rec system/build-stop-rec)
(def system-parse-stop-rec system/parse-stop-rec)
(def system-build-mark-rec-important system/build-mark-rec-important)
(def system-parse-mark-rec-important system/parse-mark-rec-important)
(def system-build-unmark-rec-important system/build-unmark-rec-important)
(def system-parse-unmark-rec-important system/parse-unmark-rec-important)
(def system-build-enter-transport system/build-enter-transport)
(def system-parse-enter-transport system/parse-enter-transport)
(def system-build-enable-geodesic-mode system/build-enable-geodesic-mode)
(def system-parse-enable-geodesic-mode system/parse-enable-geodesic-mode)
(def system-build-disable-geodesic-mode system/build-disable-geodesic-mode)
(def system-parse-disable-geodesic-mode system/parse-disable-geodesic-mode)
(def system-build-set-localization system/build-set-localization)
(def system-parse-set-localization system/parse-set-localization)
(def lrf-build-root lrf/build-root)
(def lrf-parse-root lrf/parse-root)
(def lrf-build-get-meteo lrf/build-get-meteo)
(def lrf-parse-get-meteo lrf/parse-get-meteo)
(def lrf-build-start lrf/build-start)
(def lrf-parse-start lrf/parse-start)
(def lrf-build-stop lrf/build-stop)
(def lrf-parse-stop lrf/parse-stop)
(def lrf-build-measure lrf/build-measure)
(def lrf-parse-measure lrf/parse-measure)
(def lrf-build-scan-on lrf/build-scan-on)
(def lrf-parse-scan-on lrf/parse-scan-on)
(def lrf-build-scan-off lrf/build-scan-off)
(def lrf-parse-scan-off lrf/parse-scan-off)
(def lrf-build-refine-off lrf/build-refine-off)
(def lrf-parse-refine-off lrf/parse-refine-off)
(def lrf-build-refine-on lrf/build-refine-on)
(def lrf-parse-refine-on lrf/parse-refine-on)
(def lrf-build-target-designator-off lrf/build-target-designator-off)
(def lrf-parse-target-designator-off lrf/parse-target-designator-off)
(def lrf-build-target-designator-on-mode-a
  lrf/build-target-designator-on-mode-a)
(def lrf-parse-target-designator-on-mode-a
  lrf/parse-target-designator-on-mode-a)
(def lrf-build-target-designator-on-mode-b
  lrf/build-target-designator-on-mode-b)
(def lrf-parse-target-designator-on-mode-b
  lrf/parse-target-designator-on-mode-b)
(def lrf-build-enable-fog-mode lrf/build-enable-fog-mode)
(def lrf-parse-enable-fog-mode lrf/parse-enable-fog-mode)
(def lrf-build-disable-fog-mode lrf/build-disable-fog-mode)
(def lrf-parse-disable-fog-mode lrf/parse-disable-fog-mode)
(def lrf-build-set-scan-mode lrf/build-set-scan-mode)
(def lrf-parse-set-scan-mode lrf/parse-set-scan-mode)
(def lrf-build-new-session lrf/build-new-session)
(def lrf-parse-new-session lrf/parse-new-session)
(def compass-build-root compass/build-root)
(def compass-parse-root compass/parse-root)
(def compass-build-start compass/build-start)
(def compass-parse-start compass/parse-start)
(def compass-build-stop compass/build-stop)
(def compass-parse-stop compass/parse-stop)
(def compass-build-next compass/build-next)
(def compass-parse-next compass/parse-next)
(def compass-build-calibrate-start-long compass/build-calibrate-start-long)
(def compass-parse-calibrate-start-long compass/parse-calibrate-start-long)
(def compass-build-calibrate-start-short compass/build-calibrate-start-short)
(def compass-parse-calibrate-start-short compass/parse-calibrate-start-short)
(def compass-build-calibrate-next compass/build-calibrate-next)
(def compass-parse-calibrate-next compass/parse-calibrate-next)
(def compass-build-calibrate-cencel compass/build-calibrate-cencel)
(def compass-parse-calibrate-cencel compass/parse-calibrate-cencel)
(def compass-build-get-meteo compass/build-get-meteo)
(def compass-parse-get-meteo compass/parse-get-meteo)
(def compass-build-set-magnetic-declination
  compass/build-set-magnetic-declination)
(def compass-parse-set-magnetic-declination
  compass/parse-set-magnetic-declination)
(def compass-build-set-offset-angle-azimuth
  compass/build-set-offset-angle-azimuth)
(def compass-parse-set-offset-angle-azimuth
  compass/parse-set-offset-angle-azimuth)
(def compass-build-set-offset-angle-elevation
  compass/build-set-offset-angle-elevation)
(def compass-parse-set-offset-angle-elevation
  compass/parse-set-offset-angle-elevation)
(def compass-build-set-use-rotary-position
  compass/build-set-use-rotary-position)
(def compass-parse-set-use-rotary-position
  compass/parse-set-use-rotary-position)
(def osd-build-root osd/build-root)
(def osd-parse-root osd/parse-root)
(def osd-build-show-default-screen osd/build-show-default-screen)
(def osd-parse-show-default-screen osd/parse-show-default-screen)
(def osd-build-show-lrf-measure-screen osd/build-show-lrf-measure-screen)
(def osd-parse-show-lrf-measure-screen osd/parse-show-lrf-measure-screen)
(def osd-build-show-lrf-result-screen osd/build-show-lrf-result-screen)
(def osd-parse-show-lrf-result-screen osd/parse-show-lrf-result-screen)
(def osd-build-show-lrf-result-simplified-screen
  osd/build-show-lrf-result-simplified-screen)
(def osd-parse-show-lrf-result-simplified-screen
  osd/parse-show-lrf-result-simplified-screen)
(def osd-build-enable-heat-osd osd/build-enable-heat-osd)
(def osd-parse-enable-heat-osd osd/parse-enable-heat-osd)
(def osd-build-disable-heat-osd osd/build-disable-heat-osd)
(def osd-parse-disable-heat-osd osd/parse-disable-heat-osd)
(def osd-build-enable-day-osd osd/build-enable-day-osd)
(def osd-parse-enable-day-osd osd/parse-enable-day-osd)
(def osd-build-disable-day-osd osd/build-disable-day-osd)
(def osd-parse-disable-day-osd osd/parse-disable-day-osd)
(def lrf_calib-build-root lrf_calib/build-root)
(def lrf_calib-parse-root lrf_calib/parse-root)
(def lrf_calib-build-offsets lrf_calib/build-offsets)
(def lrf_calib-parse-offsets lrf_calib/parse-offsets)
(def lrf_calib-build-set-offsets lrf_calib/build-set-offsets)
(def lrf_calib-parse-set-offsets lrf_calib/parse-set-offsets)
(def lrf_calib-build-shift-offsets-by lrf_calib/build-shift-offsets-by)
(def lrf_calib-parse-shift-offsets-by lrf_calib/parse-shift-offsets-by)
(def lrf_calib-build-reset-offsets lrf_calib/build-reset-offsets)
(def lrf_calib-parse-reset-offsets lrf_calib/parse-reset-offsets)
(def lrf_calib-build-save-offsets lrf_calib/build-save-offsets)
(def lrf_calib-parse-save-offsets lrf_calib/parse-save-offsets)
(def rotaryplatform-build-root rotaryplatform/build-root)
(def rotaryplatform-parse-root rotaryplatform/parse-root)
(def rotaryplatform-build-axis rotaryplatform/build-axis)
(def rotaryplatform-parse-axis rotaryplatform/parse-axis)
(def rotaryplatform-build-set-mode rotaryplatform/build-set-mode)
(def rotaryplatform-parse-set-mode rotaryplatform/parse-set-mode)
(def rotaryplatform-build-set-azimuth-value
  rotaryplatform/build-set-azimuth-value)
(def rotaryplatform-parse-set-azimuth-value
  rotaryplatform/parse-set-azimuth-value)
(def rotaryplatform-build-rotate-azimuth-to
  rotaryplatform/build-rotate-azimuth-to)
(def rotaryplatform-parse-rotate-azimuth-to
  rotaryplatform/parse-rotate-azimuth-to)
(def rotaryplatform-build-rotate-azimuth rotaryplatform/build-rotate-azimuth)
(def rotaryplatform-parse-rotate-azimuth rotaryplatform/parse-rotate-azimuth)
(def rotaryplatform-build-rotate-elevation
  rotaryplatform/build-rotate-elevation)
(def rotaryplatform-parse-rotate-elevation
  rotaryplatform/parse-rotate-elevation)
(def rotaryplatform-build-set-elevation-value
  rotaryplatform/build-set-elevation-value)
(def rotaryplatform-parse-set-elevation-value
  rotaryplatform/parse-set-elevation-value)
(def rotaryplatform-build-rotate-elevation-to
  rotaryplatform/build-rotate-elevation-to)
(def rotaryplatform-parse-rotate-elevation-to
  rotaryplatform/parse-rotate-elevation-to)
(def rotaryplatform-build-rotate-elevation-relative
  rotaryplatform/build-rotate-elevation-relative)
(def rotaryplatform-parse-rotate-elevation-relative
  rotaryplatform/parse-rotate-elevation-relative)
(def rotaryplatform-build-rotate-elevation-relative-set
  rotaryplatform/build-rotate-elevation-relative-set)
(def rotaryplatform-parse-rotate-elevation-relative-set
  rotaryplatform/parse-rotate-elevation-relative-set)
(def rotaryplatform-build-rotate-azimuth-relative
  rotaryplatform/build-rotate-azimuth-relative)
(def rotaryplatform-parse-rotate-azimuth-relative
  rotaryplatform/parse-rotate-azimuth-relative)
(def rotaryplatform-build-rotate-azimuth-relative-set
  rotaryplatform/build-rotate-azimuth-relative-set)
(def rotaryplatform-parse-rotate-azimuth-relative-set
  rotaryplatform/parse-rotate-azimuth-relative-set)
(def rotaryplatform-build-set-platform-azimuth
  rotaryplatform/build-set-platform-azimuth)
(def rotaryplatform-parse-set-platform-azimuth
  rotaryplatform/parse-set-platform-azimuth)
(def rotaryplatform-build-set-platform-elevation
  rotaryplatform/build-set-platform-elevation)
(def rotaryplatform-parse-set-platform-elevation
  rotaryplatform/parse-set-platform-elevation)
(def rotaryplatform-build-set-platform-bank
  rotaryplatform/build-set-platform-bank)
(def rotaryplatform-parse-set-platform-bank
  rotaryplatform/parse-set-platform-bank)
(def rotaryplatform-build-get-meteo rotaryplatform/build-get-meteo)
(def rotaryplatform-parse-get-meteo rotaryplatform/parse-get-meteo)
(def rotaryplatform-build-azimuth rotaryplatform/build-azimuth)
(def rotaryplatform-parse-azimuth rotaryplatform/parse-azimuth)
(def rotaryplatform-build-start rotaryplatform/build-start)
(def rotaryplatform-parse-start rotaryplatform/parse-start)
(def rotaryplatform-build-stop rotaryplatform/build-stop)
(def rotaryplatform-parse-stop rotaryplatform/parse-stop)
(def rotaryplatform-build-halt rotaryplatform/build-halt)
(def rotaryplatform-parse-halt rotaryplatform/parse-halt)
(def rotaryplatform-build-scan-start rotaryplatform/build-scan-start)
(def rotaryplatform-parse-scan-start rotaryplatform/parse-scan-start)
(def rotaryplatform-build-scan-stop rotaryplatform/build-scan-stop)
(def rotaryplatform-parse-scan-stop rotaryplatform/parse-scan-stop)
(def rotaryplatform-build-scan-pause rotaryplatform/build-scan-pause)
(def rotaryplatform-parse-scan-pause rotaryplatform/parse-scan-pause)
(def rotaryplatform-build-scan-unpause rotaryplatform/build-scan-unpause)
(def rotaryplatform-parse-scan-unpause rotaryplatform/parse-scan-unpause)
(def rotaryplatform-build-halt-azimuth rotaryplatform/build-halt-azimuth)
(def rotaryplatform-parse-halt-azimuth rotaryplatform/parse-halt-azimuth)
(def rotaryplatform-build-halt-elevation rotaryplatform/build-halt-elevation)
(def rotaryplatform-parse-halt-elevation rotaryplatform/parse-halt-elevation)
(def rotaryplatform-build-scan-prev rotaryplatform/build-scan-prev)
(def rotaryplatform-parse-scan-prev rotaryplatform/parse-scan-prev)
(def rotaryplatform-build-scan-next rotaryplatform/build-scan-next)
(def rotaryplatform-parse-scan-next rotaryplatform/parse-scan-next)
(def rotaryplatform-build-scan-refresh-node-list
  rotaryplatform/build-scan-refresh-node-list)
(def rotaryplatform-parse-scan-refresh-node-list
  rotaryplatform/parse-scan-refresh-node-list)
(def rotaryplatform-build-scan-select-node
  rotaryplatform/build-scan-select-node)
(def rotaryplatform-parse-scan-select-node
  rotaryplatform/parse-scan-select-node)
(def rotaryplatform-build-scan-delete-node
  rotaryplatform/build-scan-delete-node)
(def rotaryplatform-parse-scan-delete-node
  rotaryplatform/parse-scan-delete-node)
(def rotaryplatform-build-scan-update-node
  rotaryplatform/build-scan-update-node)
(def rotaryplatform-parse-scan-update-node
  rotaryplatform/parse-scan-update-node)
(def rotaryplatform-build-scan-add-node rotaryplatform/build-scan-add-node)
(def rotaryplatform-parse-scan-add-node rotaryplatform/parse-scan-add-node)
(def rotaryplatform-build-elevation rotaryplatform/build-elevation)
(def rotaryplatform-parse-elevation rotaryplatform/parse-elevation)
(def rotaryplatform-build-set-use-rotary-as-compass
  rotaryplatform/build-set-use-rotary-as-compass)
(def rotaryplatform-parse-set-use-rotary-as-compass
  rotaryplatform/parse-set-use-rotary-as-compass)
(def rotaryplatform-build-rotate-to-gps rotaryplatform/build-rotate-to-gps)
(def rotaryplatform-parse-rotate-to-gps rotaryplatform/parse-rotate-to-gps)
(def rotaryplatform-build-set-origin-gps rotaryplatform/build-set-origin-gps)
(def rotaryplatform-parse-set-origin-gps rotaryplatform/parse-set-origin-gps)
(def rotaryplatform-build-rotate-to-ndc rotaryplatform/build-rotate-to-ndc)
(def rotaryplatform-parse-rotate-to-ndc rotaryplatform/parse-rotate-to-ndc)
(def gps-build-root gps/build-root)
(def gps-parse-root gps/parse-root)
(def gps-build-start gps/build-start)
(def gps-parse-start gps/parse-start)
(def gps-build-stop gps/build-stop)
(def gps-parse-stop gps/parse-stop)
(def gps-build-get-meteo gps/build-get-meteo)
(def gps-parse-get-meteo gps/parse-get-meteo)
(def gps-build-set-use-manual-position gps/build-set-use-manual-position)
(def gps-parse-set-use-manual-position gps/parse-set-use-manual-position)
(def gps-build-set-manual-position gps/build-set-manual-position)
(def gps-parse-set-manual-position gps/parse-set-manual-position)
(def daycamglassheater-build-root daycamglassheater/build-root)
(def daycamglassheater-parse-root daycamglassheater/parse-root)
(def daycamglassheater-build-start daycamglassheater/build-start)
(def daycamglassheater-parse-start daycamglassheater/parse-start)
(def daycamglassheater-build-stop daycamglassheater/build-stop)
(def daycamglassheater-parse-stop daycamglassheater/parse-stop)
(def daycamglassheater-build-turn-on daycamglassheater/build-turn-on)
(def daycamglassheater-parse-turn-on daycamglassheater/parse-turn-on)
(def daycamglassheater-build-turn-off daycamglassheater/build-turn-off)
(def daycamglassheater-parse-turn-off daycamglassheater/parse-turn-off)
(def daycamglassheater-build-get-meteo daycamglassheater/build-get-meteo)
(def daycamglassheater-parse-get-meteo daycamglassheater/parse-get-meteo)
(def cv-build-root cv/build-root)
(def cv-parse-root cv/parse-root)
(def cv-build-vampire-mode-enable cv/build-vampire-mode-enable)
(def cv-parse-vampire-mode-enable cv/parse-vampire-mode-enable)
(def cv-build-dump-start cv/build-dump-start)
(def cv-parse-dump-start cv/parse-dump-start)
(def cv-build-dump-stop cv/build-dump-stop)
(def cv-parse-dump-stop cv/parse-dump-stop)
(def cv-build-vampire-mode-disable cv/build-vampire-mode-disable)
(def cv-parse-vampire-mode-disable cv/parse-vampire-mode-disable)
(def cv-build-stabilization-mode-enable cv/build-stabilization-mode-enable)
(def cv-parse-stabilization-mode-enable cv/parse-stabilization-mode-enable)
(def cv-build-stabilization-mode-disable cv/build-stabilization-mode-disable)
(def cv-parse-stabilization-mode-disable cv/parse-stabilization-mode-disable)
(def cv-build-set-auto-focus cv/build-set-auto-focus)
(def cv-parse-set-auto-focus cv/parse-set-auto-focus)
(def cv-build-start-track-ndc cv/build-start-track-ndc)
(def cv-parse-start-track-ndc cv/parse-start-track-ndc)
(def cv-build-stop-track cv/build-stop-track)
(def cv-parse-stop-track cv/parse-stop-track)
(def daycamera-build-set-value daycamera/build-set-value)
(def daycamera-parse-set-value daycamera/parse-set-value)
(def daycamera-build-move daycamera/build-move)
(def daycamera-parse-move daycamera/parse-move)
(def daycamera-build-offset daycamera/build-offset)
(def daycamera-parse-offset daycamera/parse-offset)
(def daycamera-build-set-clahe-level daycamera/build-set-clahe-level)
(def daycamera-parse-set-clahe-level daycamera/parse-set-clahe-level)
(def daycamera-build-shift-clahe-level daycamera/build-shift-clahe-level)
(def daycamera-parse-shift-clahe-level daycamera/parse-shift-clahe-level)
(def daycamera-build-root daycamera/build-root)
(def daycamera-parse-root daycamera/parse-root)
(def daycamera-build-get-pos daycamera/build-get-pos)
(def daycamera-parse-get-pos daycamera/parse-get-pos)
(def daycamera-build-next-fx-mode daycamera/build-next-fx-mode)
(def daycamera-parse-next-fx-mode daycamera/parse-next-fx-mode)
(def daycamera-build-prev-fx-mode daycamera/build-prev-fx-mode)
(def daycamera-parse-prev-fx-mode daycamera/parse-prev-fx-mode)
(def daycamera-build-refresh-fx-mode daycamera/build-refresh-fx-mode)
(def daycamera-parse-refresh-fx-mode daycamera/parse-refresh-fx-mode)
(def daycamera-build-halt-all daycamera/build-halt-all)
(def daycamera-parse-halt-all daycamera/parse-halt-all)
(def daycamera-build-set-fx-mode daycamera/build-set-fx-mode)
(def daycamera-parse-set-fx-mode daycamera/parse-set-fx-mode)
(def daycamera-build-set-digital-zoom-level
  daycamera/build-set-digital-zoom-level)
(def daycamera-parse-set-digital-zoom-level
  daycamera/parse-set-digital-zoom-level)
(def daycamera-build-focus daycamera/build-focus)
(def daycamera-parse-focus daycamera/parse-focus)
(def daycamera-build-zoom daycamera/build-zoom)
(def daycamera-parse-zoom daycamera/parse-zoom)
(def daycamera-build-next-zoom-table-pos daycamera/build-next-zoom-table-pos)
(def daycamera-parse-next-zoom-table-pos daycamera/parse-next-zoom-table-pos)
(def daycamera-build-prev-zoom-table-pos daycamera/build-prev-zoom-table-pos)
(def daycamera-parse-prev-zoom-table-pos daycamera/parse-prev-zoom-table-pos)
(def daycamera-build-set-iris daycamera/build-set-iris)
(def daycamera-parse-set-iris daycamera/parse-set-iris)
(def daycamera-build-set-infra-red-filter daycamera/build-set-infra-red-filter)
(def daycamera-parse-set-infra-red-filter daycamera/parse-set-infra-red-filter)
(def daycamera-build-set-auto-iris daycamera/build-set-auto-iris)
(def daycamera-parse-set-auto-iris daycamera/parse-set-auto-iris)
(def daycamera-build-set-zoom-table-value daycamera/build-set-zoom-table-value)
(def daycamera-parse-set-zoom-table-value daycamera/parse-set-zoom-table-value)
(def daycamera-build-stop daycamera/build-stop)
(def daycamera-parse-stop daycamera/parse-stop)
(def daycamera-build-start daycamera/build-start)
(def daycamera-parse-start daycamera/parse-start)
(def daycamera-build-photo daycamera/build-photo)
(def daycamera-parse-photo daycamera/parse-photo)
(def daycamera-build-halt daycamera/build-halt)
(def daycamera-parse-halt daycamera/parse-halt)
(def daycamera-build-get-meteo daycamera/build-get-meteo)
(def daycamera-parse-get-meteo daycamera/parse-get-meteo)
(def daycamera-build-reset-zoom daycamera/build-reset-zoom)
(def daycamera-parse-reset-zoom daycamera/parse-reset-zoom)
(def daycamera-build-reset-focus daycamera/build-reset-focus)
(def daycamera-parse-reset-focus daycamera/parse-reset-focus)
(def daycamera-build-save-to-table daycamera/build-save-to-table)
(def daycamera-parse-save-to-table daycamera/parse-save-to-table)
(def daycamera-build-save-to-table-focus daycamera/build-save-to-table-focus)
(def daycamera-parse-save-to-table-focus daycamera/parse-save-to-table-focus)
