// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jon_shared_data_rotary.proto

package ser;

public final class JonSharedDataRotary {
  private JonSharedDataRotary() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JonGuiDataRotaryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ser.JonGuiDataRotary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float azimuth = 1;</code>
     * @return The azimuth.
     */
    float getAzimuth();

    /**
     * <code>float azimuth_speed = 2;</code>
     * @return The azimuthSpeed.
     */
    float getAzimuthSpeed();

    /**
     * <code>float elevation = 3;</code>
     * @return The elevation.
     */
    float getElevation();

    /**
     * <code>float elevation_speed = 4;</code>
     * @return The elevationSpeed.
     */
    float getElevationSpeed();

    /**
     * <code>float platform_azimuth = 5;</code>
     * @return The platformAzimuth.
     */
    float getPlatformAzimuth();

    /**
     * <code>float platform_elevation = 6;</code>
     * @return The platformElevation.
     */
    float getPlatformElevation();

    /**
     * <code>float platform_bank = 7;</code>
     * @return The platformBank.
     */
    float getPlatformBank();

    /**
     * <code>bool is_moving = 8;</code>
     * @return The isMoving.
     */
    boolean getIsMoving();

    /**
     * <code>.ser.JonGuiDataRotaryMode mode = 9;</code>
     * @return The enum numeric value on the wire for mode.
     */
    int getModeValue();
    /**
     * <code>.ser.JonGuiDataRotaryMode mode = 9;</code>
     * @return The mode.
     */
    ser.JonSharedDataTypes.JonGuiDataRotaryMode getMode();

    /**
     * <code>bool is_scanning = 10;</code>
     * @return The isScanning.
     */
    boolean getIsScanning();

    /**
     * <code>bool is_scanning_paused = 11;</code>
     * @return The isScanningPaused.
     */
    boolean getIsScanningPaused();

    /**
     * <code>bool use_rotary_as_compass = 12;</code>
     * @return The useRotaryAsCompass.
     */
    boolean getUseRotaryAsCompass();

    /**
     * <code>int32 scan_target = 13;</code>
     * @return The scanTarget.
     */
    int getScanTarget();

    /**
     * <code>int32 scan_target_max = 14;</code>
     * @return The scanTargetMax.
     */
    int getScanTargetMax();

    /**
     * <code>float sun_azimuth = 15;</code>
     * @return The sunAzimuth.
     */
    float getSunAzimuth();

    /**
     * <code>float sun_elevation = 16;</code>
     * @return The sunElevation.
     */
    float getSunElevation();

    /**
     * <code>.ser.ScanNode current_scan_node = 17;</code>
     * @return Whether the currentScanNode field is set.
     */
    boolean hasCurrentScanNode();
    /**
     * <code>.ser.ScanNode current_scan_node = 17;</code>
     * @return The currentScanNode.
     */
    ser.JonSharedDataRotary.ScanNode getCurrentScanNode();
    /**
     * <code>.ser.ScanNode current_scan_node = 17;</code>
     */
    ser.JonSharedDataRotary.ScanNodeOrBuilder getCurrentScanNodeOrBuilder();
  }
  /**
   * Protobuf type {@code ser.JonGuiDataRotary}
   */
  public static final class JonGuiDataRotary extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ser.JonGuiDataRotary)
      JonGuiDataRotaryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JonGuiDataRotary.newBuilder() to construct.
    private JonGuiDataRotary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JonGuiDataRotary() {
      mode_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JonGuiDataRotary();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JonGuiDataRotary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              azimuth_ = input.readFloat();
              break;
            }
            case 21: {

              azimuthSpeed_ = input.readFloat();
              break;
            }
            case 29: {

              elevation_ = input.readFloat();
              break;
            }
            case 37: {

              elevationSpeed_ = input.readFloat();
              break;
            }
            case 45: {

              platformAzimuth_ = input.readFloat();
              break;
            }
            case 53: {

              platformElevation_ = input.readFloat();
              break;
            }
            case 61: {

              platformBank_ = input.readFloat();
              break;
            }
            case 64: {

              isMoving_ = input.readBool();
              break;
            }
            case 72: {
              int rawValue = input.readEnum();

              mode_ = rawValue;
              break;
            }
            case 80: {

              isScanning_ = input.readBool();
              break;
            }
            case 88: {

              isScanningPaused_ = input.readBool();
              break;
            }
            case 96: {

              useRotaryAsCompass_ = input.readBool();
              break;
            }
            case 104: {

              scanTarget_ = input.readInt32();
              break;
            }
            case 112: {

              scanTargetMax_ = input.readInt32();
              break;
            }
            case 125: {

              sunAzimuth_ = input.readFloat();
              break;
            }
            case 133: {

              sunElevation_ = input.readFloat();
              break;
            }
            case 138: {
              ser.JonSharedDataRotary.ScanNode.Builder subBuilder = null;
              if (currentScanNode_ != null) {
                subBuilder = currentScanNode_.toBuilder();
              }
              currentScanNode_ = input.readMessage(ser.JonSharedDataRotary.ScanNode.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(currentScanNode_);
                currentScanNode_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ser.JonSharedDataRotary.internal_static_ser_JonGuiDataRotary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ser.JonSharedDataRotary.internal_static_ser_JonGuiDataRotary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ser.JonSharedDataRotary.JonGuiDataRotary.class, ser.JonSharedDataRotary.JonGuiDataRotary.Builder.class);
    }

    public static final int AZIMUTH_FIELD_NUMBER = 1;
    private float azimuth_;
    /**
     * <code>float azimuth = 1;</code>
     * @return The azimuth.
     */
    @java.lang.Override
    public float getAzimuth() {
      return azimuth_;
    }

    public static final int AZIMUTH_SPEED_FIELD_NUMBER = 2;
    private float azimuthSpeed_;
    /**
     * <code>float azimuth_speed = 2;</code>
     * @return The azimuthSpeed.
     */
    @java.lang.Override
    public float getAzimuthSpeed() {
      return azimuthSpeed_;
    }

    public static final int ELEVATION_FIELD_NUMBER = 3;
    private float elevation_;
    /**
     * <code>float elevation = 3;</code>
     * @return The elevation.
     */
    @java.lang.Override
    public float getElevation() {
      return elevation_;
    }

    public static final int ELEVATION_SPEED_FIELD_NUMBER = 4;
    private float elevationSpeed_;
    /**
     * <code>float elevation_speed = 4;</code>
     * @return The elevationSpeed.
     */
    @java.lang.Override
    public float getElevationSpeed() {
      return elevationSpeed_;
    }

    public static final int PLATFORM_AZIMUTH_FIELD_NUMBER = 5;
    private float platformAzimuth_;
    /**
     * <code>float platform_azimuth = 5;</code>
     * @return The platformAzimuth.
     */
    @java.lang.Override
    public float getPlatformAzimuth() {
      return platformAzimuth_;
    }

    public static final int PLATFORM_ELEVATION_FIELD_NUMBER = 6;
    private float platformElevation_;
    /**
     * <code>float platform_elevation = 6;</code>
     * @return The platformElevation.
     */
    @java.lang.Override
    public float getPlatformElevation() {
      return platformElevation_;
    }

    public static final int PLATFORM_BANK_FIELD_NUMBER = 7;
    private float platformBank_;
    /**
     * <code>float platform_bank = 7;</code>
     * @return The platformBank.
     */
    @java.lang.Override
    public float getPlatformBank() {
      return platformBank_;
    }

    public static final int IS_MOVING_FIELD_NUMBER = 8;
    private boolean isMoving_;
    /**
     * <code>bool is_moving = 8;</code>
     * @return The isMoving.
     */
    @java.lang.Override
    public boolean getIsMoving() {
      return isMoving_;
    }

    public static final int MODE_FIELD_NUMBER = 9;
    private int mode_;
    /**
     * <code>.ser.JonGuiDataRotaryMode mode = 9;</code>
     * @return The enum numeric value on the wire for mode.
     */
    @java.lang.Override public int getModeValue() {
      return mode_;
    }
    /**
     * <code>.ser.JonGuiDataRotaryMode mode = 9;</code>
     * @return The mode.
     */
    @java.lang.Override public ser.JonSharedDataTypes.JonGuiDataRotaryMode getMode() {
      @SuppressWarnings("deprecation")
      ser.JonSharedDataTypes.JonGuiDataRotaryMode result = ser.JonSharedDataTypes.JonGuiDataRotaryMode.valueOf(mode_);
      return result == null ? ser.JonSharedDataTypes.JonGuiDataRotaryMode.UNRECOGNIZED : result;
    }

    public static final int IS_SCANNING_FIELD_NUMBER = 10;
    private boolean isScanning_;
    /**
     * <code>bool is_scanning = 10;</code>
     * @return The isScanning.
     */
    @java.lang.Override
    public boolean getIsScanning() {
      return isScanning_;
    }

    public static final int IS_SCANNING_PAUSED_FIELD_NUMBER = 11;
    private boolean isScanningPaused_;
    /**
     * <code>bool is_scanning_paused = 11;</code>
     * @return The isScanningPaused.
     */
    @java.lang.Override
    public boolean getIsScanningPaused() {
      return isScanningPaused_;
    }

    public static final int USE_ROTARY_AS_COMPASS_FIELD_NUMBER = 12;
    private boolean useRotaryAsCompass_;
    /**
     * <code>bool use_rotary_as_compass = 12;</code>
     * @return The useRotaryAsCompass.
     */
    @java.lang.Override
    public boolean getUseRotaryAsCompass() {
      return useRotaryAsCompass_;
    }

    public static final int SCAN_TARGET_FIELD_NUMBER = 13;
    private int scanTarget_;
    /**
     * <code>int32 scan_target = 13;</code>
     * @return The scanTarget.
     */
    @java.lang.Override
    public int getScanTarget() {
      return scanTarget_;
    }

    public static final int SCAN_TARGET_MAX_FIELD_NUMBER = 14;
    private int scanTargetMax_;
    /**
     * <code>int32 scan_target_max = 14;</code>
     * @return The scanTargetMax.
     */
    @java.lang.Override
    public int getScanTargetMax() {
      return scanTargetMax_;
    }

    public static final int SUN_AZIMUTH_FIELD_NUMBER = 15;
    private float sunAzimuth_;
    /**
     * <code>float sun_azimuth = 15;</code>
     * @return The sunAzimuth.
     */
    @java.lang.Override
    public float getSunAzimuth() {
      return sunAzimuth_;
    }

    public static final int SUN_ELEVATION_FIELD_NUMBER = 16;
    private float sunElevation_;
    /**
     * <code>float sun_elevation = 16;</code>
     * @return The sunElevation.
     */
    @java.lang.Override
    public float getSunElevation() {
      return sunElevation_;
    }

    public static final int CURRENT_SCAN_NODE_FIELD_NUMBER = 17;
    private ser.JonSharedDataRotary.ScanNode currentScanNode_;
    /**
     * <code>.ser.ScanNode current_scan_node = 17;</code>
     * @return Whether the currentScanNode field is set.
     */
    @java.lang.Override
    public boolean hasCurrentScanNode() {
      return currentScanNode_ != null;
    }
    /**
     * <code>.ser.ScanNode current_scan_node = 17;</code>
     * @return The currentScanNode.
     */
    @java.lang.Override
    public ser.JonSharedDataRotary.ScanNode getCurrentScanNode() {
      return currentScanNode_ == null ? ser.JonSharedDataRotary.ScanNode.getDefaultInstance() : currentScanNode_;
    }
    /**
     * <code>.ser.ScanNode current_scan_node = 17;</code>
     */
    @java.lang.Override
    public ser.JonSharedDataRotary.ScanNodeOrBuilder getCurrentScanNodeOrBuilder() {
      return getCurrentScanNode();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (azimuth_ != 0F) {
        output.writeFloat(1, azimuth_);
      }
      if (azimuthSpeed_ != 0F) {
        output.writeFloat(2, azimuthSpeed_);
      }
      if (elevation_ != 0F) {
        output.writeFloat(3, elevation_);
      }
      if (elevationSpeed_ != 0F) {
        output.writeFloat(4, elevationSpeed_);
      }
      if (platformAzimuth_ != 0F) {
        output.writeFloat(5, platformAzimuth_);
      }
      if (platformElevation_ != 0F) {
        output.writeFloat(6, platformElevation_);
      }
      if (platformBank_ != 0F) {
        output.writeFloat(7, platformBank_);
      }
      if (isMoving_ != false) {
        output.writeBool(8, isMoving_);
      }
      if (mode_ != ser.JonSharedDataTypes.JonGuiDataRotaryMode.JON_GUI_DATA_ROTARY_MODE_UNSPECIFIED.getNumber()) {
        output.writeEnum(9, mode_);
      }
      if (isScanning_ != false) {
        output.writeBool(10, isScanning_);
      }
      if (isScanningPaused_ != false) {
        output.writeBool(11, isScanningPaused_);
      }
      if (useRotaryAsCompass_ != false) {
        output.writeBool(12, useRotaryAsCompass_);
      }
      if (scanTarget_ != 0) {
        output.writeInt32(13, scanTarget_);
      }
      if (scanTargetMax_ != 0) {
        output.writeInt32(14, scanTargetMax_);
      }
      if (sunAzimuth_ != 0F) {
        output.writeFloat(15, sunAzimuth_);
      }
      if (sunElevation_ != 0F) {
        output.writeFloat(16, sunElevation_);
      }
      if (currentScanNode_ != null) {
        output.writeMessage(17, getCurrentScanNode());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (azimuth_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, azimuth_);
      }
      if (azimuthSpeed_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, azimuthSpeed_);
      }
      if (elevation_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, elevation_);
      }
      if (elevationSpeed_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, elevationSpeed_);
      }
      if (platformAzimuth_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, platformAzimuth_);
      }
      if (platformElevation_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, platformElevation_);
      }
      if (platformBank_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, platformBank_);
      }
      if (isMoving_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, isMoving_);
      }
      if (mode_ != ser.JonSharedDataTypes.JonGuiDataRotaryMode.JON_GUI_DATA_ROTARY_MODE_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, mode_);
      }
      if (isScanning_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, isScanning_);
      }
      if (isScanningPaused_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, isScanningPaused_);
      }
      if (useRotaryAsCompass_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, useRotaryAsCompass_);
      }
      if (scanTarget_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, scanTarget_);
      }
      if (scanTargetMax_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, scanTargetMax_);
      }
      if (sunAzimuth_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(15, sunAzimuth_);
      }
      if (sunElevation_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(16, sunElevation_);
      }
      if (currentScanNode_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(17, getCurrentScanNode());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ser.JonSharedDataRotary.JonGuiDataRotary)) {
        return super.equals(obj);
      }
      ser.JonSharedDataRotary.JonGuiDataRotary other = (ser.JonSharedDataRotary.JonGuiDataRotary) obj;

      if (java.lang.Float.floatToIntBits(getAzimuth())
          != java.lang.Float.floatToIntBits(
              other.getAzimuth())) return false;
      if (java.lang.Float.floatToIntBits(getAzimuthSpeed())
          != java.lang.Float.floatToIntBits(
              other.getAzimuthSpeed())) return false;
      if (java.lang.Float.floatToIntBits(getElevation())
          != java.lang.Float.floatToIntBits(
              other.getElevation())) return false;
      if (java.lang.Float.floatToIntBits(getElevationSpeed())
          != java.lang.Float.floatToIntBits(
              other.getElevationSpeed())) return false;
      if (java.lang.Float.floatToIntBits(getPlatformAzimuth())
          != java.lang.Float.floatToIntBits(
              other.getPlatformAzimuth())) return false;
      if (java.lang.Float.floatToIntBits(getPlatformElevation())
          != java.lang.Float.floatToIntBits(
              other.getPlatformElevation())) return false;
      if (java.lang.Float.floatToIntBits(getPlatformBank())
          != java.lang.Float.floatToIntBits(
              other.getPlatformBank())) return false;
      if (getIsMoving()
          != other.getIsMoving()) return false;
      if (mode_ != other.mode_) return false;
      if (getIsScanning()
          != other.getIsScanning()) return false;
      if (getIsScanningPaused()
          != other.getIsScanningPaused()) return false;
      if (getUseRotaryAsCompass()
          != other.getUseRotaryAsCompass()) return false;
      if (getScanTarget()
          != other.getScanTarget()) return false;
      if (getScanTargetMax()
          != other.getScanTargetMax()) return false;
      if (java.lang.Float.floatToIntBits(getSunAzimuth())
          != java.lang.Float.floatToIntBits(
              other.getSunAzimuth())) return false;
      if (java.lang.Float.floatToIntBits(getSunElevation())
          != java.lang.Float.floatToIntBits(
              other.getSunElevation())) return false;
      if (hasCurrentScanNode() != other.hasCurrentScanNode()) return false;
      if (hasCurrentScanNode()) {
        if (!getCurrentScanNode()
            .equals(other.getCurrentScanNode())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AZIMUTH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAzimuth());
      hash = (37 * hash) + AZIMUTH_SPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAzimuthSpeed());
      hash = (37 * hash) + ELEVATION_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getElevation());
      hash = (37 * hash) + ELEVATION_SPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getElevationSpeed());
      hash = (37 * hash) + PLATFORM_AZIMUTH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPlatformAzimuth());
      hash = (37 * hash) + PLATFORM_ELEVATION_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPlatformElevation());
      hash = (37 * hash) + PLATFORM_BANK_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPlatformBank());
      hash = (37 * hash) + IS_MOVING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsMoving());
      hash = (37 * hash) + MODE_FIELD_NUMBER;
      hash = (53 * hash) + mode_;
      hash = (37 * hash) + IS_SCANNING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsScanning());
      hash = (37 * hash) + IS_SCANNING_PAUSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsScanningPaused());
      hash = (37 * hash) + USE_ROTARY_AS_COMPASS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUseRotaryAsCompass());
      hash = (37 * hash) + SCAN_TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getScanTarget();
      hash = (37 * hash) + SCAN_TARGET_MAX_FIELD_NUMBER;
      hash = (53 * hash) + getScanTargetMax();
      hash = (37 * hash) + SUN_AZIMUTH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSunAzimuth());
      hash = (37 * hash) + SUN_ELEVATION_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSunElevation());
      if (hasCurrentScanNode()) {
        hash = (37 * hash) + CURRENT_SCAN_NODE_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentScanNode().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ser.JonSharedDataRotary.JonGuiDataRotary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataRotary.JonGuiDataRotary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataRotary.JonGuiDataRotary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataRotary.JonGuiDataRotary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataRotary.JonGuiDataRotary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataRotary.JonGuiDataRotary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataRotary.JonGuiDataRotary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataRotary.JonGuiDataRotary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataRotary.JonGuiDataRotary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataRotary.JonGuiDataRotary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataRotary.JonGuiDataRotary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataRotary.JonGuiDataRotary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ser.JonSharedDataRotary.JonGuiDataRotary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ser.JonGuiDataRotary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ser.JonGuiDataRotary)
        ser.JonSharedDataRotary.JonGuiDataRotaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ser.JonSharedDataRotary.internal_static_ser_JonGuiDataRotary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ser.JonSharedDataRotary.internal_static_ser_JonGuiDataRotary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ser.JonSharedDataRotary.JonGuiDataRotary.class, ser.JonSharedDataRotary.JonGuiDataRotary.Builder.class);
      }

      // Construct using ser.JonSharedDataRotary.JonGuiDataRotary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        azimuth_ = 0F;

        azimuthSpeed_ = 0F;

        elevation_ = 0F;

        elevationSpeed_ = 0F;

        platformAzimuth_ = 0F;

        platformElevation_ = 0F;

        platformBank_ = 0F;

        isMoving_ = false;

        mode_ = 0;

        isScanning_ = false;

        isScanningPaused_ = false;

        useRotaryAsCompass_ = false;

        scanTarget_ = 0;

        scanTargetMax_ = 0;

        sunAzimuth_ = 0F;

        sunElevation_ = 0F;

        if (currentScanNodeBuilder_ == null) {
          currentScanNode_ = null;
        } else {
          currentScanNode_ = null;
          currentScanNodeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ser.JonSharedDataRotary.internal_static_ser_JonGuiDataRotary_descriptor;
      }

      @java.lang.Override
      public ser.JonSharedDataRotary.JonGuiDataRotary getDefaultInstanceForType() {
        return ser.JonSharedDataRotary.JonGuiDataRotary.getDefaultInstance();
      }

      @java.lang.Override
      public ser.JonSharedDataRotary.JonGuiDataRotary build() {
        ser.JonSharedDataRotary.JonGuiDataRotary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ser.JonSharedDataRotary.JonGuiDataRotary buildPartial() {
        ser.JonSharedDataRotary.JonGuiDataRotary result = new ser.JonSharedDataRotary.JonGuiDataRotary(this);
        result.azimuth_ = azimuth_;
        result.azimuthSpeed_ = azimuthSpeed_;
        result.elevation_ = elevation_;
        result.elevationSpeed_ = elevationSpeed_;
        result.platformAzimuth_ = platformAzimuth_;
        result.platformElevation_ = platformElevation_;
        result.platformBank_ = platformBank_;
        result.isMoving_ = isMoving_;
        result.mode_ = mode_;
        result.isScanning_ = isScanning_;
        result.isScanningPaused_ = isScanningPaused_;
        result.useRotaryAsCompass_ = useRotaryAsCompass_;
        result.scanTarget_ = scanTarget_;
        result.scanTargetMax_ = scanTargetMax_;
        result.sunAzimuth_ = sunAzimuth_;
        result.sunElevation_ = sunElevation_;
        if (currentScanNodeBuilder_ == null) {
          result.currentScanNode_ = currentScanNode_;
        } else {
          result.currentScanNode_ = currentScanNodeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ser.JonSharedDataRotary.JonGuiDataRotary) {
          return mergeFrom((ser.JonSharedDataRotary.JonGuiDataRotary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ser.JonSharedDataRotary.JonGuiDataRotary other) {
        if (other == ser.JonSharedDataRotary.JonGuiDataRotary.getDefaultInstance()) return this;
        if (other.getAzimuth() != 0F) {
          setAzimuth(other.getAzimuth());
        }
        if (other.getAzimuthSpeed() != 0F) {
          setAzimuthSpeed(other.getAzimuthSpeed());
        }
        if (other.getElevation() != 0F) {
          setElevation(other.getElevation());
        }
        if (other.getElevationSpeed() != 0F) {
          setElevationSpeed(other.getElevationSpeed());
        }
        if (other.getPlatformAzimuth() != 0F) {
          setPlatformAzimuth(other.getPlatformAzimuth());
        }
        if (other.getPlatformElevation() != 0F) {
          setPlatformElevation(other.getPlatformElevation());
        }
        if (other.getPlatformBank() != 0F) {
          setPlatformBank(other.getPlatformBank());
        }
        if (other.getIsMoving() != false) {
          setIsMoving(other.getIsMoving());
        }
        if (other.mode_ != 0) {
          setModeValue(other.getModeValue());
        }
        if (other.getIsScanning() != false) {
          setIsScanning(other.getIsScanning());
        }
        if (other.getIsScanningPaused() != false) {
          setIsScanningPaused(other.getIsScanningPaused());
        }
        if (other.getUseRotaryAsCompass() != false) {
          setUseRotaryAsCompass(other.getUseRotaryAsCompass());
        }
        if (other.getScanTarget() != 0) {
          setScanTarget(other.getScanTarget());
        }
        if (other.getScanTargetMax() != 0) {
          setScanTargetMax(other.getScanTargetMax());
        }
        if (other.getSunAzimuth() != 0F) {
          setSunAzimuth(other.getSunAzimuth());
        }
        if (other.getSunElevation() != 0F) {
          setSunElevation(other.getSunElevation());
        }
        if (other.hasCurrentScanNode()) {
          mergeCurrentScanNode(other.getCurrentScanNode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ser.JonSharedDataRotary.JonGuiDataRotary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ser.JonSharedDataRotary.JonGuiDataRotary) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float azimuth_ ;
      /**
       * <code>float azimuth = 1;</code>
       * @return The azimuth.
       */
      @java.lang.Override
      public float getAzimuth() {
        return azimuth_;
      }
      /**
       * <code>float azimuth = 1;</code>
       * @param value The azimuth to set.
       * @return This builder for chaining.
       */
      public Builder setAzimuth(float value) {
        
        azimuth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float azimuth = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAzimuth() {
        
        azimuth_ = 0F;
        onChanged();
        return this;
      }

      private float azimuthSpeed_ ;
      /**
       * <code>float azimuth_speed = 2;</code>
       * @return The azimuthSpeed.
       */
      @java.lang.Override
      public float getAzimuthSpeed() {
        return azimuthSpeed_;
      }
      /**
       * <code>float azimuth_speed = 2;</code>
       * @param value The azimuthSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setAzimuthSpeed(float value) {
        
        azimuthSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float azimuth_speed = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAzimuthSpeed() {
        
        azimuthSpeed_ = 0F;
        onChanged();
        return this;
      }

      private float elevation_ ;
      /**
       * <code>float elevation = 3;</code>
       * @return The elevation.
       */
      @java.lang.Override
      public float getElevation() {
        return elevation_;
      }
      /**
       * <code>float elevation = 3;</code>
       * @param value The elevation to set.
       * @return This builder for chaining.
       */
      public Builder setElevation(float value) {
        
        elevation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float elevation = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearElevation() {
        
        elevation_ = 0F;
        onChanged();
        return this;
      }

      private float elevationSpeed_ ;
      /**
       * <code>float elevation_speed = 4;</code>
       * @return The elevationSpeed.
       */
      @java.lang.Override
      public float getElevationSpeed() {
        return elevationSpeed_;
      }
      /**
       * <code>float elevation_speed = 4;</code>
       * @param value The elevationSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setElevationSpeed(float value) {
        
        elevationSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float elevation_speed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearElevationSpeed() {
        
        elevationSpeed_ = 0F;
        onChanged();
        return this;
      }

      private float platformAzimuth_ ;
      /**
       * <code>float platform_azimuth = 5;</code>
       * @return The platformAzimuth.
       */
      @java.lang.Override
      public float getPlatformAzimuth() {
        return platformAzimuth_;
      }
      /**
       * <code>float platform_azimuth = 5;</code>
       * @param value The platformAzimuth to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformAzimuth(float value) {
        
        platformAzimuth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float platform_azimuth = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlatformAzimuth() {
        
        platformAzimuth_ = 0F;
        onChanged();
        return this;
      }

      private float platformElevation_ ;
      /**
       * <code>float platform_elevation = 6;</code>
       * @return The platformElevation.
       */
      @java.lang.Override
      public float getPlatformElevation() {
        return platformElevation_;
      }
      /**
       * <code>float platform_elevation = 6;</code>
       * @param value The platformElevation to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformElevation(float value) {
        
        platformElevation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float platform_elevation = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlatformElevation() {
        
        platformElevation_ = 0F;
        onChanged();
        return this;
      }

      private float platformBank_ ;
      /**
       * <code>float platform_bank = 7;</code>
       * @return The platformBank.
       */
      @java.lang.Override
      public float getPlatformBank() {
        return platformBank_;
      }
      /**
       * <code>float platform_bank = 7;</code>
       * @param value The platformBank to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformBank(float value) {
        
        platformBank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float platform_bank = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlatformBank() {
        
        platformBank_ = 0F;
        onChanged();
        return this;
      }

      private boolean isMoving_ ;
      /**
       * <code>bool is_moving = 8;</code>
       * @return The isMoving.
       */
      @java.lang.Override
      public boolean getIsMoving() {
        return isMoving_;
      }
      /**
       * <code>bool is_moving = 8;</code>
       * @param value The isMoving to set.
       * @return This builder for chaining.
       */
      public Builder setIsMoving(boolean value) {
        
        isMoving_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_moving = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsMoving() {
        
        isMoving_ = false;
        onChanged();
        return this;
      }

      private int mode_ = 0;
      /**
       * <code>.ser.JonGuiDataRotaryMode mode = 9;</code>
       * @return The enum numeric value on the wire for mode.
       */
      @java.lang.Override public int getModeValue() {
        return mode_;
      }
      /**
       * <code>.ser.JonGuiDataRotaryMode mode = 9;</code>
       * @param value The enum numeric value on the wire for mode to set.
       * @return This builder for chaining.
       */
      public Builder setModeValue(int value) {
        
        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ser.JonGuiDataRotaryMode mode = 9;</code>
       * @return The mode.
       */
      @java.lang.Override
      public ser.JonSharedDataTypes.JonGuiDataRotaryMode getMode() {
        @SuppressWarnings("deprecation")
        ser.JonSharedDataTypes.JonGuiDataRotaryMode result = ser.JonSharedDataTypes.JonGuiDataRotaryMode.valueOf(mode_);
        return result == null ? ser.JonSharedDataTypes.JonGuiDataRotaryMode.UNRECOGNIZED : result;
      }
      /**
       * <code>.ser.JonGuiDataRotaryMode mode = 9;</code>
       * @param value The mode to set.
       * @return This builder for chaining.
       */
      public Builder setMode(ser.JonSharedDataTypes.JonGuiDataRotaryMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        mode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ser.JonGuiDataRotaryMode mode = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearMode() {
        
        mode_ = 0;
        onChanged();
        return this;
      }

      private boolean isScanning_ ;
      /**
       * <code>bool is_scanning = 10;</code>
       * @return The isScanning.
       */
      @java.lang.Override
      public boolean getIsScanning() {
        return isScanning_;
      }
      /**
       * <code>bool is_scanning = 10;</code>
       * @param value The isScanning to set.
       * @return This builder for chaining.
       */
      public Builder setIsScanning(boolean value) {
        
        isScanning_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_scanning = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsScanning() {
        
        isScanning_ = false;
        onChanged();
        return this;
      }

      private boolean isScanningPaused_ ;
      /**
       * <code>bool is_scanning_paused = 11;</code>
       * @return The isScanningPaused.
       */
      @java.lang.Override
      public boolean getIsScanningPaused() {
        return isScanningPaused_;
      }
      /**
       * <code>bool is_scanning_paused = 11;</code>
       * @param value The isScanningPaused to set.
       * @return This builder for chaining.
       */
      public Builder setIsScanningPaused(boolean value) {
        
        isScanningPaused_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_scanning_paused = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsScanningPaused() {
        
        isScanningPaused_ = false;
        onChanged();
        return this;
      }

      private boolean useRotaryAsCompass_ ;
      /**
       * <code>bool use_rotary_as_compass = 12;</code>
       * @return The useRotaryAsCompass.
       */
      @java.lang.Override
      public boolean getUseRotaryAsCompass() {
        return useRotaryAsCompass_;
      }
      /**
       * <code>bool use_rotary_as_compass = 12;</code>
       * @param value The useRotaryAsCompass to set.
       * @return This builder for chaining.
       */
      public Builder setUseRotaryAsCompass(boolean value) {
        
        useRotaryAsCompass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool use_rotary_as_compass = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearUseRotaryAsCompass() {
        
        useRotaryAsCompass_ = false;
        onChanged();
        return this;
      }

      private int scanTarget_ ;
      /**
       * <code>int32 scan_target = 13;</code>
       * @return The scanTarget.
       */
      @java.lang.Override
      public int getScanTarget() {
        return scanTarget_;
      }
      /**
       * <code>int32 scan_target = 13;</code>
       * @param value The scanTarget to set.
       * @return This builder for chaining.
       */
      public Builder setScanTarget(int value) {
        
        scanTarget_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 scan_target = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearScanTarget() {
        
        scanTarget_ = 0;
        onChanged();
        return this;
      }

      private int scanTargetMax_ ;
      /**
       * <code>int32 scan_target_max = 14;</code>
       * @return The scanTargetMax.
       */
      @java.lang.Override
      public int getScanTargetMax() {
        return scanTargetMax_;
      }
      /**
       * <code>int32 scan_target_max = 14;</code>
       * @param value The scanTargetMax to set.
       * @return This builder for chaining.
       */
      public Builder setScanTargetMax(int value) {
        
        scanTargetMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 scan_target_max = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearScanTargetMax() {
        
        scanTargetMax_ = 0;
        onChanged();
        return this;
      }

      private float sunAzimuth_ ;
      /**
       * <code>float sun_azimuth = 15;</code>
       * @return The sunAzimuth.
       */
      @java.lang.Override
      public float getSunAzimuth() {
        return sunAzimuth_;
      }
      /**
       * <code>float sun_azimuth = 15;</code>
       * @param value The sunAzimuth to set.
       * @return This builder for chaining.
       */
      public Builder setSunAzimuth(float value) {
        
        sunAzimuth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float sun_azimuth = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearSunAzimuth() {
        
        sunAzimuth_ = 0F;
        onChanged();
        return this;
      }

      private float sunElevation_ ;
      /**
       * <code>float sun_elevation = 16;</code>
       * @return The sunElevation.
       */
      @java.lang.Override
      public float getSunElevation() {
        return sunElevation_;
      }
      /**
       * <code>float sun_elevation = 16;</code>
       * @param value The sunElevation to set.
       * @return This builder for chaining.
       */
      public Builder setSunElevation(float value) {
        
        sunElevation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float sun_elevation = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearSunElevation() {
        
        sunElevation_ = 0F;
        onChanged();
        return this;
      }

      private ser.JonSharedDataRotary.ScanNode currentScanNode_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ser.JonSharedDataRotary.ScanNode, ser.JonSharedDataRotary.ScanNode.Builder, ser.JonSharedDataRotary.ScanNodeOrBuilder> currentScanNodeBuilder_;
      /**
       * <code>.ser.ScanNode current_scan_node = 17;</code>
       * @return Whether the currentScanNode field is set.
       */
      public boolean hasCurrentScanNode() {
        return currentScanNodeBuilder_ != null || currentScanNode_ != null;
      }
      /**
       * <code>.ser.ScanNode current_scan_node = 17;</code>
       * @return The currentScanNode.
       */
      public ser.JonSharedDataRotary.ScanNode getCurrentScanNode() {
        if (currentScanNodeBuilder_ == null) {
          return currentScanNode_ == null ? ser.JonSharedDataRotary.ScanNode.getDefaultInstance() : currentScanNode_;
        } else {
          return currentScanNodeBuilder_.getMessage();
        }
      }
      /**
       * <code>.ser.ScanNode current_scan_node = 17;</code>
       */
      public Builder setCurrentScanNode(ser.JonSharedDataRotary.ScanNode value) {
        if (currentScanNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          currentScanNode_ = value;
          onChanged();
        } else {
          currentScanNodeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ser.ScanNode current_scan_node = 17;</code>
       */
      public Builder setCurrentScanNode(
          ser.JonSharedDataRotary.ScanNode.Builder builderForValue) {
        if (currentScanNodeBuilder_ == null) {
          currentScanNode_ = builderForValue.build();
          onChanged();
        } else {
          currentScanNodeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ser.ScanNode current_scan_node = 17;</code>
       */
      public Builder mergeCurrentScanNode(ser.JonSharedDataRotary.ScanNode value) {
        if (currentScanNodeBuilder_ == null) {
          if (currentScanNode_ != null) {
            currentScanNode_ =
              ser.JonSharedDataRotary.ScanNode.newBuilder(currentScanNode_).mergeFrom(value).buildPartial();
          } else {
            currentScanNode_ = value;
          }
          onChanged();
        } else {
          currentScanNodeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ser.ScanNode current_scan_node = 17;</code>
       */
      public Builder clearCurrentScanNode() {
        if (currentScanNodeBuilder_ == null) {
          currentScanNode_ = null;
          onChanged();
        } else {
          currentScanNode_ = null;
          currentScanNodeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ser.ScanNode current_scan_node = 17;</code>
       */
      public ser.JonSharedDataRotary.ScanNode.Builder getCurrentScanNodeBuilder() {
        
        onChanged();
        return getCurrentScanNodeFieldBuilder().getBuilder();
      }
      /**
       * <code>.ser.ScanNode current_scan_node = 17;</code>
       */
      public ser.JonSharedDataRotary.ScanNodeOrBuilder getCurrentScanNodeOrBuilder() {
        if (currentScanNodeBuilder_ != null) {
          return currentScanNodeBuilder_.getMessageOrBuilder();
        } else {
          return currentScanNode_ == null ?
              ser.JonSharedDataRotary.ScanNode.getDefaultInstance() : currentScanNode_;
        }
      }
      /**
       * <code>.ser.ScanNode current_scan_node = 17;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ser.JonSharedDataRotary.ScanNode, ser.JonSharedDataRotary.ScanNode.Builder, ser.JonSharedDataRotary.ScanNodeOrBuilder> 
          getCurrentScanNodeFieldBuilder() {
        if (currentScanNodeBuilder_ == null) {
          currentScanNodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ser.JonSharedDataRotary.ScanNode, ser.JonSharedDataRotary.ScanNode.Builder, ser.JonSharedDataRotary.ScanNodeOrBuilder>(
                  getCurrentScanNode(),
                  getParentForChildren(),
                  isClean());
          currentScanNode_ = null;
        }
        return currentScanNodeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ser.JonGuiDataRotary)
    }

    // @@protoc_insertion_point(class_scope:ser.JonGuiDataRotary)
    private static final ser.JonSharedDataRotary.JonGuiDataRotary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ser.JonSharedDataRotary.JonGuiDataRotary();
    }

    public static ser.JonSharedDataRotary.JonGuiDataRotary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JonGuiDataRotary>
        PARSER = new com.google.protobuf.AbstractParser<JonGuiDataRotary>() {
      @java.lang.Override
      public JonGuiDataRotary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JonGuiDataRotary(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JonGuiDataRotary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JonGuiDataRotary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ser.JonSharedDataRotary.JonGuiDataRotary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScanNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ser.ScanNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <code>int32 DayZoomTableValue = 2;</code>
     * @return The dayZoomTableValue.
     */
    int getDayZoomTableValue();

    /**
     * <code>int32 HeatZoomTableValue = 3;</code>
     * @return The heatZoomTableValue.
     */
    int getHeatZoomTableValue();

    /**
     * <code>double azimuth = 4;</code>
     * @return The azimuth.
     */
    double getAzimuth();

    /**
     * <code>double elevation = 5;</code>
     * @return The elevation.
     */
    double getElevation();

    /**
     * <code>double linger = 6;</code>
     * @return The linger.
     */
    double getLinger();

    /**
     * <code>double speed = 7;</code>
     * @return The speed.
     */
    double getSpeed();
  }
  /**
   * Protobuf type {@code ser.ScanNode}
   */
  public static final class ScanNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ser.ScanNode)
      ScanNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScanNode.newBuilder() to construct.
    private ScanNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScanNode() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScanNode();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScanNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              index_ = input.readInt32();
              break;
            }
            case 16: {

              dayZoomTableValue_ = input.readInt32();
              break;
            }
            case 24: {

              heatZoomTableValue_ = input.readInt32();
              break;
            }
            case 33: {

              azimuth_ = input.readDouble();
              break;
            }
            case 41: {

              elevation_ = input.readDouble();
              break;
            }
            case 49: {

              linger_ = input.readDouble();
              break;
            }
            case 57: {

              speed_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ser.JonSharedDataRotary.internal_static_ser_ScanNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ser.JonSharedDataRotary.internal_static_ser_ScanNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ser.JonSharedDataRotary.ScanNode.class, ser.JonSharedDataRotary.ScanNode.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }

    public static final int DAYZOOMTABLEVALUE_FIELD_NUMBER = 2;
    private int dayZoomTableValue_;
    /**
     * <code>int32 DayZoomTableValue = 2;</code>
     * @return The dayZoomTableValue.
     */
    @java.lang.Override
    public int getDayZoomTableValue() {
      return dayZoomTableValue_;
    }

    public static final int HEATZOOMTABLEVALUE_FIELD_NUMBER = 3;
    private int heatZoomTableValue_;
    /**
     * <code>int32 HeatZoomTableValue = 3;</code>
     * @return The heatZoomTableValue.
     */
    @java.lang.Override
    public int getHeatZoomTableValue() {
      return heatZoomTableValue_;
    }

    public static final int AZIMUTH_FIELD_NUMBER = 4;
    private double azimuth_;
    /**
     * <code>double azimuth = 4;</code>
     * @return The azimuth.
     */
    @java.lang.Override
    public double getAzimuth() {
      return azimuth_;
    }

    public static final int ELEVATION_FIELD_NUMBER = 5;
    private double elevation_;
    /**
     * <code>double elevation = 5;</code>
     * @return The elevation.
     */
    @java.lang.Override
    public double getElevation() {
      return elevation_;
    }

    public static final int LINGER_FIELD_NUMBER = 6;
    private double linger_;
    /**
     * <code>double linger = 6;</code>
     * @return The linger.
     */
    @java.lang.Override
    public double getLinger() {
      return linger_;
    }

    public static final int SPEED_FIELD_NUMBER = 7;
    private double speed_;
    /**
     * <code>double speed = 7;</code>
     * @return The speed.
     */
    @java.lang.Override
    public double getSpeed() {
      return speed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeInt32(1, index_);
      }
      if (dayZoomTableValue_ != 0) {
        output.writeInt32(2, dayZoomTableValue_);
      }
      if (heatZoomTableValue_ != 0) {
        output.writeInt32(3, heatZoomTableValue_);
      }
      if (azimuth_ != 0D) {
        output.writeDouble(4, azimuth_);
      }
      if (elevation_ != 0D) {
        output.writeDouble(5, elevation_);
      }
      if (linger_ != 0D) {
        output.writeDouble(6, linger_);
      }
      if (speed_ != 0D) {
        output.writeDouble(7, speed_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, index_);
      }
      if (dayZoomTableValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dayZoomTableValue_);
      }
      if (heatZoomTableValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, heatZoomTableValue_);
      }
      if (azimuth_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, azimuth_);
      }
      if (elevation_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, elevation_);
      }
      if (linger_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, linger_);
      }
      if (speed_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, speed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ser.JonSharedDataRotary.ScanNode)) {
        return super.equals(obj);
      }
      ser.JonSharedDataRotary.ScanNode other = (ser.JonSharedDataRotary.ScanNode) obj;

      if (getIndex()
          != other.getIndex()) return false;
      if (getDayZoomTableValue()
          != other.getDayZoomTableValue()) return false;
      if (getHeatZoomTableValue()
          != other.getHeatZoomTableValue()) return false;
      if (java.lang.Double.doubleToLongBits(getAzimuth())
          != java.lang.Double.doubleToLongBits(
              other.getAzimuth())) return false;
      if (java.lang.Double.doubleToLongBits(getElevation())
          != java.lang.Double.doubleToLongBits(
              other.getElevation())) return false;
      if (java.lang.Double.doubleToLongBits(getLinger())
          != java.lang.Double.doubleToLongBits(
              other.getLinger())) return false;
      if (java.lang.Double.doubleToLongBits(getSpeed())
          != java.lang.Double.doubleToLongBits(
              other.getSpeed())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + DAYZOOMTABLEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getDayZoomTableValue();
      hash = (37 * hash) + HEATZOOMTABLEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getHeatZoomTableValue();
      hash = (37 * hash) + AZIMUTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAzimuth()));
      hash = (37 * hash) + ELEVATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getElevation()));
      hash = (37 * hash) + LINGER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLinger()));
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSpeed()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ser.JonSharedDataRotary.ScanNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataRotary.ScanNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataRotary.ScanNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataRotary.ScanNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataRotary.ScanNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataRotary.ScanNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataRotary.ScanNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataRotary.ScanNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataRotary.ScanNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataRotary.ScanNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataRotary.ScanNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataRotary.ScanNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ser.JonSharedDataRotary.ScanNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ser.ScanNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ser.ScanNode)
        ser.JonSharedDataRotary.ScanNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ser.JonSharedDataRotary.internal_static_ser_ScanNode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ser.JonSharedDataRotary.internal_static_ser_ScanNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ser.JonSharedDataRotary.ScanNode.class, ser.JonSharedDataRotary.ScanNode.Builder.class);
      }

      // Construct using ser.JonSharedDataRotary.ScanNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        index_ = 0;

        dayZoomTableValue_ = 0;

        heatZoomTableValue_ = 0;

        azimuth_ = 0D;

        elevation_ = 0D;

        linger_ = 0D;

        speed_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ser.JonSharedDataRotary.internal_static_ser_ScanNode_descriptor;
      }

      @java.lang.Override
      public ser.JonSharedDataRotary.ScanNode getDefaultInstanceForType() {
        return ser.JonSharedDataRotary.ScanNode.getDefaultInstance();
      }

      @java.lang.Override
      public ser.JonSharedDataRotary.ScanNode build() {
        ser.JonSharedDataRotary.ScanNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ser.JonSharedDataRotary.ScanNode buildPartial() {
        ser.JonSharedDataRotary.ScanNode result = new ser.JonSharedDataRotary.ScanNode(this);
        result.index_ = index_;
        result.dayZoomTableValue_ = dayZoomTableValue_;
        result.heatZoomTableValue_ = heatZoomTableValue_;
        result.azimuth_ = azimuth_;
        result.elevation_ = elevation_;
        result.linger_ = linger_;
        result.speed_ = speed_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ser.JonSharedDataRotary.ScanNode) {
          return mergeFrom((ser.JonSharedDataRotary.ScanNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ser.JonSharedDataRotary.ScanNode other) {
        if (other == ser.JonSharedDataRotary.ScanNode.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.getDayZoomTableValue() != 0) {
          setDayZoomTableValue(other.getDayZoomTableValue());
        }
        if (other.getHeatZoomTableValue() != 0) {
          setHeatZoomTableValue(other.getHeatZoomTableValue());
        }
        if (other.getAzimuth() != 0D) {
          setAzimuth(other.getAzimuth());
        }
        if (other.getElevation() != 0D) {
          setElevation(other.getElevation());
        }
        if (other.getLinger() != 0D) {
          setLinger(other.getLinger());
        }
        if (other.getSpeed() != 0D) {
          setSpeed(other.getSpeed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ser.JonSharedDataRotary.ScanNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ser.JonSharedDataRotary.ScanNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int index_ ;
      /**
       * <code>int32 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return index_;
      }
      /**
       * <code>int32 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private int dayZoomTableValue_ ;
      /**
       * <code>int32 DayZoomTableValue = 2;</code>
       * @return The dayZoomTableValue.
       */
      @java.lang.Override
      public int getDayZoomTableValue() {
        return dayZoomTableValue_;
      }
      /**
       * <code>int32 DayZoomTableValue = 2;</code>
       * @param value The dayZoomTableValue to set.
       * @return This builder for chaining.
       */
      public Builder setDayZoomTableValue(int value) {
        
        dayZoomTableValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 DayZoomTableValue = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDayZoomTableValue() {
        
        dayZoomTableValue_ = 0;
        onChanged();
        return this;
      }

      private int heatZoomTableValue_ ;
      /**
       * <code>int32 HeatZoomTableValue = 3;</code>
       * @return The heatZoomTableValue.
       */
      @java.lang.Override
      public int getHeatZoomTableValue() {
        return heatZoomTableValue_;
      }
      /**
       * <code>int32 HeatZoomTableValue = 3;</code>
       * @param value The heatZoomTableValue to set.
       * @return This builder for chaining.
       */
      public Builder setHeatZoomTableValue(int value) {
        
        heatZoomTableValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 HeatZoomTableValue = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeatZoomTableValue() {
        
        heatZoomTableValue_ = 0;
        onChanged();
        return this;
      }

      private double azimuth_ ;
      /**
       * <code>double azimuth = 4;</code>
       * @return The azimuth.
       */
      @java.lang.Override
      public double getAzimuth() {
        return azimuth_;
      }
      /**
       * <code>double azimuth = 4;</code>
       * @param value The azimuth to set.
       * @return This builder for chaining.
       */
      public Builder setAzimuth(double value) {
        
        azimuth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double azimuth = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAzimuth() {
        
        azimuth_ = 0D;
        onChanged();
        return this;
      }

      private double elevation_ ;
      /**
       * <code>double elevation = 5;</code>
       * @return The elevation.
       */
      @java.lang.Override
      public double getElevation() {
        return elevation_;
      }
      /**
       * <code>double elevation = 5;</code>
       * @param value The elevation to set.
       * @return This builder for chaining.
       */
      public Builder setElevation(double value) {
        
        elevation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double elevation = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearElevation() {
        
        elevation_ = 0D;
        onChanged();
        return this;
      }

      private double linger_ ;
      /**
       * <code>double linger = 6;</code>
       * @return The linger.
       */
      @java.lang.Override
      public double getLinger() {
        return linger_;
      }
      /**
       * <code>double linger = 6;</code>
       * @param value The linger to set.
       * @return This builder for chaining.
       */
      public Builder setLinger(double value) {
        
        linger_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double linger = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLinger() {
        
        linger_ = 0D;
        onChanged();
        return this;
      }

      private double speed_ ;
      /**
       * <code>double speed = 7;</code>
       * @return The speed.
       */
      @java.lang.Override
      public double getSpeed() {
        return speed_;
      }
      /**
       * <code>double speed = 7;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(double value) {
        
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double speed = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        
        speed_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ser.ScanNode)
    }

    // @@protoc_insertion_point(class_scope:ser.ScanNode)
    private static final ser.JonSharedDataRotary.ScanNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ser.JonSharedDataRotary.ScanNode();
    }

    public static ser.JonSharedDataRotary.ScanNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScanNode>
        PARSER = new com.google.protobuf.AbstractParser<ScanNode>() {
      @java.lang.Override
      public ScanNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScanNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScanNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScanNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ser.JonSharedDataRotary.ScanNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ser_JonGuiDataRotary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ser_JonGuiDataRotary_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ser_ScanNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ser_ScanNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034jon_shared_data_rotary.proto\022\003ser\032\033jon" +
      "_shared_data_types.proto\"\303\003\n\020JonGuiDataR" +
      "otary\022\017\n\007azimuth\030\001 \001(\002\022\025\n\razimuth_speed\030" +
      "\002 \001(\002\022\021\n\televation\030\003 \001(\002\022\027\n\017elevation_sp" +
      "eed\030\004 \001(\002\022\030\n\020platform_azimuth\030\005 \001(\002\022\032\n\022p" +
      "latform_elevation\030\006 \001(\002\022\025\n\rplatform_bank" +
      "\030\007 \001(\002\022\021\n\tis_moving\030\010 \001(\010\022\'\n\004mode\030\t \001(\0162" +
      "\031.ser.JonGuiDataRotaryMode\022\023\n\013is_scannin" +
      "g\030\n \001(\010\022\032\n\022is_scanning_paused\030\013 \001(\010\022\035\n\025u" +
      "se_rotary_as_compass\030\014 \001(\010\022\023\n\013scan_targe" +
      "t\030\r \001(\005\022\027\n\017scan_target_max\030\016 \001(\005\022\023\n\013sun_" +
      "azimuth\030\017 \001(\002\022\025\n\rsun_elevation\030\020 \001(\002\022(\n\021" +
      "current_scan_node\030\021 \001(\0132\r.ser.ScanNode\"\223" +
      "\001\n\010ScanNode\022\r\n\005index\030\001 \001(\005\022\031\n\021DayZoomTab" +
      "leValue\030\002 \001(\005\022\032\n\022HeatZoomTableValue\030\003 \001(" +
      "\005\022\017\n\007azimuth\030\004 \001(\001\022\021\n\televation\030\005 \001(\001\022\016\n" +
      "\006linger\030\006 \001(\001\022\r\n\005speed\030\007 \001(\001BNZLgit-code" +
      "commit.eu-central-1.amazonaws.com/v1/rep" +
      "os/jettison/jonp/data/rotaryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ser.JonSharedDataTypes.getDescriptor(),
        });
    internal_static_ser_JonGuiDataRotary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ser_JonGuiDataRotary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ser_JonGuiDataRotary_descriptor,
        new java.lang.String[] { "Azimuth", "AzimuthSpeed", "Elevation", "ElevationSpeed", "PlatformAzimuth", "PlatformElevation", "PlatformBank", "IsMoving", "Mode", "IsScanning", "IsScanningPaused", "UseRotaryAsCompass", "ScanTarget", "ScanTargetMax", "SunAzimuth", "SunElevation", "CurrentScanNode", });
    internal_static_ser_ScanNode_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ser_ScanNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ser_ScanNode_descriptor,
        new java.lang.String[] { "Index", "DayZoomTableValue", "HeatZoomTableValue", "Azimuth", "Elevation", "Linger", "Speed", });
    ser.JonSharedDataTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
