// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jon_shared_data_system.proto

package ser;

public final class JonSharedDataSystem {
  private JonSharedDataSystem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JonGuiDataSystemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ser.JonGuiDataSystem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float cpu_temperature = 1;</code>
     * @return The cpuTemperature.
     */
    float getCpuTemperature();

    /**
     * <code>float gpu_temperature = 2;</code>
     * @return The gpuTemperature.
     */
    float getGpuTemperature();

    /**
     * <code>float gpu_load = 3;</code>
     * @return The gpuLoad.
     */
    float getGpuLoad();

    /**
     * <code>float cpu_load = 4;</code>
     * @return The cpuLoad.
     */
    float getCpuLoad();

    /**
     * <code>float power_consumption = 5;</code>
     * @return The powerConsumption.
     */
    float getPowerConsumption();

    /**
     * <code>.ser.JonGuiDataSystemLocalizations loc = 6;</code>
     * @return The enum numeric value on the wire for loc.
     */
    int getLocValue();
    /**
     * <code>.ser.JonGuiDataSystemLocalizations loc = 6;</code>
     * @return The loc.
     */
    ser.JonSharedDataTypes.JonGuiDataSystemLocalizations getLoc();

    /**
     * <code>int32 cur_video_rec_dir_year = 7;</code>
     * @return The curVideoRecDirYear.
     */
    int getCurVideoRecDirYear();

    /**
     * <code>int32 cur_video_rec_dir_month = 8;</code>
     * @return The curVideoRecDirMonth.
     */
    int getCurVideoRecDirMonth();

    /**
     * <code>int32 cur_video_rec_dir_day = 9;</code>
     * @return The curVideoRecDirDay.
     */
    int getCurVideoRecDirDay();

    /**
     * <code>int32 cur_video_rec_dir_hour = 10;</code>
     * @return The curVideoRecDirHour.
     */
    int getCurVideoRecDirHour();

    /**
     * <code>int32 cur_video_rec_dir_minute = 11;</code>
     * @return The curVideoRecDirMinute.
     */
    int getCurVideoRecDirMinute();

    /**
     * <code>int32 cur_video_rec_dir_second = 12;</code>
     * @return The curVideoRecDirSecond.
     */
    int getCurVideoRecDirSecond();

    /**
     * <code>bool rec_enabled = 13;</code>
     * @return The recEnabled.
     */
    boolean getRecEnabled();

    /**
     * <code>bool important_rec_enabled = 14;</code>
     * @return The importantRecEnabled.
     */
    boolean getImportantRecEnabled();

    /**
     * <code>bool low_disk_space = 15;</code>
     * @return The lowDiskSpace.
     */
    boolean getLowDiskSpace();

    /**
     * <code>bool no_disk_space = 16;</code>
     * @return The noDiskSpace.
     */
    boolean getNoDiskSpace();

    /**
     * <code>int32 disk_space = 17;</code>
     * @return The diskSpace.
     */
    int getDiskSpace();

    /**
     * <code>bool tracking = 18;</code>
     * @return The tracking.
     */
    boolean getTracking();

    /**
     * <code>bool vampire_mode = 19;</code>
     * @return The vampireMode.
     */
    boolean getVampireMode();

    /**
     * <code>bool stabilization_mode = 20;</code>
     * @return The stabilizationMode.
     */
    boolean getStabilizationMode();

    /**
     * <code>bool geodesic_mode = 21;</code>
     * @return The geodesicMode.
     */
    boolean getGeodesicMode();

    /**
     * <code>bool cv_dumping = 22;</code>
     * @return The cvDumping.
     */
    boolean getCvDumping();
  }
  /**
   * Protobuf type {@code ser.JonGuiDataSystem}
   */
  public static final class JonGuiDataSystem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ser.JonGuiDataSystem)
      JonGuiDataSystemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JonGuiDataSystem.newBuilder() to construct.
    private JonGuiDataSystem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JonGuiDataSystem() {
      loc_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JonGuiDataSystem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JonGuiDataSystem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              cpuTemperature_ = input.readFloat();
              break;
            }
            case 21: {

              gpuTemperature_ = input.readFloat();
              break;
            }
            case 29: {

              gpuLoad_ = input.readFloat();
              break;
            }
            case 37: {

              cpuLoad_ = input.readFloat();
              break;
            }
            case 45: {

              powerConsumption_ = input.readFloat();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              loc_ = rawValue;
              break;
            }
            case 56: {

              curVideoRecDirYear_ = input.readInt32();
              break;
            }
            case 64: {

              curVideoRecDirMonth_ = input.readInt32();
              break;
            }
            case 72: {

              curVideoRecDirDay_ = input.readInt32();
              break;
            }
            case 80: {

              curVideoRecDirHour_ = input.readInt32();
              break;
            }
            case 88: {

              curVideoRecDirMinute_ = input.readInt32();
              break;
            }
            case 96: {

              curVideoRecDirSecond_ = input.readInt32();
              break;
            }
            case 104: {

              recEnabled_ = input.readBool();
              break;
            }
            case 112: {

              importantRecEnabled_ = input.readBool();
              break;
            }
            case 120: {

              lowDiskSpace_ = input.readBool();
              break;
            }
            case 128: {

              noDiskSpace_ = input.readBool();
              break;
            }
            case 136: {

              diskSpace_ = input.readInt32();
              break;
            }
            case 144: {

              tracking_ = input.readBool();
              break;
            }
            case 152: {

              vampireMode_ = input.readBool();
              break;
            }
            case 160: {

              stabilizationMode_ = input.readBool();
              break;
            }
            case 168: {

              geodesicMode_ = input.readBool();
              break;
            }
            case 176: {

              cvDumping_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ser.JonSharedDataSystem.internal_static_ser_JonGuiDataSystem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ser.JonSharedDataSystem.internal_static_ser_JonGuiDataSystem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ser.JonSharedDataSystem.JonGuiDataSystem.class, ser.JonSharedDataSystem.JonGuiDataSystem.Builder.class);
    }

    public static final int CPU_TEMPERATURE_FIELD_NUMBER = 1;
    private float cpuTemperature_;
    /**
     * <code>float cpu_temperature = 1;</code>
     * @return The cpuTemperature.
     */
    @java.lang.Override
    public float getCpuTemperature() {
      return cpuTemperature_;
    }

    public static final int GPU_TEMPERATURE_FIELD_NUMBER = 2;
    private float gpuTemperature_;
    /**
     * <code>float gpu_temperature = 2;</code>
     * @return The gpuTemperature.
     */
    @java.lang.Override
    public float getGpuTemperature() {
      return gpuTemperature_;
    }

    public static final int GPU_LOAD_FIELD_NUMBER = 3;
    private float gpuLoad_;
    /**
     * <code>float gpu_load = 3;</code>
     * @return The gpuLoad.
     */
    @java.lang.Override
    public float getGpuLoad() {
      return gpuLoad_;
    }

    public static final int CPU_LOAD_FIELD_NUMBER = 4;
    private float cpuLoad_;
    /**
     * <code>float cpu_load = 4;</code>
     * @return The cpuLoad.
     */
    @java.lang.Override
    public float getCpuLoad() {
      return cpuLoad_;
    }

    public static final int POWER_CONSUMPTION_FIELD_NUMBER = 5;
    private float powerConsumption_;
    /**
     * <code>float power_consumption = 5;</code>
     * @return The powerConsumption.
     */
    @java.lang.Override
    public float getPowerConsumption() {
      return powerConsumption_;
    }

    public static final int LOC_FIELD_NUMBER = 6;
    private int loc_;
    /**
     * <code>.ser.JonGuiDataSystemLocalizations loc = 6;</code>
     * @return The enum numeric value on the wire for loc.
     */
    @java.lang.Override public int getLocValue() {
      return loc_;
    }
    /**
     * <code>.ser.JonGuiDataSystemLocalizations loc = 6;</code>
     * @return The loc.
     */
    @java.lang.Override public ser.JonSharedDataTypes.JonGuiDataSystemLocalizations getLoc() {
      @SuppressWarnings("deprecation")
      ser.JonSharedDataTypes.JonGuiDataSystemLocalizations result = ser.JonSharedDataTypes.JonGuiDataSystemLocalizations.valueOf(loc_);
      return result == null ? ser.JonSharedDataTypes.JonGuiDataSystemLocalizations.UNRECOGNIZED : result;
    }

    public static final int CUR_VIDEO_REC_DIR_YEAR_FIELD_NUMBER = 7;
    private int curVideoRecDirYear_;
    /**
     * <code>int32 cur_video_rec_dir_year = 7;</code>
     * @return The curVideoRecDirYear.
     */
    @java.lang.Override
    public int getCurVideoRecDirYear() {
      return curVideoRecDirYear_;
    }

    public static final int CUR_VIDEO_REC_DIR_MONTH_FIELD_NUMBER = 8;
    private int curVideoRecDirMonth_;
    /**
     * <code>int32 cur_video_rec_dir_month = 8;</code>
     * @return The curVideoRecDirMonth.
     */
    @java.lang.Override
    public int getCurVideoRecDirMonth() {
      return curVideoRecDirMonth_;
    }

    public static final int CUR_VIDEO_REC_DIR_DAY_FIELD_NUMBER = 9;
    private int curVideoRecDirDay_;
    /**
     * <code>int32 cur_video_rec_dir_day = 9;</code>
     * @return The curVideoRecDirDay.
     */
    @java.lang.Override
    public int getCurVideoRecDirDay() {
      return curVideoRecDirDay_;
    }

    public static final int CUR_VIDEO_REC_DIR_HOUR_FIELD_NUMBER = 10;
    private int curVideoRecDirHour_;
    /**
     * <code>int32 cur_video_rec_dir_hour = 10;</code>
     * @return The curVideoRecDirHour.
     */
    @java.lang.Override
    public int getCurVideoRecDirHour() {
      return curVideoRecDirHour_;
    }

    public static final int CUR_VIDEO_REC_DIR_MINUTE_FIELD_NUMBER = 11;
    private int curVideoRecDirMinute_;
    /**
     * <code>int32 cur_video_rec_dir_minute = 11;</code>
     * @return The curVideoRecDirMinute.
     */
    @java.lang.Override
    public int getCurVideoRecDirMinute() {
      return curVideoRecDirMinute_;
    }

    public static final int CUR_VIDEO_REC_DIR_SECOND_FIELD_NUMBER = 12;
    private int curVideoRecDirSecond_;
    /**
     * <code>int32 cur_video_rec_dir_second = 12;</code>
     * @return The curVideoRecDirSecond.
     */
    @java.lang.Override
    public int getCurVideoRecDirSecond() {
      return curVideoRecDirSecond_;
    }

    public static final int REC_ENABLED_FIELD_NUMBER = 13;
    private boolean recEnabled_;
    /**
     * <code>bool rec_enabled = 13;</code>
     * @return The recEnabled.
     */
    @java.lang.Override
    public boolean getRecEnabled() {
      return recEnabled_;
    }

    public static final int IMPORTANT_REC_ENABLED_FIELD_NUMBER = 14;
    private boolean importantRecEnabled_;
    /**
     * <code>bool important_rec_enabled = 14;</code>
     * @return The importantRecEnabled.
     */
    @java.lang.Override
    public boolean getImportantRecEnabled() {
      return importantRecEnabled_;
    }

    public static final int LOW_DISK_SPACE_FIELD_NUMBER = 15;
    private boolean lowDiskSpace_;
    /**
     * <code>bool low_disk_space = 15;</code>
     * @return The lowDiskSpace.
     */
    @java.lang.Override
    public boolean getLowDiskSpace() {
      return lowDiskSpace_;
    }

    public static final int NO_DISK_SPACE_FIELD_NUMBER = 16;
    private boolean noDiskSpace_;
    /**
     * <code>bool no_disk_space = 16;</code>
     * @return The noDiskSpace.
     */
    @java.lang.Override
    public boolean getNoDiskSpace() {
      return noDiskSpace_;
    }

    public static final int DISK_SPACE_FIELD_NUMBER = 17;
    private int diskSpace_;
    /**
     * <code>int32 disk_space = 17;</code>
     * @return The diskSpace.
     */
    @java.lang.Override
    public int getDiskSpace() {
      return diskSpace_;
    }

    public static final int TRACKING_FIELD_NUMBER = 18;
    private boolean tracking_;
    /**
     * <code>bool tracking = 18;</code>
     * @return The tracking.
     */
    @java.lang.Override
    public boolean getTracking() {
      return tracking_;
    }

    public static final int VAMPIRE_MODE_FIELD_NUMBER = 19;
    private boolean vampireMode_;
    /**
     * <code>bool vampire_mode = 19;</code>
     * @return The vampireMode.
     */
    @java.lang.Override
    public boolean getVampireMode() {
      return vampireMode_;
    }

    public static final int STABILIZATION_MODE_FIELD_NUMBER = 20;
    private boolean stabilizationMode_;
    /**
     * <code>bool stabilization_mode = 20;</code>
     * @return The stabilizationMode.
     */
    @java.lang.Override
    public boolean getStabilizationMode() {
      return stabilizationMode_;
    }

    public static final int GEODESIC_MODE_FIELD_NUMBER = 21;
    private boolean geodesicMode_;
    /**
     * <code>bool geodesic_mode = 21;</code>
     * @return The geodesicMode.
     */
    @java.lang.Override
    public boolean getGeodesicMode() {
      return geodesicMode_;
    }

    public static final int CV_DUMPING_FIELD_NUMBER = 22;
    private boolean cvDumping_;
    /**
     * <code>bool cv_dumping = 22;</code>
     * @return The cvDumping.
     */
    @java.lang.Override
    public boolean getCvDumping() {
      return cvDumping_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cpuTemperature_ != 0F) {
        output.writeFloat(1, cpuTemperature_);
      }
      if (gpuTemperature_ != 0F) {
        output.writeFloat(2, gpuTemperature_);
      }
      if (gpuLoad_ != 0F) {
        output.writeFloat(3, gpuLoad_);
      }
      if (cpuLoad_ != 0F) {
        output.writeFloat(4, cpuLoad_);
      }
      if (powerConsumption_ != 0F) {
        output.writeFloat(5, powerConsumption_);
      }
      if (loc_ != ser.JonSharedDataTypes.JonGuiDataSystemLocalizations.JON_GUI_DATA_SYSTEM_LOCALIZATION_UNSPECIFIED.getNumber()) {
        output.writeEnum(6, loc_);
      }
      if (curVideoRecDirYear_ != 0) {
        output.writeInt32(7, curVideoRecDirYear_);
      }
      if (curVideoRecDirMonth_ != 0) {
        output.writeInt32(8, curVideoRecDirMonth_);
      }
      if (curVideoRecDirDay_ != 0) {
        output.writeInt32(9, curVideoRecDirDay_);
      }
      if (curVideoRecDirHour_ != 0) {
        output.writeInt32(10, curVideoRecDirHour_);
      }
      if (curVideoRecDirMinute_ != 0) {
        output.writeInt32(11, curVideoRecDirMinute_);
      }
      if (curVideoRecDirSecond_ != 0) {
        output.writeInt32(12, curVideoRecDirSecond_);
      }
      if (recEnabled_ != false) {
        output.writeBool(13, recEnabled_);
      }
      if (importantRecEnabled_ != false) {
        output.writeBool(14, importantRecEnabled_);
      }
      if (lowDiskSpace_ != false) {
        output.writeBool(15, lowDiskSpace_);
      }
      if (noDiskSpace_ != false) {
        output.writeBool(16, noDiskSpace_);
      }
      if (diskSpace_ != 0) {
        output.writeInt32(17, diskSpace_);
      }
      if (tracking_ != false) {
        output.writeBool(18, tracking_);
      }
      if (vampireMode_ != false) {
        output.writeBool(19, vampireMode_);
      }
      if (stabilizationMode_ != false) {
        output.writeBool(20, stabilizationMode_);
      }
      if (geodesicMode_ != false) {
        output.writeBool(21, geodesicMode_);
      }
      if (cvDumping_ != false) {
        output.writeBool(22, cvDumping_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cpuTemperature_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, cpuTemperature_);
      }
      if (gpuTemperature_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, gpuTemperature_);
      }
      if (gpuLoad_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, gpuLoad_);
      }
      if (cpuLoad_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, cpuLoad_);
      }
      if (powerConsumption_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, powerConsumption_);
      }
      if (loc_ != ser.JonSharedDataTypes.JonGuiDataSystemLocalizations.JON_GUI_DATA_SYSTEM_LOCALIZATION_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, loc_);
      }
      if (curVideoRecDirYear_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, curVideoRecDirYear_);
      }
      if (curVideoRecDirMonth_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, curVideoRecDirMonth_);
      }
      if (curVideoRecDirDay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, curVideoRecDirDay_);
      }
      if (curVideoRecDirHour_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, curVideoRecDirHour_);
      }
      if (curVideoRecDirMinute_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, curVideoRecDirMinute_);
      }
      if (curVideoRecDirSecond_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, curVideoRecDirSecond_);
      }
      if (recEnabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, recEnabled_);
      }
      if (importantRecEnabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, importantRecEnabled_);
      }
      if (lowDiskSpace_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, lowDiskSpace_);
      }
      if (noDiskSpace_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(16, noDiskSpace_);
      }
      if (diskSpace_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, diskSpace_);
      }
      if (tracking_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(18, tracking_);
      }
      if (vampireMode_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(19, vampireMode_);
      }
      if (stabilizationMode_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(20, stabilizationMode_);
      }
      if (geodesicMode_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(21, geodesicMode_);
      }
      if (cvDumping_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(22, cvDumping_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ser.JonSharedDataSystem.JonGuiDataSystem)) {
        return super.equals(obj);
      }
      ser.JonSharedDataSystem.JonGuiDataSystem other = (ser.JonSharedDataSystem.JonGuiDataSystem) obj;

      if (java.lang.Float.floatToIntBits(getCpuTemperature())
          != java.lang.Float.floatToIntBits(
              other.getCpuTemperature())) return false;
      if (java.lang.Float.floatToIntBits(getGpuTemperature())
          != java.lang.Float.floatToIntBits(
              other.getGpuTemperature())) return false;
      if (java.lang.Float.floatToIntBits(getGpuLoad())
          != java.lang.Float.floatToIntBits(
              other.getGpuLoad())) return false;
      if (java.lang.Float.floatToIntBits(getCpuLoad())
          != java.lang.Float.floatToIntBits(
              other.getCpuLoad())) return false;
      if (java.lang.Float.floatToIntBits(getPowerConsumption())
          != java.lang.Float.floatToIntBits(
              other.getPowerConsumption())) return false;
      if (loc_ != other.loc_) return false;
      if (getCurVideoRecDirYear()
          != other.getCurVideoRecDirYear()) return false;
      if (getCurVideoRecDirMonth()
          != other.getCurVideoRecDirMonth()) return false;
      if (getCurVideoRecDirDay()
          != other.getCurVideoRecDirDay()) return false;
      if (getCurVideoRecDirHour()
          != other.getCurVideoRecDirHour()) return false;
      if (getCurVideoRecDirMinute()
          != other.getCurVideoRecDirMinute()) return false;
      if (getCurVideoRecDirSecond()
          != other.getCurVideoRecDirSecond()) return false;
      if (getRecEnabled()
          != other.getRecEnabled()) return false;
      if (getImportantRecEnabled()
          != other.getImportantRecEnabled()) return false;
      if (getLowDiskSpace()
          != other.getLowDiskSpace()) return false;
      if (getNoDiskSpace()
          != other.getNoDiskSpace()) return false;
      if (getDiskSpace()
          != other.getDiskSpace()) return false;
      if (getTracking()
          != other.getTracking()) return false;
      if (getVampireMode()
          != other.getVampireMode()) return false;
      if (getStabilizationMode()
          != other.getStabilizationMode()) return false;
      if (getGeodesicMode()
          != other.getGeodesicMode()) return false;
      if (getCvDumping()
          != other.getCvDumping()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CPU_TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCpuTemperature());
      hash = (37 * hash) + GPU_TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getGpuTemperature());
      hash = (37 * hash) + GPU_LOAD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getGpuLoad());
      hash = (37 * hash) + CPU_LOAD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCpuLoad());
      hash = (37 * hash) + POWER_CONSUMPTION_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPowerConsumption());
      hash = (37 * hash) + LOC_FIELD_NUMBER;
      hash = (53 * hash) + loc_;
      hash = (37 * hash) + CUR_VIDEO_REC_DIR_YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getCurVideoRecDirYear();
      hash = (37 * hash) + CUR_VIDEO_REC_DIR_MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getCurVideoRecDirMonth();
      hash = (37 * hash) + CUR_VIDEO_REC_DIR_DAY_FIELD_NUMBER;
      hash = (53 * hash) + getCurVideoRecDirDay();
      hash = (37 * hash) + CUR_VIDEO_REC_DIR_HOUR_FIELD_NUMBER;
      hash = (53 * hash) + getCurVideoRecDirHour();
      hash = (37 * hash) + CUR_VIDEO_REC_DIR_MINUTE_FIELD_NUMBER;
      hash = (53 * hash) + getCurVideoRecDirMinute();
      hash = (37 * hash) + CUR_VIDEO_REC_DIR_SECOND_FIELD_NUMBER;
      hash = (53 * hash) + getCurVideoRecDirSecond();
      hash = (37 * hash) + REC_ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRecEnabled());
      hash = (37 * hash) + IMPORTANT_REC_ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getImportantRecEnabled());
      hash = (37 * hash) + LOW_DISK_SPACE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLowDiskSpace());
      hash = (37 * hash) + NO_DISK_SPACE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNoDiskSpace());
      hash = (37 * hash) + DISK_SPACE_FIELD_NUMBER;
      hash = (53 * hash) + getDiskSpace();
      hash = (37 * hash) + TRACKING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTracking());
      hash = (37 * hash) + VAMPIRE_MODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVampireMode());
      hash = (37 * hash) + STABILIZATION_MODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStabilizationMode());
      hash = (37 * hash) + GEODESIC_MODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getGeodesicMode());
      hash = (37 * hash) + CV_DUMPING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCvDumping());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ser.JonSharedDataSystem.JonGuiDataSystem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataSystem.JonGuiDataSystem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataSystem.JonGuiDataSystem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataSystem.JonGuiDataSystem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataSystem.JonGuiDataSystem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataSystem.JonGuiDataSystem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataSystem.JonGuiDataSystem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataSystem.JonGuiDataSystem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataSystem.JonGuiDataSystem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataSystem.JonGuiDataSystem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataSystem.JonGuiDataSystem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataSystem.JonGuiDataSystem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ser.JonSharedDataSystem.JonGuiDataSystem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ser.JonGuiDataSystem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ser.JonGuiDataSystem)
        ser.JonSharedDataSystem.JonGuiDataSystemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ser.JonSharedDataSystem.internal_static_ser_JonGuiDataSystem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ser.JonSharedDataSystem.internal_static_ser_JonGuiDataSystem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ser.JonSharedDataSystem.JonGuiDataSystem.class, ser.JonSharedDataSystem.JonGuiDataSystem.Builder.class);
      }

      // Construct using ser.JonSharedDataSystem.JonGuiDataSystem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cpuTemperature_ = 0F;

        gpuTemperature_ = 0F;

        gpuLoad_ = 0F;

        cpuLoad_ = 0F;

        powerConsumption_ = 0F;

        loc_ = 0;

        curVideoRecDirYear_ = 0;

        curVideoRecDirMonth_ = 0;

        curVideoRecDirDay_ = 0;

        curVideoRecDirHour_ = 0;

        curVideoRecDirMinute_ = 0;

        curVideoRecDirSecond_ = 0;

        recEnabled_ = false;

        importantRecEnabled_ = false;

        lowDiskSpace_ = false;

        noDiskSpace_ = false;

        diskSpace_ = 0;

        tracking_ = false;

        vampireMode_ = false;

        stabilizationMode_ = false;

        geodesicMode_ = false;

        cvDumping_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ser.JonSharedDataSystem.internal_static_ser_JonGuiDataSystem_descriptor;
      }

      @java.lang.Override
      public ser.JonSharedDataSystem.JonGuiDataSystem getDefaultInstanceForType() {
        return ser.JonSharedDataSystem.JonGuiDataSystem.getDefaultInstance();
      }

      @java.lang.Override
      public ser.JonSharedDataSystem.JonGuiDataSystem build() {
        ser.JonSharedDataSystem.JonGuiDataSystem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ser.JonSharedDataSystem.JonGuiDataSystem buildPartial() {
        ser.JonSharedDataSystem.JonGuiDataSystem result = new ser.JonSharedDataSystem.JonGuiDataSystem(this);
        result.cpuTemperature_ = cpuTemperature_;
        result.gpuTemperature_ = gpuTemperature_;
        result.gpuLoad_ = gpuLoad_;
        result.cpuLoad_ = cpuLoad_;
        result.powerConsumption_ = powerConsumption_;
        result.loc_ = loc_;
        result.curVideoRecDirYear_ = curVideoRecDirYear_;
        result.curVideoRecDirMonth_ = curVideoRecDirMonth_;
        result.curVideoRecDirDay_ = curVideoRecDirDay_;
        result.curVideoRecDirHour_ = curVideoRecDirHour_;
        result.curVideoRecDirMinute_ = curVideoRecDirMinute_;
        result.curVideoRecDirSecond_ = curVideoRecDirSecond_;
        result.recEnabled_ = recEnabled_;
        result.importantRecEnabled_ = importantRecEnabled_;
        result.lowDiskSpace_ = lowDiskSpace_;
        result.noDiskSpace_ = noDiskSpace_;
        result.diskSpace_ = diskSpace_;
        result.tracking_ = tracking_;
        result.vampireMode_ = vampireMode_;
        result.stabilizationMode_ = stabilizationMode_;
        result.geodesicMode_ = geodesicMode_;
        result.cvDumping_ = cvDumping_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ser.JonSharedDataSystem.JonGuiDataSystem) {
          return mergeFrom((ser.JonSharedDataSystem.JonGuiDataSystem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ser.JonSharedDataSystem.JonGuiDataSystem other) {
        if (other == ser.JonSharedDataSystem.JonGuiDataSystem.getDefaultInstance()) return this;
        if (other.getCpuTemperature() != 0F) {
          setCpuTemperature(other.getCpuTemperature());
        }
        if (other.getGpuTemperature() != 0F) {
          setGpuTemperature(other.getGpuTemperature());
        }
        if (other.getGpuLoad() != 0F) {
          setGpuLoad(other.getGpuLoad());
        }
        if (other.getCpuLoad() != 0F) {
          setCpuLoad(other.getCpuLoad());
        }
        if (other.getPowerConsumption() != 0F) {
          setPowerConsumption(other.getPowerConsumption());
        }
        if (other.loc_ != 0) {
          setLocValue(other.getLocValue());
        }
        if (other.getCurVideoRecDirYear() != 0) {
          setCurVideoRecDirYear(other.getCurVideoRecDirYear());
        }
        if (other.getCurVideoRecDirMonth() != 0) {
          setCurVideoRecDirMonth(other.getCurVideoRecDirMonth());
        }
        if (other.getCurVideoRecDirDay() != 0) {
          setCurVideoRecDirDay(other.getCurVideoRecDirDay());
        }
        if (other.getCurVideoRecDirHour() != 0) {
          setCurVideoRecDirHour(other.getCurVideoRecDirHour());
        }
        if (other.getCurVideoRecDirMinute() != 0) {
          setCurVideoRecDirMinute(other.getCurVideoRecDirMinute());
        }
        if (other.getCurVideoRecDirSecond() != 0) {
          setCurVideoRecDirSecond(other.getCurVideoRecDirSecond());
        }
        if (other.getRecEnabled() != false) {
          setRecEnabled(other.getRecEnabled());
        }
        if (other.getImportantRecEnabled() != false) {
          setImportantRecEnabled(other.getImportantRecEnabled());
        }
        if (other.getLowDiskSpace() != false) {
          setLowDiskSpace(other.getLowDiskSpace());
        }
        if (other.getNoDiskSpace() != false) {
          setNoDiskSpace(other.getNoDiskSpace());
        }
        if (other.getDiskSpace() != 0) {
          setDiskSpace(other.getDiskSpace());
        }
        if (other.getTracking() != false) {
          setTracking(other.getTracking());
        }
        if (other.getVampireMode() != false) {
          setVampireMode(other.getVampireMode());
        }
        if (other.getStabilizationMode() != false) {
          setStabilizationMode(other.getStabilizationMode());
        }
        if (other.getGeodesicMode() != false) {
          setGeodesicMode(other.getGeodesicMode());
        }
        if (other.getCvDumping() != false) {
          setCvDumping(other.getCvDumping());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ser.JonSharedDataSystem.JonGuiDataSystem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ser.JonSharedDataSystem.JonGuiDataSystem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float cpuTemperature_ ;
      /**
       * <code>float cpu_temperature = 1;</code>
       * @return The cpuTemperature.
       */
      @java.lang.Override
      public float getCpuTemperature() {
        return cpuTemperature_;
      }
      /**
       * <code>float cpu_temperature = 1;</code>
       * @param value The cpuTemperature to set.
       * @return This builder for chaining.
       */
      public Builder setCpuTemperature(float value) {
        
        cpuTemperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float cpu_temperature = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpuTemperature() {
        
        cpuTemperature_ = 0F;
        onChanged();
        return this;
      }

      private float gpuTemperature_ ;
      /**
       * <code>float gpu_temperature = 2;</code>
       * @return The gpuTemperature.
       */
      @java.lang.Override
      public float getGpuTemperature() {
        return gpuTemperature_;
      }
      /**
       * <code>float gpu_temperature = 2;</code>
       * @param value The gpuTemperature to set.
       * @return This builder for chaining.
       */
      public Builder setGpuTemperature(float value) {
        
        gpuTemperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float gpu_temperature = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGpuTemperature() {
        
        gpuTemperature_ = 0F;
        onChanged();
        return this;
      }

      private float gpuLoad_ ;
      /**
       * <code>float gpu_load = 3;</code>
       * @return The gpuLoad.
       */
      @java.lang.Override
      public float getGpuLoad() {
        return gpuLoad_;
      }
      /**
       * <code>float gpu_load = 3;</code>
       * @param value The gpuLoad to set.
       * @return This builder for chaining.
       */
      public Builder setGpuLoad(float value) {
        
        gpuLoad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float gpu_load = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGpuLoad() {
        
        gpuLoad_ = 0F;
        onChanged();
        return this;
      }

      private float cpuLoad_ ;
      /**
       * <code>float cpu_load = 4;</code>
       * @return The cpuLoad.
       */
      @java.lang.Override
      public float getCpuLoad() {
        return cpuLoad_;
      }
      /**
       * <code>float cpu_load = 4;</code>
       * @param value The cpuLoad to set.
       * @return This builder for chaining.
       */
      public Builder setCpuLoad(float value) {
        
        cpuLoad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float cpu_load = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpuLoad() {
        
        cpuLoad_ = 0F;
        onChanged();
        return this;
      }

      private float powerConsumption_ ;
      /**
       * <code>float power_consumption = 5;</code>
       * @return The powerConsumption.
       */
      @java.lang.Override
      public float getPowerConsumption() {
        return powerConsumption_;
      }
      /**
       * <code>float power_consumption = 5;</code>
       * @param value The powerConsumption to set.
       * @return This builder for chaining.
       */
      public Builder setPowerConsumption(float value) {
        
        powerConsumption_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float power_consumption = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPowerConsumption() {
        
        powerConsumption_ = 0F;
        onChanged();
        return this;
      }

      private int loc_ = 0;
      /**
       * <code>.ser.JonGuiDataSystemLocalizations loc = 6;</code>
       * @return The enum numeric value on the wire for loc.
       */
      @java.lang.Override public int getLocValue() {
        return loc_;
      }
      /**
       * <code>.ser.JonGuiDataSystemLocalizations loc = 6;</code>
       * @param value The enum numeric value on the wire for loc to set.
       * @return This builder for chaining.
       */
      public Builder setLocValue(int value) {
        
        loc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ser.JonGuiDataSystemLocalizations loc = 6;</code>
       * @return The loc.
       */
      @java.lang.Override
      public ser.JonSharedDataTypes.JonGuiDataSystemLocalizations getLoc() {
        @SuppressWarnings("deprecation")
        ser.JonSharedDataTypes.JonGuiDataSystemLocalizations result = ser.JonSharedDataTypes.JonGuiDataSystemLocalizations.valueOf(loc_);
        return result == null ? ser.JonSharedDataTypes.JonGuiDataSystemLocalizations.UNRECOGNIZED : result;
      }
      /**
       * <code>.ser.JonGuiDataSystemLocalizations loc = 6;</code>
       * @param value The loc to set.
       * @return This builder for chaining.
       */
      public Builder setLoc(ser.JonSharedDataTypes.JonGuiDataSystemLocalizations value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        loc_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ser.JonGuiDataSystemLocalizations loc = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoc() {
        
        loc_ = 0;
        onChanged();
        return this;
      }

      private int curVideoRecDirYear_ ;
      /**
       * <code>int32 cur_video_rec_dir_year = 7;</code>
       * @return The curVideoRecDirYear.
       */
      @java.lang.Override
      public int getCurVideoRecDirYear() {
        return curVideoRecDirYear_;
      }
      /**
       * <code>int32 cur_video_rec_dir_year = 7;</code>
       * @param value The curVideoRecDirYear to set.
       * @return This builder for chaining.
       */
      public Builder setCurVideoRecDirYear(int value) {
        
        curVideoRecDirYear_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cur_video_rec_dir_year = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurVideoRecDirYear() {
        
        curVideoRecDirYear_ = 0;
        onChanged();
        return this;
      }

      private int curVideoRecDirMonth_ ;
      /**
       * <code>int32 cur_video_rec_dir_month = 8;</code>
       * @return The curVideoRecDirMonth.
       */
      @java.lang.Override
      public int getCurVideoRecDirMonth() {
        return curVideoRecDirMonth_;
      }
      /**
       * <code>int32 cur_video_rec_dir_month = 8;</code>
       * @param value The curVideoRecDirMonth to set.
       * @return This builder for chaining.
       */
      public Builder setCurVideoRecDirMonth(int value) {
        
        curVideoRecDirMonth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cur_video_rec_dir_month = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurVideoRecDirMonth() {
        
        curVideoRecDirMonth_ = 0;
        onChanged();
        return this;
      }

      private int curVideoRecDirDay_ ;
      /**
       * <code>int32 cur_video_rec_dir_day = 9;</code>
       * @return The curVideoRecDirDay.
       */
      @java.lang.Override
      public int getCurVideoRecDirDay() {
        return curVideoRecDirDay_;
      }
      /**
       * <code>int32 cur_video_rec_dir_day = 9;</code>
       * @param value The curVideoRecDirDay to set.
       * @return This builder for chaining.
       */
      public Builder setCurVideoRecDirDay(int value) {
        
        curVideoRecDirDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cur_video_rec_dir_day = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurVideoRecDirDay() {
        
        curVideoRecDirDay_ = 0;
        onChanged();
        return this;
      }

      private int curVideoRecDirHour_ ;
      /**
       * <code>int32 cur_video_rec_dir_hour = 10;</code>
       * @return The curVideoRecDirHour.
       */
      @java.lang.Override
      public int getCurVideoRecDirHour() {
        return curVideoRecDirHour_;
      }
      /**
       * <code>int32 cur_video_rec_dir_hour = 10;</code>
       * @param value The curVideoRecDirHour to set.
       * @return This builder for chaining.
       */
      public Builder setCurVideoRecDirHour(int value) {
        
        curVideoRecDirHour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cur_video_rec_dir_hour = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurVideoRecDirHour() {
        
        curVideoRecDirHour_ = 0;
        onChanged();
        return this;
      }

      private int curVideoRecDirMinute_ ;
      /**
       * <code>int32 cur_video_rec_dir_minute = 11;</code>
       * @return The curVideoRecDirMinute.
       */
      @java.lang.Override
      public int getCurVideoRecDirMinute() {
        return curVideoRecDirMinute_;
      }
      /**
       * <code>int32 cur_video_rec_dir_minute = 11;</code>
       * @param value The curVideoRecDirMinute to set.
       * @return This builder for chaining.
       */
      public Builder setCurVideoRecDirMinute(int value) {
        
        curVideoRecDirMinute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cur_video_rec_dir_minute = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurVideoRecDirMinute() {
        
        curVideoRecDirMinute_ = 0;
        onChanged();
        return this;
      }

      private int curVideoRecDirSecond_ ;
      /**
       * <code>int32 cur_video_rec_dir_second = 12;</code>
       * @return The curVideoRecDirSecond.
       */
      @java.lang.Override
      public int getCurVideoRecDirSecond() {
        return curVideoRecDirSecond_;
      }
      /**
       * <code>int32 cur_video_rec_dir_second = 12;</code>
       * @param value The curVideoRecDirSecond to set.
       * @return This builder for chaining.
       */
      public Builder setCurVideoRecDirSecond(int value) {
        
        curVideoRecDirSecond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cur_video_rec_dir_second = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurVideoRecDirSecond() {
        
        curVideoRecDirSecond_ = 0;
        onChanged();
        return this;
      }

      private boolean recEnabled_ ;
      /**
       * <code>bool rec_enabled = 13;</code>
       * @return The recEnabled.
       */
      @java.lang.Override
      public boolean getRecEnabled() {
        return recEnabled_;
      }
      /**
       * <code>bool rec_enabled = 13;</code>
       * @param value The recEnabled to set.
       * @return This builder for chaining.
       */
      public Builder setRecEnabled(boolean value) {
        
        recEnabled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool rec_enabled = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecEnabled() {
        
        recEnabled_ = false;
        onChanged();
        return this;
      }

      private boolean importantRecEnabled_ ;
      /**
       * <code>bool important_rec_enabled = 14;</code>
       * @return The importantRecEnabled.
       */
      @java.lang.Override
      public boolean getImportantRecEnabled() {
        return importantRecEnabled_;
      }
      /**
       * <code>bool important_rec_enabled = 14;</code>
       * @param value The importantRecEnabled to set.
       * @return This builder for chaining.
       */
      public Builder setImportantRecEnabled(boolean value) {
        
        importantRecEnabled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool important_rec_enabled = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearImportantRecEnabled() {
        
        importantRecEnabled_ = false;
        onChanged();
        return this;
      }

      private boolean lowDiskSpace_ ;
      /**
       * <code>bool low_disk_space = 15;</code>
       * @return The lowDiskSpace.
       */
      @java.lang.Override
      public boolean getLowDiskSpace() {
        return lowDiskSpace_;
      }
      /**
       * <code>bool low_disk_space = 15;</code>
       * @param value The lowDiskSpace to set.
       * @return This builder for chaining.
       */
      public Builder setLowDiskSpace(boolean value) {
        
        lowDiskSpace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool low_disk_space = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearLowDiskSpace() {
        
        lowDiskSpace_ = false;
        onChanged();
        return this;
      }

      private boolean noDiskSpace_ ;
      /**
       * <code>bool no_disk_space = 16;</code>
       * @return The noDiskSpace.
       */
      @java.lang.Override
      public boolean getNoDiskSpace() {
        return noDiskSpace_;
      }
      /**
       * <code>bool no_disk_space = 16;</code>
       * @param value The noDiskSpace to set.
       * @return This builder for chaining.
       */
      public Builder setNoDiskSpace(boolean value) {
        
        noDiskSpace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool no_disk_space = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearNoDiskSpace() {
        
        noDiskSpace_ = false;
        onChanged();
        return this;
      }

      private int diskSpace_ ;
      /**
       * <code>int32 disk_space = 17;</code>
       * @return The diskSpace.
       */
      @java.lang.Override
      public int getDiskSpace() {
        return diskSpace_;
      }
      /**
       * <code>int32 disk_space = 17;</code>
       * @param value The diskSpace to set.
       * @return This builder for chaining.
       */
      public Builder setDiskSpace(int value) {
        
        diskSpace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 disk_space = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiskSpace() {
        
        diskSpace_ = 0;
        onChanged();
        return this;
      }

      private boolean tracking_ ;
      /**
       * <code>bool tracking = 18;</code>
       * @return The tracking.
       */
      @java.lang.Override
      public boolean getTracking() {
        return tracking_;
      }
      /**
       * <code>bool tracking = 18;</code>
       * @param value The tracking to set.
       * @return This builder for chaining.
       */
      public Builder setTracking(boolean value) {
        
        tracking_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool tracking = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearTracking() {
        
        tracking_ = false;
        onChanged();
        return this;
      }

      private boolean vampireMode_ ;
      /**
       * <code>bool vampire_mode = 19;</code>
       * @return The vampireMode.
       */
      @java.lang.Override
      public boolean getVampireMode() {
        return vampireMode_;
      }
      /**
       * <code>bool vampire_mode = 19;</code>
       * @param value The vampireMode to set.
       * @return This builder for chaining.
       */
      public Builder setVampireMode(boolean value) {
        
        vampireMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool vampire_mode = 19;</code>
       * @return This builder for chaining.
       */
      public Builder clearVampireMode() {
        
        vampireMode_ = false;
        onChanged();
        return this;
      }

      private boolean stabilizationMode_ ;
      /**
       * <code>bool stabilization_mode = 20;</code>
       * @return The stabilizationMode.
       */
      @java.lang.Override
      public boolean getStabilizationMode() {
        return stabilizationMode_;
      }
      /**
       * <code>bool stabilization_mode = 20;</code>
       * @param value The stabilizationMode to set.
       * @return This builder for chaining.
       */
      public Builder setStabilizationMode(boolean value) {
        
        stabilizationMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool stabilization_mode = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearStabilizationMode() {
        
        stabilizationMode_ = false;
        onChanged();
        return this;
      }

      private boolean geodesicMode_ ;
      /**
       * <code>bool geodesic_mode = 21;</code>
       * @return The geodesicMode.
       */
      @java.lang.Override
      public boolean getGeodesicMode() {
        return geodesicMode_;
      }
      /**
       * <code>bool geodesic_mode = 21;</code>
       * @param value The geodesicMode to set.
       * @return This builder for chaining.
       */
      public Builder setGeodesicMode(boolean value) {
        
        geodesicMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool geodesic_mode = 21;</code>
       * @return This builder for chaining.
       */
      public Builder clearGeodesicMode() {
        
        geodesicMode_ = false;
        onChanged();
        return this;
      }

      private boolean cvDumping_ ;
      /**
       * <code>bool cv_dumping = 22;</code>
       * @return The cvDumping.
       */
      @java.lang.Override
      public boolean getCvDumping() {
        return cvDumping_;
      }
      /**
       * <code>bool cv_dumping = 22;</code>
       * @param value The cvDumping to set.
       * @return This builder for chaining.
       */
      public Builder setCvDumping(boolean value) {
        
        cvDumping_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool cv_dumping = 22;</code>
       * @return This builder for chaining.
       */
      public Builder clearCvDumping() {
        
        cvDumping_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ser.JonGuiDataSystem)
    }

    // @@protoc_insertion_point(class_scope:ser.JonGuiDataSystem)
    private static final ser.JonSharedDataSystem.JonGuiDataSystem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ser.JonSharedDataSystem.JonGuiDataSystem();
    }

    public static ser.JonSharedDataSystem.JonGuiDataSystem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JonGuiDataSystem>
        PARSER = new com.google.protobuf.AbstractParser<JonGuiDataSystem>() {
      @java.lang.Override
      public JonGuiDataSystem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JonGuiDataSystem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JonGuiDataSystem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JonGuiDataSystem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ser.JonSharedDataSystem.JonGuiDataSystem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ser_JonGuiDataSystem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ser_JonGuiDataSystem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034jon_shared_data_system.proto\022\003ser\032\033jon" +
      "_shared_data_types.proto\"\336\004\n\020JonGuiDataS" +
      "ystem\022\027\n\017cpu_temperature\030\001 \001(\002\022\027\n\017gpu_te" +
      "mperature\030\002 \001(\002\022\020\n\010gpu_load\030\003 \001(\002\022\020\n\010cpu" +
      "_load\030\004 \001(\002\022\031\n\021power_consumption\030\005 \001(\002\022/" +
      "\n\003loc\030\006 \001(\0162\".ser.JonGuiDataSystemLocali" +
      "zations\022\036\n\026cur_video_rec_dir_year\030\007 \001(\005\022" +
      "\037\n\027cur_video_rec_dir_month\030\010 \001(\005\022\035\n\025cur_" +
      "video_rec_dir_day\030\t \001(\005\022\036\n\026cur_video_rec" +
      "_dir_hour\030\n \001(\005\022 \n\030cur_video_rec_dir_min" +
      "ute\030\013 \001(\005\022 \n\030cur_video_rec_dir_second\030\014 " +
      "\001(\005\022\023\n\013rec_enabled\030\r \001(\010\022\035\n\025important_re" +
      "c_enabled\030\016 \001(\010\022\026\n\016low_disk_space\030\017 \001(\010\022" +
      "\025\n\rno_disk_space\030\020 \001(\010\022\022\n\ndisk_space\030\021 \001" +
      "(\005\022\020\n\010tracking\030\022 \001(\010\022\024\n\014vampire_mode\030\023 \001" +
      "(\010\022\032\n\022stabilization_mode\030\024 \001(\010\022\025\n\rgeodes" +
      "ic_mode\030\025 \001(\010\022\022\n\ncv_dumping\030\026 \001(\010BNZLgit" +
      "-codecommit.eu-central-1.amazonaws.com/v" +
      "1/repos/jettison/jonp/data/systemb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ser.JonSharedDataTypes.getDescriptor(),
        });
    internal_static_ser_JonGuiDataSystem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ser_JonGuiDataSystem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ser_JonGuiDataSystem_descriptor,
        new java.lang.String[] { "CpuTemperature", "GpuTemperature", "GpuLoad", "CpuLoad", "PowerConsumption", "Loc", "CurVideoRecDirYear", "CurVideoRecDirMonth", "CurVideoRecDirDay", "CurVideoRecDirHour", "CurVideoRecDirMinute", "CurVideoRecDirSecond", "RecEnabled", "ImportantRecEnabled", "LowDiskSpace", "NoDiskSpace", "DiskSpace", "Tracking", "VampireMode", "StabilizationMode", "GeodesicMode", "CvDumping", });
    ser.JonSharedDataTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
