// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jon_shared_data_compass_calibration.proto
// Protobuf Java Version: 4.29.5

package data;

public final class JonSharedDataCompassCalibration {
  private JonSharedDataCompassCalibration() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 5,
      /* suffix= */ "",
      JonSharedDataCompassCalibration.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JonGuiDataCompassCalibrationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.JonGuiDataCompassCalibration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 stage = 1;</code>
     * @return The stage.
     */
    int getStage();

    /**
     * <code>uint32 final_stage = 2;</code>
     * @return The finalStage.
     */
    int getFinalStage();

    /**
     * <code>double target_azimuth = 3;</code>
     * @return The targetAzimuth.
     */
    double getTargetAzimuth();

    /**
     * <code>double target_elevation = 4;</code>
     * @return The targetElevation.
     */
    double getTargetElevation();

    /**
     * <code>double target_bank = 5;</code>
     * @return The targetBank.
     */
    double getTargetBank();

    /**
     * <code>.data.JonGuiDataCompassCalibrateStatus status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.data.JonGuiDataCompassCalibrateStatus status = 6;</code>
     * @return The status.
     */
    data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus getStatus();
  }
  /**
   * Protobuf type {@code data.JonGuiDataCompassCalibration}
   */
  public static final class JonGuiDataCompassCalibration extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:data.JonGuiDataCompassCalibration)
      JonGuiDataCompassCalibrationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 5,
        /* suffix= */ "",
        JonGuiDataCompassCalibration.class.getName());
    }
    // Use JonGuiDataCompassCalibration.newBuilder() to construct.
    private JonGuiDataCompassCalibration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private JonGuiDataCompassCalibration() {
      status_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return data.JonSharedDataCompassCalibration.internal_static_data_JonGuiDataCompassCalibration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return data.JonSharedDataCompassCalibration.internal_static_data_JonGuiDataCompassCalibration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.class, data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.Builder.class);
    }

    public static final int STAGE_FIELD_NUMBER = 1;
    private int stage_ = 0;
    /**
     * <code>uint32 stage = 1;</code>
     * @return The stage.
     */
    @java.lang.Override
    public int getStage() {
      return stage_;
    }

    public static final int FINAL_STAGE_FIELD_NUMBER = 2;
    private int finalStage_ = 0;
    /**
     * <code>uint32 final_stage = 2;</code>
     * @return The finalStage.
     */
    @java.lang.Override
    public int getFinalStage() {
      return finalStage_;
    }

    public static final int TARGET_AZIMUTH_FIELD_NUMBER = 3;
    private double targetAzimuth_ = 0D;
    /**
     * <code>double target_azimuth = 3;</code>
     * @return The targetAzimuth.
     */
    @java.lang.Override
    public double getTargetAzimuth() {
      return targetAzimuth_;
    }

    public static final int TARGET_ELEVATION_FIELD_NUMBER = 4;
    private double targetElevation_ = 0D;
    /**
     * <code>double target_elevation = 4;</code>
     * @return The targetElevation.
     */
    @java.lang.Override
    public double getTargetElevation() {
      return targetElevation_;
    }

    public static final int TARGET_BANK_FIELD_NUMBER = 5;
    private double targetBank_ = 0D;
    /**
     * <code>double target_bank = 5;</code>
     * @return The targetBank.
     */
    @java.lang.Override
    public double getTargetBank() {
      return targetBank_;
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private int status_ = 0;
    /**
     * <code>.data.JonGuiDataCompassCalibrateStatus status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.data.JonGuiDataCompassCalibrateStatus status = 6;</code>
     * @return The status.
     */
    @java.lang.Override public data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus getStatus() {
      data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus result = data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.forNumber(status_);
      return result == null ? data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stage_ != 0) {
        output.writeUInt32(1, stage_);
      }
      if (finalStage_ != 0) {
        output.writeUInt32(2, finalStage_);
      }
      if (java.lang.Double.doubleToRawLongBits(targetAzimuth_) != 0) {
        output.writeDouble(3, targetAzimuth_);
      }
      if (java.lang.Double.doubleToRawLongBits(targetElevation_) != 0) {
        output.writeDouble(4, targetElevation_);
      }
      if (java.lang.Double.doubleToRawLongBits(targetBank_) != 0) {
        output.writeDouble(5, targetBank_);
      }
      if (status_ != data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_UNSPECIFIED.getNumber()) {
        output.writeEnum(6, status_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, stage_);
      }
      if (finalStage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, finalStage_);
      }
      if (java.lang.Double.doubleToRawLongBits(targetAzimuth_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, targetAzimuth_);
      }
      if (java.lang.Double.doubleToRawLongBits(targetElevation_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, targetElevation_);
      }
      if (java.lang.Double.doubleToRawLongBits(targetBank_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, targetBank_);
      }
      if (status_ != data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration)) {
        return super.equals(obj);
      }
      data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration other = (data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration) obj;

      if (getStage()
          != other.getStage()) return false;
      if (getFinalStage()
          != other.getFinalStage()) return false;
      if (java.lang.Double.doubleToLongBits(getTargetAzimuth())
          != java.lang.Double.doubleToLongBits(
              other.getTargetAzimuth())) return false;
      if (java.lang.Double.doubleToLongBits(getTargetElevation())
          != java.lang.Double.doubleToLongBits(
              other.getTargetElevation())) return false;
      if (java.lang.Double.doubleToLongBits(getTargetBank())
          != java.lang.Double.doubleToLongBits(
              other.getTargetBank())) return false;
      if (status_ != other.status_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STAGE_FIELD_NUMBER;
      hash = (53 * hash) + getStage();
      hash = (37 * hash) + FINAL_STAGE_FIELD_NUMBER;
      hash = (53 * hash) + getFinalStage();
      hash = (37 * hash) + TARGET_AZIMUTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTargetAzimuth()));
      hash = (37 * hash) + TARGET_ELEVATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTargetElevation()));
      hash = (37 * hash) + TARGET_BANK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTargetBank()));
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.JonGuiDataCompassCalibration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.JonGuiDataCompassCalibration)
        data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibrationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.JonSharedDataCompassCalibration.internal_static_data_JonGuiDataCompassCalibration_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.JonSharedDataCompassCalibration.internal_static_data_JonGuiDataCompassCalibration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.class, data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.Builder.class);
      }

      // Construct using data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        stage_ = 0;
        finalStage_ = 0;
        targetAzimuth_ = 0D;
        targetElevation_ = 0D;
        targetBank_ = 0D;
        status_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return data.JonSharedDataCompassCalibration.internal_static_data_JonGuiDataCompassCalibration_descriptor;
      }

      @java.lang.Override
      public data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration getDefaultInstanceForType() {
        return data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.getDefaultInstance();
      }

      @java.lang.Override
      public data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration build() {
        data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration buildPartial() {
        data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration result = new data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.stage_ = stage_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.finalStage_ = finalStage_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.targetAzimuth_ = targetAzimuth_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.targetElevation_ = targetElevation_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.targetBank_ = targetBank_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.status_ = status_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration) {
          return mergeFrom((data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration other) {
        if (other == data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.getDefaultInstance()) return this;
        if (other.getStage() != 0) {
          setStage(other.getStage());
        }
        if (other.getFinalStage() != 0) {
          setFinalStage(other.getFinalStage());
        }
        if (other.getTargetAzimuth() != 0D) {
          setTargetAzimuth(other.getTargetAzimuth());
        }
        if (other.getTargetElevation() != 0D) {
          setTargetElevation(other.getTargetElevation());
        }
        if (other.getTargetBank() != 0D) {
          setTargetBank(other.getTargetBank());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                stage_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                finalStage_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 25: {
                targetAzimuth_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                targetElevation_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 41: {
                targetBank_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 48: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int stage_ ;
      /**
       * <code>uint32 stage = 1;</code>
       * @return The stage.
       */
      @java.lang.Override
      public int getStage() {
        return stage_;
      }
      /**
       * <code>uint32 stage = 1;</code>
       * @param value The stage to set.
       * @return This builder for chaining.
       */
      public Builder setStage(int value) {

        stage_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 stage = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stage_ = 0;
        onChanged();
        return this;
      }

      private int finalStage_ ;
      /**
       * <code>uint32 final_stage = 2;</code>
       * @return The finalStage.
       */
      @java.lang.Override
      public int getFinalStage() {
        return finalStage_;
      }
      /**
       * <code>uint32 final_stage = 2;</code>
       * @param value The finalStage to set.
       * @return This builder for chaining.
       */
      public Builder setFinalStage(int value) {

        finalStage_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 final_stage = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFinalStage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        finalStage_ = 0;
        onChanged();
        return this;
      }

      private double targetAzimuth_ ;
      /**
       * <code>double target_azimuth = 3;</code>
       * @return The targetAzimuth.
       */
      @java.lang.Override
      public double getTargetAzimuth() {
        return targetAzimuth_;
      }
      /**
       * <code>double target_azimuth = 3;</code>
       * @param value The targetAzimuth to set.
       * @return This builder for chaining.
       */
      public Builder setTargetAzimuth(double value) {

        targetAzimuth_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double target_azimuth = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetAzimuth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        targetAzimuth_ = 0D;
        onChanged();
        return this;
      }

      private double targetElevation_ ;
      /**
       * <code>double target_elevation = 4;</code>
       * @return The targetElevation.
       */
      @java.lang.Override
      public double getTargetElevation() {
        return targetElevation_;
      }
      /**
       * <code>double target_elevation = 4;</code>
       * @param value The targetElevation to set.
       * @return This builder for chaining.
       */
      public Builder setTargetElevation(double value) {

        targetElevation_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double target_elevation = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetElevation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        targetElevation_ = 0D;
        onChanged();
        return this;
      }

      private double targetBank_ ;
      /**
       * <code>double target_bank = 5;</code>
       * @return The targetBank.
       */
      @java.lang.Override
      public double getTargetBank() {
        return targetBank_;
      }
      /**
       * <code>double target_bank = 5;</code>
       * @param value The targetBank to set.
       * @return This builder for chaining.
       */
      public Builder setTargetBank(double value) {

        targetBank_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double target_bank = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetBank() {
        bitField0_ = (bitField0_ & ~0x00000010);
        targetBank_ = 0D;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.data.JonGuiDataCompassCalibrateStatus status = 6;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.data.JonGuiDataCompassCalibrateStatus status = 6;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.data.JonGuiDataCompassCalibrateStatus status = 6;</code>
       * @return The status.
       */
      @java.lang.Override
      public data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus getStatus() {
        data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus result = data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.forNumber(status_);
        return result == null ? data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.data.JonGuiDataCompassCalibrateStatus status = 6;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(data.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.data.JonGuiDataCompassCalibrateStatus status = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:data.JonGuiDataCompassCalibration)
    }

    // @@protoc_insertion_point(class_scope:data.JonGuiDataCompassCalibration)
    private static final data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration();
    }

    public static data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JonGuiDataCompassCalibration>
        PARSER = new com.google.protobuf.AbstractParser<JonGuiDataCompassCalibration>() {
      @java.lang.Override
      public JonGuiDataCompassCalibration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<JonGuiDataCompassCalibration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JonGuiDataCompassCalibration> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public data.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_JonGuiDataCompassCalibration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_JonGuiDataCompassCalibration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)jon_shared_data_compass_calibration.pr" +
      "oto\022\004data\032\033jon_shared_data_types.proto\"\301" +
      "\001\n\034JonGuiDataCompassCalibration\022\r\n\005stage" +
      "\030\001 \001(\r\022\023\n\013final_stage\030\002 \001(\r\022\026\n\016target_az" +
      "imuth\030\003 \001(\001\022\030\n\020target_elevation\030\004 \001(\001\022\023\n" +
      "\013target_bank\030\005 \001(\001\0226\n\006status\030\006 \001(\0162&.dat" +
      "a.JonGuiDataCompassCalibrateStatusB[ZYgi" +
      "t-codecommit.eu-central-1.amazonaws.com/" +
      "v1/repos/jettison/jonp/data/compass_cali" +
      "brationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          data.JonSharedDataTypes.getDescriptor(),
        });
    internal_static_data_JonGuiDataCompassCalibration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_JonGuiDataCompassCalibration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_data_JonGuiDataCompassCalibration_descriptor,
        new java.lang.String[] { "Stage", "FinalStage", "TargetAzimuth", "TargetElevation", "TargetBank", "Status", });
    descriptor.resolveAllFeaturesImmutable();
    data.JonSharedDataTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
