(ns potatoclient.proto.command
  "Commands index - re-exports all command namespaces"
  (:require [potatoclient.proto.cmd.lira :as lira]
            [potatoclient.proto.cmd.system :as system]
            [potatoclient.proto.cmd.lrf :as lrf]
            [potatoclient.proto.cmd.compass :as compass]
            [potatoclient.proto.cmd.osd :as osd]
            [potatoclient.proto.cmd.gps :as gps]
            [potatoclient.proto.cmd.daycamera :as day-camera]
            [potatoclient.proto.cmd.daycamglassheater :as day-cam-glass-heater]
            [potatoclient.proto.cmd.rotaryplatform :as rotary-platform]
            [potatoclient.proto.cmd.cv :as cv]
            [potatoclient.proto.cmd.lrf_calib :as lrf-calib]
            [potatoclient.proto.cmd.heatcamera :as heat-camera]))

;; Re-export all public functions from sub-namespaces
;; This supports testing without needing to know the internal namespace
;; structure

(def lira-build-root lira/build-root)
(def lira-parse-root lira/parse-root)
(def lira-build-refine-target lira/build-refine-target)
(def lira-parse-refine-target lira/parse-refine-target)
(def lira-build-jon-gui-data-lira-target lira/build-jon-gui-data-lira-target)
(def lira-parse-jon-gui-data-lira-target lira/parse-jon-gui-data-lira-target)
(def system-build-root system/build-root)
(def system-parse-root system/parse-root)
(def system-build-start-a-ll system/build-start-a-ll)
(def system-parse-start-a-ll system/parse-start-a-ll)
(def system-build-stop-a-ll system/build-stop-a-ll)
(def system-parse-stop-a-ll system/parse-stop-a-ll)
(def system-build-reboot system/build-reboot)
(def system-parse-reboot system/parse-reboot)
(def system-build-power-off system/build-power-off)
(def system-parse-power-off system/parse-power-off)
(def system-build-reset-configs system/build-reset-configs)
(def system-parse-reset-configs system/parse-reset-configs)
(def system-build-start-rec system/build-start-rec)
(def system-parse-start-rec system/parse-start-rec)
(def system-build-stop-rec system/build-stop-rec)
(def system-parse-stop-rec system/parse-stop-rec)
(def system-build-mark-rec-important system/build-mark-rec-important)
(def system-parse-mark-rec-important system/parse-mark-rec-important)
(def system-build-unmark-rec-important system/build-unmark-rec-important)
(def system-parse-unmark-rec-important system/parse-unmark-rec-important)
(def system-build-enter-transport system/build-enter-transport)
(def system-parse-enter-transport system/parse-enter-transport)
(def system-build-enable-geodesic-mode system/build-enable-geodesic-mode)
(def system-parse-enable-geodesic-mode system/parse-enable-geodesic-mode)
(def system-build-disable-geodesic-mode system/build-disable-geodesic-mode)
(def system-parse-disable-geodesic-mode system/parse-disable-geodesic-mode)
(def system-build-set-localization system/build-set-localization)
(def system-parse-set-localization system/parse-set-localization)
(def lrf-build-root lrf/build-root)
(def lrf-parse-root lrf/parse-root)
(def lrf-build-get-meteo lrf/build-get-meteo)
(def lrf-parse-get-meteo lrf/parse-get-meteo)
(def lrf-build-start lrf/build-start)
(def lrf-parse-start lrf/parse-start)
(def lrf-build-stop lrf/build-stop)
(def lrf-parse-stop lrf/parse-stop)
(def lrf-build-measure lrf/build-measure)
(def lrf-parse-measure lrf/parse-measure)
(def lrf-build-scan-on lrf/build-scan-on)
(def lrf-parse-scan-on lrf/parse-scan-on)
(def lrf-build-scan-off lrf/build-scan-off)
(def lrf-parse-scan-off lrf/parse-scan-off)
(def lrf-build-refine-off lrf/build-refine-off)
(def lrf-parse-refine-off lrf/parse-refine-off)
(def lrf-build-refine-on lrf/build-refine-on)
(def lrf-parse-refine-on lrf/parse-refine-on)
(def lrf-build-target-designator-off lrf/build-target-designator-off)
(def lrf-parse-target-designator-off lrf/parse-target-designator-off)
(def lrf-build-target-designator-on-mode-a
  lrf/build-target-designator-on-mode-a)
(def lrf-parse-target-designator-on-mode-a
  lrf/parse-target-designator-on-mode-a)
(def lrf-build-target-designator-on-mode-b
  lrf/build-target-designator-on-mode-b)
(def lrf-parse-target-designator-on-mode-b
  lrf/parse-target-designator-on-mode-b)
(def lrf-build-enable-fog-mode lrf/build-enable-fog-mode)
(def lrf-parse-enable-fog-mode lrf/parse-enable-fog-mode)
(def lrf-build-disable-fog-mode lrf/build-disable-fog-mode)
(def lrf-parse-disable-fog-mode lrf/parse-disable-fog-mode)
(def lrf-build-set-scan-mode lrf/build-set-scan-mode)
(def lrf-parse-set-scan-mode lrf/parse-set-scan-mode)
(def lrf-build-new-session lrf/build-new-session)
(def lrf-parse-new-session lrf/parse-new-session)
(def compass-build-root compass/build-root)
(def compass-parse-root compass/parse-root)
(def compass-build-start compass/build-start)
(def compass-parse-start compass/parse-start)
(def compass-build-stop compass/build-stop)
(def compass-parse-stop compass/parse-stop)
(def compass-build-next compass/build-next)
(def compass-parse-next compass/parse-next)
(def compass-build-calibrate-start-long compass/build-calibrate-start-long)
(def compass-parse-calibrate-start-long compass/parse-calibrate-start-long)
(def compass-build-calibrate-start-short compass/build-calibrate-start-short)
(def compass-parse-calibrate-start-short compass/parse-calibrate-start-short)
(def compass-build-calibrate-next compass/build-calibrate-next)
(def compass-parse-calibrate-next compass/parse-calibrate-next)
(def compass-build-calibrate-cencel compass/build-calibrate-cencel)
(def compass-parse-calibrate-cencel compass/parse-calibrate-cencel)
(def compass-build-get-meteo compass/build-get-meteo)
(def compass-parse-get-meteo compass/parse-get-meteo)
(def compass-build-set-magnetic-declination
  compass/build-set-magnetic-declination)
(def compass-parse-set-magnetic-declination
  compass/parse-set-magnetic-declination)
(def compass-build-set-offset-angle-azimuth
  compass/build-set-offset-angle-azimuth)
(def compass-parse-set-offset-angle-azimuth
  compass/parse-set-offset-angle-azimuth)
(def compass-build-set-offset-angle-elevation
  compass/build-set-offset-angle-elevation)
(def compass-parse-set-offset-angle-elevation
  compass/parse-set-offset-angle-elevation)
(def compass-build-set-use-rotary-position
  compass/build-set-use-rotary-position)
(def compass-parse-set-use-rotary-position
  compass/parse-set-use-rotary-position)
(def osd-build-root osd/build-root)
(def osd-parse-root osd/parse-root)
(def osd-build-show-default-screen osd/build-show-default-screen)
(def osd-parse-show-default-screen osd/parse-show-default-screen)
(def osd-build-show-lrf-measure-screen osd/build-show-lrf-measure-screen)
(def osd-parse-show-lrf-measure-screen osd/parse-show-lrf-measure-screen)
(def osd-build-show-lrf-result-screen osd/build-show-lrf-result-screen)
(def osd-parse-show-lrf-result-screen osd/parse-show-lrf-result-screen)
(def osd-build-show-lrf-result-simplified-screen
  osd/build-show-lrf-result-simplified-screen)
(def osd-parse-show-lrf-result-simplified-screen
  osd/parse-show-lrf-result-simplified-screen)
(def osd-build-enable-heat-osd osd/build-enable-heat-osd)
(def osd-parse-enable-heat-osd osd/parse-enable-heat-osd)
(def osd-build-disable-heat-osd osd/build-disable-heat-osd)
(def osd-parse-disable-heat-osd osd/parse-disable-heat-osd)
(def osd-build-enable-day-osd osd/build-enable-day-osd)
(def osd-parse-enable-day-osd osd/parse-enable-day-osd)
(def osd-build-disable-day-osd osd/build-disable-day-osd)
(def osd-parse-disable-day-osd osd/parse-disable-day-osd)
(def gps-build-root gps/build-root)
(def gps-parse-root gps/parse-root)
(def gps-build-start gps/build-start)
(def gps-parse-start gps/parse-start)
(def gps-build-stop gps/build-stop)
(def gps-parse-stop gps/parse-stop)
(def gps-build-get-meteo gps/build-get-meteo)
(def gps-parse-get-meteo gps/parse-get-meteo)
(def gps-build-set-use-manual-position gps/build-set-use-manual-position)
(def gps-parse-set-use-manual-position gps/parse-set-use-manual-position)
(def gps-build-set-manual-position gps/build-set-manual-position)
(def gps-parse-set-manual-position gps/parse-set-manual-position)
(def cv-build-root cv/build-root)
(def cv-parse-root cv/parse-root)
(def cv-build-vampire-mode-enable cv/build-vampire-mode-enable)
(def cv-parse-vampire-mode-enable cv/parse-vampire-mode-enable)
(def cv-build-dump-start cv/build-dump-start)
(def cv-parse-dump-start cv/parse-dump-start)
(def cv-build-dump-stop cv/build-dump-stop)
(def cv-parse-dump-stop cv/parse-dump-stop)
(def cv-build-vampire-mode-disable cv/build-vampire-mode-disable)
(def cv-parse-vampire-mode-disable cv/parse-vampire-mode-disable)
(def cv-build-stabilization-mode-enable cv/build-stabilization-mode-enable)
(def cv-parse-stabilization-mode-enable cv/parse-stabilization-mode-enable)
(def cv-build-stabilization-mode-disable cv/build-stabilization-mode-disable)
(def cv-parse-stabilization-mode-disable cv/parse-stabilization-mode-disable)
(def cv-build-set-auto-focus cv/build-set-auto-focus)
(def cv-parse-set-auto-focus cv/parse-set-auto-focus)
(def cv-build-start-track-ndc cv/build-start-track-ndc)
(def cv-parse-start-track-ndc cv/parse-start-track-ndc)
(def cv-build-stop-track cv/build-stop-track)
(def cv-parse-stop-track cv/parse-stop-track)
