// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jon_shared_data_compass_calibration.proto

package ser;

public final class JonSharedDataCompassCalibration {
  private JonSharedDataCompassCalibration() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JonGuiDataCompassCalibrationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ser.JonGuiDataCompassCalibration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 stage = 1;</code>
     * @return The stage.
     */
    int getStage();

    /**
     * <code>uint32 final_stage = 2;</code>
     * @return The finalStage.
     */
    int getFinalStage();

    /**
     * <code>double target_azimuth = 3;</code>
     * @return The targetAzimuth.
     */
    double getTargetAzimuth();

    /**
     * <code>double target_elevation = 4;</code>
     * @return The targetElevation.
     */
    double getTargetElevation();

    /**
     * <code>double target_bank = 5;</code>
     * @return The targetBank.
     */
    double getTargetBank();

    /**
     * <code>.ser.JonGuiDataCompassCalibrateStatus status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.ser.JonGuiDataCompassCalibrateStatus status = 6;</code>
     * @return The status.
     */
    ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus getStatus();
  }
  /**
   * Protobuf type {@code ser.JonGuiDataCompassCalibration}
   */
  public static final class JonGuiDataCompassCalibration extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ser.JonGuiDataCompassCalibration)
      JonGuiDataCompassCalibrationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JonGuiDataCompassCalibration.newBuilder() to construct.
    private JonGuiDataCompassCalibration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JonGuiDataCompassCalibration() {
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JonGuiDataCompassCalibration();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JonGuiDataCompassCalibration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              stage_ = input.readUInt32();
              break;
            }
            case 16: {

              finalStage_ = input.readUInt32();
              break;
            }
            case 25: {

              targetAzimuth_ = input.readDouble();
              break;
            }
            case 33: {

              targetElevation_ = input.readDouble();
              break;
            }
            case 41: {

              targetBank_ = input.readDouble();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ser.JonSharedDataCompassCalibration.internal_static_ser_JonGuiDataCompassCalibration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ser.JonSharedDataCompassCalibration.internal_static_ser_JonGuiDataCompassCalibration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.class, ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.Builder.class);
    }

    public static final int STAGE_FIELD_NUMBER = 1;
    private int stage_;
    /**
     * <code>uint32 stage = 1;</code>
     * @return The stage.
     */
    @java.lang.Override
    public int getStage() {
      return stage_;
    }

    public static final int FINAL_STAGE_FIELD_NUMBER = 2;
    private int finalStage_;
    /**
     * <code>uint32 final_stage = 2;</code>
     * @return The finalStage.
     */
    @java.lang.Override
    public int getFinalStage() {
      return finalStage_;
    }

    public static final int TARGET_AZIMUTH_FIELD_NUMBER = 3;
    private double targetAzimuth_;
    /**
     * <code>double target_azimuth = 3;</code>
     * @return The targetAzimuth.
     */
    @java.lang.Override
    public double getTargetAzimuth() {
      return targetAzimuth_;
    }

    public static final int TARGET_ELEVATION_FIELD_NUMBER = 4;
    private double targetElevation_;
    /**
     * <code>double target_elevation = 4;</code>
     * @return The targetElevation.
     */
    @java.lang.Override
    public double getTargetElevation() {
      return targetElevation_;
    }

    public static final int TARGET_BANK_FIELD_NUMBER = 5;
    private double targetBank_;
    /**
     * <code>double target_bank = 5;</code>
     * @return The targetBank.
     */
    @java.lang.Override
    public double getTargetBank() {
      return targetBank_;
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private int status_;
    /**
     * <code>.ser.JonGuiDataCompassCalibrateStatus status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.ser.JonGuiDataCompassCalibrateStatus status = 6;</code>
     * @return The status.
     */
    @java.lang.Override public ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus getStatus() {
      @SuppressWarnings("deprecation")
      ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus result = ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.valueOf(status_);
      return result == null ? ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stage_ != 0) {
        output.writeUInt32(1, stage_);
      }
      if (finalStage_ != 0) {
        output.writeUInt32(2, finalStage_);
      }
      if (targetAzimuth_ != 0D) {
        output.writeDouble(3, targetAzimuth_);
      }
      if (targetElevation_ != 0D) {
        output.writeDouble(4, targetElevation_);
      }
      if (targetBank_ != 0D) {
        output.writeDouble(5, targetBank_);
      }
      if (status_ != ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_UNSPECIFIED.getNumber()) {
        output.writeEnum(6, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, stage_);
      }
      if (finalStage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, finalStage_);
      }
      if (targetAzimuth_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, targetAzimuth_);
      }
      if (targetElevation_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, targetElevation_);
      }
      if (targetBank_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, targetBank_);
      }
      if (status_ != ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.JON_GUI_DATA_COMPASS_CALIBRATE_STATUS_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration)) {
        return super.equals(obj);
      }
      ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration other = (ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration) obj;

      if (getStage()
          != other.getStage()) return false;
      if (getFinalStage()
          != other.getFinalStage()) return false;
      if (java.lang.Double.doubleToLongBits(getTargetAzimuth())
          != java.lang.Double.doubleToLongBits(
              other.getTargetAzimuth())) return false;
      if (java.lang.Double.doubleToLongBits(getTargetElevation())
          != java.lang.Double.doubleToLongBits(
              other.getTargetElevation())) return false;
      if (java.lang.Double.doubleToLongBits(getTargetBank())
          != java.lang.Double.doubleToLongBits(
              other.getTargetBank())) return false;
      if (status_ != other.status_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STAGE_FIELD_NUMBER;
      hash = (53 * hash) + getStage();
      hash = (37 * hash) + FINAL_STAGE_FIELD_NUMBER;
      hash = (53 * hash) + getFinalStage();
      hash = (37 * hash) + TARGET_AZIMUTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTargetAzimuth()));
      hash = (37 * hash) + TARGET_ELEVATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTargetElevation()));
      hash = (37 * hash) + TARGET_BANK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTargetBank()));
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ser.JonGuiDataCompassCalibration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ser.JonGuiDataCompassCalibration)
        ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibrationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ser.JonSharedDataCompassCalibration.internal_static_ser_JonGuiDataCompassCalibration_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ser.JonSharedDataCompassCalibration.internal_static_ser_JonGuiDataCompassCalibration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.class, ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.Builder.class);
      }

      // Construct using ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        stage_ = 0;

        finalStage_ = 0;

        targetAzimuth_ = 0D;

        targetElevation_ = 0D;

        targetBank_ = 0D;

        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ser.JonSharedDataCompassCalibration.internal_static_ser_JonGuiDataCompassCalibration_descriptor;
      }

      @java.lang.Override
      public ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration getDefaultInstanceForType() {
        return ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.getDefaultInstance();
      }

      @java.lang.Override
      public ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration build() {
        ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration buildPartial() {
        ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration result = new ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration(this);
        result.stage_ = stage_;
        result.finalStage_ = finalStage_;
        result.targetAzimuth_ = targetAzimuth_;
        result.targetElevation_ = targetElevation_;
        result.targetBank_ = targetBank_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration) {
          return mergeFrom((ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration other) {
        if (other == ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration.getDefaultInstance()) return this;
        if (other.getStage() != 0) {
          setStage(other.getStage());
        }
        if (other.getFinalStage() != 0) {
          setFinalStage(other.getFinalStage());
        }
        if (other.getTargetAzimuth() != 0D) {
          setTargetAzimuth(other.getTargetAzimuth());
        }
        if (other.getTargetElevation() != 0D) {
          setTargetElevation(other.getTargetElevation());
        }
        if (other.getTargetBank() != 0D) {
          setTargetBank(other.getTargetBank());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int stage_ ;
      /**
       * <code>uint32 stage = 1;</code>
       * @return The stage.
       */
      @java.lang.Override
      public int getStage() {
        return stage_;
      }
      /**
       * <code>uint32 stage = 1;</code>
       * @param value The stage to set.
       * @return This builder for chaining.
       */
      public Builder setStage(int value) {
        
        stage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 stage = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStage() {
        
        stage_ = 0;
        onChanged();
        return this;
      }

      private int finalStage_ ;
      /**
       * <code>uint32 final_stage = 2;</code>
       * @return The finalStage.
       */
      @java.lang.Override
      public int getFinalStage() {
        return finalStage_;
      }
      /**
       * <code>uint32 final_stage = 2;</code>
       * @param value The finalStage to set.
       * @return This builder for chaining.
       */
      public Builder setFinalStage(int value) {
        
        finalStage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 final_stage = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFinalStage() {
        
        finalStage_ = 0;
        onChanged();
        return this;
      }

      private double targetAzimuth_ ;
      /**
       * <code>double target_azimuth = 3;</code>
       * @return The targetAzimuth.
       */
      @java.lang.Override
      public double getTargetAzimuth() {
        return targetAzimuth_;
      }
      /**
       * <code>double target_azimuth = 3;</code>
       * @param value The targetAzimuth to set.
       * @return This builder for chaining.
       */
      public Builder setTargetAzimuth(double value) {
        
        targetAzimuth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double target_azimuth = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetAzimuth() {
        
        targetAzimuth_ = 0D;
        onChanged();
        return this;
      }

      private double targetElevation_ ;
      /**
       * <code>double target_elevation = 4;</code>
       * @return The targetElevation.
       */
      @java.lang.Override
      public double getTargetElevation() {
        return targetElevation_;
      }
      /**
       * <code>double target_elevation = 4;</code>
       * @param value The targetElevation to set.
       * @return This builder for chaining.
       */
      public Builder setTargetElevation(double value) {
        
        targetElevation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double target_elevation = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetElevation() {
        
        targetElevation_ = 0D;
        onChanged();
        return this;
      }

      private double targetBank_ ;
      /**
       * <code>double target_bank = 5;</code>
       * @return The targetBank.
       */
      @java.lang.Override
      public double getTargetBank() {
        return targetBank_;
      }
      /**
       * <code>double target_bank = 5;</code>
       * @param value The targetBank to set.
       * @return This builder for chaining.
       */
      public Builder setTargetBank(double value) {
        
        targetBank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double target_bank = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetBank() {
        
        targetBank_ = 0D;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.ser.JonGuiDataCompassCalibrateStatus status = 6;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.ser.JonGuiDataCompassCalibrateStatus status = 6;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ser.JonGuiDataCompassCalibrateStatus status = 6;</code>
       * @return The status.
       */
      @java.lang.Override
      public ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus getStatus() {
        @SuppressWarnings("deprecation")
        ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus result = ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.valueOf(status_);
        return result == null ? ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.ser.JonGuiDataCompassCalibrateStatus status = 6;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(ser.JonSharedDataTypes.JonGuiDataCompassCalibrateStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ser.JonGuiDataCompassCalibrateStatus status = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ser.JonGuiDataCompassCalibration)
    }

    // @@protoc_insertion_point(class_scope:ser.JonGuiDataCompassCalibration)
    private static final ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration();
    }

    public static ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JonGuiDataCompassCalibration>
        PARSER = new com.google.protobuf.AbstractParser<JonGuiDataCompassCalibration>() {
      @java.lang.Override
      public JonGuiDataCompassCalibration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JonGuiDataCompassCalibration(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JonGuiDataCompassCalibration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JonGuiDataCompassCalibration> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ser.JonSharedDataCompassCalibration.JonGuiDataCompassCalibration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ser_JonGuiDataCompassCalibration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ser_JonGuiDataCompassCalibration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)jon_shared_data_compass_calibration.pr" +
      "oto\022\003ser\032\033jon_shared_data_types.proto\"\300\001" +
      "\n\034JonGuiDataCompassCalibration\022\r\n\005stage\030" +
      "\001 \001(\r\022\023\n\013final_stage\030\002 \001(\r\022\026\n\016target_azi" +
      "muth\030\003 \001(\001\022\030\n\020target_elevation\030\004 \001(\001\022\023\n\013" +
      "target_bank\030\005 \001(\001\0225\n\006status\030\006 \001(\0162%.ser." +
      "JonGuiDataCompassCalibrateStatusB[ZYgit-" +
      "codecommit.eu-central-1.amazonaws.com/v1" +
      "/repos/jettison/jonp/data/compass_calibr" +
      "ationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ser.JonSharedDataTypes.getDescriptor(),
        });
    internal_static_ser_JonGuiDataCompassCalibration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ser_JonGuiDataCompassCalibration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ser_JonGuiDataCompassCalibration_descriptor,
        new java.lang.String[] { "Stage", "FinalStage", "TargetAzimuth", "TargetElevation", "TargetBank", "Status", });
    ser.JonSharedDataTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
