// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jon_shared_data_day_cam_glass_heater.proto

package ser;

public final class JonSharedDataDayCamGlassHeater {
  private JonSharedDataDayCamGlassHeater() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JonGuiDataDayCamGlassHeaterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ser.JonGuiDataDayCamGlassHeater)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double temperature = 1;</code>
     * @return The temperature.
     */
    double getTemperature();

    /**
     * <code>bool status = 2;</code>
     * @return The status.
     */
    boolean getStatus();
  }
  /**
   * Protobuf type {@code ser.JonGuiDataDayCamGlassHeater}
   */
  public static final class JonGuiDataDayCamGlassHeater extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ser.JonGuiDataDayCamGlassHeater)
      JonGuiDataDayCamGlassHeaterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JonGuiDataDayCamGlassHeater.newBuilder() to construct.
    private JonGuiDataDayCamGlassHeater(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JonGuiDataDayCamGlassHeater() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JonGuiDataDayCamGlassHeater();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JonGuiDataDayCamGlassHeater(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              temperature_ = input.readDouble();
              break;
            }
            case 16: {

              status_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ser.JonSharedDataDayCamGlassHeater.internal_static_ser_JonGuiDataDayCamGlassHeater_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ser.JonSharedDataDayCamGlassHeater.internal_static_ser_JonGuiDataDayCamGlassHeater_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater.class, ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater.Builder.class);
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 1;
    private double temperature_;
    /**
     * <code>double temperature = 1;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public double getTemperature() {
      return temperature_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private boolean status_;
    /**
     * <code>bool status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public boolean getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (temperature_ != 0D) {
        output.writeDouble(1, temperature_);
      }
      if (status_ != false) {
        output.writeBool(2, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (temperature_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, temperature_);
      }
      if (status_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater)) {
        return super.equals(obj);
      }
      ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater other = (ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater) obj;

      if (java.lang.Double.doubleToLongBits(getTemperature())
          != java.lang.Double.doubleToLongBits(
              other.getTemperature())) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTemperature()));
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ser.JonGuiDataDayCamGlassHeater}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ser.JonGuiDataDayCamGlassHeater)
        ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeaterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ser.JonSharedDataDayCamGlassHeater.internal_static_ser_JonGuiDataDayCamGlassHeater_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ser.JonSharedDataDayCamGlassHeater.internal_static_ser_JonGuiDataDayCamGlassHeater_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater.class, ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater.Builder.class);
      }

      // Construct using ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        temperature_ = 0D;

        status_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ser.JonSharedDataDayCamGlassHeater.internal_static_ser_JonGuiDataDayCamGlassHeater_descriptor;
      }

      @java.lang.Override
      public ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater getDefaultInstanceForType() {
        return ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater.getDefaultInstance();
      }

      @java.lang.Override
      public ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater build() {
        ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater buildPartial() {
        ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater result = new ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater(this);
        result.temperature_ = temperature_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater) {
          return mergeFrom((ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater other) {
        if (other == ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater.getDefaultInstance()) return this;
        if (other.getTemperature() != 0D) {
          setTemperature(other.getTemperature());
        }
        if (other.getStatus() != false) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double temperature_ ;
      /**
       * <code>double temperature = 1;</code>
       * @return The temperature.
       */
      @java.lang.Override
      public double getTemperature() {
        return temperature_;
      }
      /**
       * <code>double temperature = 1;</code>
       * @param value The temperature to set.
       * @return This builder for chaining.
       */
      public Builder setTemperature(double value) {
        
        temperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double temperature = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemperature() {
        
        temperature_ = 0D;
        onChanged();
        return this;
      }

      private boolean status_ ;
      /**
       * <code>bool status = 2;</code>
       * @return The status.
       */
      @java.lang.Override
      public boolean getStatus() {
        return status_;
      }
      /**
       * <code>bool status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(boolean value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ser.JonGuiDataDayCamGlassHeater)
    }

    // @@protoc_insertion_point(class_scope:ser.JonGuiDataDayCamGlassHeater)
    private static final ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater();
    }

    public static ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JonGuiDataDayCamGlassHeater>
        PARSER = new com.google.protobuf.AbstractParser<JonGuiDataDayCamGlassHeater>() {
      @java.lang.Override
      public JonGuiDataDayCamGlassHeater parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JonGuiDataDayCamGlassHeater(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JonGuiDataDayCamGlassHeater> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JonGuiDataDayCamGlassHeater> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ser.JonSharedDataDayCamGlassHeater.JonGuiDataDayCamGlassHeater getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ser_JonGuiDataDayCamGlassHeater_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ser_JonGuiDataDayCamGlassHeater_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*jon_shared_data_day_cam_glass_heater.p" +
      "roto\022\003ser\"B\n\033JonGuiDataDayCamGlassHeater" +
      "\022\023\n\013temperature\030\001 \001(\001\022\016\n\006status\030\002 \001(\010B\\Z" +
      "Zgit-codecommit.eu-central-1.amazonaws.c" +
      "om/v1/repos/jettison/jonp/data/day_cam_g" +
      "lass_heaterb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ser_JonGuiDataDayCamGlassHeater_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ser_JonGuiDataDayCamGlassHeater_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ser_JonGuiDataDayCamGlassHeater_descriptor,
        new java.lang.String[] { "Temperature", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
