// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jon_shared_cmd_lira.proto

package cmd.Lira;

public final class JonSharedCmdLira {
  private JonSharedCmdLira() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RootOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cmd.Lira.Root)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
     * @return Whether the refineTarget field is set.
     */
    boolean hasRefineTarget();
    /**
     * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
     * @return The refineTarget.
     */
    cmd.Lira.JonSharedCmdLira.Refine_target getRefineTarget();
    /**
     * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
     */
    cmd.Lira.JonSharedCmdLira.Refine_targetOrBuilder getRefineTargetOrBuilder();

    public cmd.Lira.JonSharedCmdLira.Root.CmdCase getCmdCase();
  }
  /**
   * Protobuf type {@code cmd.Lira.Root}
   */
  public static final class Root extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cmd.Lira.Root)
      RootOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Root.newBuilder() to construct.
    private Root(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Root() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Root();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Root(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cmd.Lira.JonSharedCmdLira.Refine_target.Builder subBuilder = null;
              if (cmdCase_ == 1) {
                subBuilder = ((cmd.Lira.JonSharedCmdLira.Refine_target) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(cmd.Lira.JonSharedCmdLira.Refine_target.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cmd.Lira.JonSharedCmdLira.Refine_target) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 1;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_Root_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_Root_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cmd.Lira.JonSharedCmdLira.Root.class, cmd.Lira.JonSharedCmdLira.Root.Builder.class);
    }

    private int cmdCase_ = 0;
    private java.lang.Object cmd_;
    public enum CmdCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      REFINE_TARGET(1),
      CMD_NOT_SET(0);
      private final int value;
      private CmdCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CmdCase valueOf(int value) {
        return forNumber(value);
      }

      public static CmdCase forNumber(int value) {
        switch (value) {
          case 1: return REFINE_TARGET;
          case 0: return CMD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CmdCase
    getCmdCase() {
      return CmdCase.forNumber(
          cmdCase_);
    }

    public static final int REFINE_TARGET_FIELD_NUMBER = 1;
    /**
     * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
     * @return Whether the refineTarget field is set.
     */
    @java.lang.Override
    public boolean hasRefineTarget() {
      return cmdCase_ == 1;
    }
    /**
     * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
     * @return The refineTarget.
     */
    @java.lang.Override
    public cmd.Lira.JonSharedCmdLira.Refine_target getRefineTarget() {
      if (cmdCase_ == 1) {
         return (cmd.Lira.JonSharedCmdLira.Refine_target) cmd_;
      }
      return cmd.Lira.JonSharedCmdLira.Refine_target.getDefaultInstance();
    }
    /**
     * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
     */
    @java.lang.Override
    public cmd.Lira.JonSharedCmdLira.Refine_targetOrBuilder getRefineTargetOrBuilder() {
      if (cmdCase_ == 1) {
         return (cmd.Lira.JonSharedCmdLira.Refine_target) cmd_;
      }
      return cmd.Lira.JonSharedCmdLira.Refine_target.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdCase_ == 1) {
        output.writeMessage(1, (cmd.Lira.JonSharedCmdLira.Refine_target) cmd_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (cmd.Lira.JonSharedCmdLira.Refine_target) cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cmd.Lira.JonSharedCmdLira.Root)) {
        return super.equals(obj);
      }
      cmd.Lira.JonSharedCmdLira.Root other = (cmd.Lira.JonSharedCmdLira.Root) obj;

      if (!getCmdCase().equals(other.getCmdCase())) return false;
      switch (cmdCase_) {
        case 1:
          if (!getRefineTarget()
              .equals(other.getRefineTarget())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (cmdCase_) {
        case 1:
          hash = (37 * hash) + REFINE_TARGET_FIELD_NUMBER;
          hash = (53 * hash) + getRefineTarget().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cmd.Lira.JonSharedCmdLira.Root parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmd.Lira.JonSharedCmdLira.Root parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.Root parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmd.Lira.JonSharedCmdLira.Root parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.Root parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmd.Lira.JonSharedCmdLira.Root parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.Root parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cmd.Lira.JonSharedCmdLira.Root parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.Root parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cmd.Lira.JonSharedCmdLira.Root parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.Root parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cmd.Lira.JonSharedCmdLira.Root parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cmd.Lira.JonSharedCmdLira.Root prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cmd.Lira.Root}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cmd.Lira.Root)
        cmd.Lira.JonSharedCmdLira.RootOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_Root_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_Root_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cmd.Lira.JonSharedCmdLira.Root.class, cmd.Lira.JonSharedCmdLira.Root.Builder.class);
      }

      // Construct using cmd.Lira.JonSharedCmdLira.Root.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmdCase_ = 0;
        cmd_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_Root_descriptor;
      }

      @java.lang.Override
      public cmd.Lira.JonSharedCmdLira.Root getDefaultInstanceForType() {
        return cmd.Lira.JonSharedCmdLira.Root.getDefaultInstance();
      }

      @java.lang.Override
      public cmd.Lira.JonSharedCmdLira.Root build() {
        cmd.Lira.JonSharedCmdLira.Root result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cmd.Lira.JonSharedCmdLira.Root buildPartial() {
        cmd.Lira.JonSharedCmdLira.Root result = new cmd.Lira.JonSharedCmdLira.Root(this);
        if (cmdCase_ == 1) {
          if (refineTargetBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = refineTargetBuilder_.build();
          }
        }
        result.cmdCase_ = cmdCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cmd.Lira.JonSharedCmdLira.Root) {
          return mergeFrom((cmd.Lira.JonSharedCmdLira.Root)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cmd.Lira.JonSharedCmdLira.Root other) {
        if (other == cmd.Lira.JonSharedCmdLira.Root.getDefaultInstance()) return this;
        switch (other.getCmdCase()) {
          case REFINE_TARGET: {
            mergeRefineTarget(other.getRefineTarget());
            break;
          }
          case CMD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cmd.Lira.JonSharedCmdLira.Root parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cmd.Lira.JonSharedCmdLira.Root) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int cmdCase_ = 0;
      private java.lang.Object cmd_;
      public CmdCase
          getCmdCase() {
        return CmdCase.forNumber(
            cmdCase_);
      }

      public Builder clearCmd() {
        cmdCase_ = 0;
        cmd_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          cmd.Lira.JonSharedCmdLira.Refine_target, cmd.Lira.JonSharedCmdLira.Refine_target.Builder, cmd.Lira.JonSharedCmdLira.Refine_targetOrBuilder> refineTargetBuilder_;
      /**
       * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
       * @return Whether the refineTarget field is set.
       */
      @java.lang.Override
      public boolean hasRefineTarget() {
        return cmdCase_ == 1;
      }
      /**
       * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
       * @return The refineTarget.
       */
      @java.lang.Override
      public cmd.Lira.JonSharedCmdLira.Refine_target getRefineTarget() {
        if (refineTargetBuilder_ == null) {
          if (cmdCase_ == 1) {
            return (cmd.Lira.JonSharedCmdLira.Refine_target) cmd_;
          }
          return cmd.Lira.JonSharedCmdLira.Refine_target.getDefaultInstance();
        } else {
          if (cmdCase_ == 1) {
            return refineTargetBuilder_.getMessage();
          }
          return cmd.Lira.JonSharedCmdLira.Refine_target.getDefaultInstance();
        }
      }
      /**
       * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
       */
      public Builder setRefineTarget(cmd.Lira.JonSharedCmdLira.Refine_target value) {
        if (refineTargetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          refineTargetBuilder_.setMessage(value);
        }
        cmdCase_ = 1;
        return this;
      }
      /**
       * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
       */
      public Builder setRefineTarget(
          cmd.Lira.JonSharedCmdLira.Refine_target.Builder builderForValue) {
        if (refineTargetBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          refineTargetBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 1;
        return this;
      }
      /**
       * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
       */
      public Builder mergeRefineTarget(cmd.Lira.JonSharedCmdLira.Refine_target value) {
        if (refineTargetBuilder_ == null) {
          if (cmdCase_ == 1 &&
              cmd_ != cmd.Lira.JonSharedCmdLira.Refine_target.getDefaultInstance()) {
            cmd_ = cmd.Lira.JonSharedCmdLira.Refine_target.newBuilder((cmd.Lira.JonSharedCmdLira.Refine_target) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 1) {
            refineTargetBuilder_.mergeFrom(value);
          }
          refineTargetBuilder_.setMessage(value);
        }
        cmdCase_ = 1;
        return this;
      }
      /**
       * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
       */
      public Builder clearRefineTarget() {
        if (refineTargetBuilder_ == null) {
          if (cmdCase_ == 1) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 1) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          refineTargetBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
       */
      public cmd.Lira.JonSharedCmdLira.Refine_target.Builder getRefineTargetBuilder() {
        return getRefineTargetFieldBuilder().getBuilder();
      }
      /**
       * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
       */
      @java.lang.Override
      public cmd.Lira.JonSharedCmdLira.Refine_targetOrBuilder getRefineTargetOrBuilder() {
        if ((cmdCase_ == 1) && (refineTargetBuilder_ != null)) {
          return refineTargetBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 1) {
            return (cmd.Lira.JonSharedCmdLira.Refine_target) cmd_;
          }
          return cmd.Lira.JonSharedCmdLira.Refine_target.getDefaultInstance();
        }
      }
      /**
       * <code>.cmd.Lira.Refine_target refine_target = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cmd.Lira.JonSharedCmdLira.Refine_target, cmd.Lira.JonSharedCmdLira.Refine_target.Builder, cmd.Lira.JonSharedCmdLira.Refine_targetOrBuilder> 
          getRefineTargetFieldBuilder() {
        if (refineTargetBuilder_ == null) {
          if (!(cmdCase_ == 1)) {
            cmd_ = cmd.Lira.JonSharedCmdLira.Refine_target.getDefaultInstance();
          }
          refineTargetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cmd.Lira.JonSharedCmdLira.Refine_target, cmd.Lira.JonSharedCmdLira.Refine_target.Builder, cmd.Lira.JonSharedCmdLira.Refine_targetOrBuilder>(
                  (cmd.Lira.JonSharedCmdLira.Refine_target) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 1;
        onChanged();;
        return refineTargetBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cmd.Lira.Root)
    }

    // @@protoc_insertion_point(class_scope:cmd.Lira.Root)
    private static final cmd.Lira.JonSharedCmdLira.Root DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cmd.Lira.JonSharedCmdLira.Root();
    }

    public static cmd.Lira.JonSharedCmdLira.Root getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Root>
        PARSER = new com.google.protobuf.AbstractParser<Root>() {
      @java.lang.Override
      public Root parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Root(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Root> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Root> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cmd.Lira.JonSharedCmdLira.Root getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Refine_targetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cmd.Lira.Refine_target)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
     * @return Whether the target field is set.
     */
    boolean hasTarget();
    /**
     * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
     * @return The target.
     */
    cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget getTarget();
    /**
     * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
     */
    cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTargetOrBuilder getTargetOrBuilder();
  }
  /**
   * Protobuf type {@code cmd.Lira.Refine_target}
   */
  public static final class Refine_target extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cmd.Lira.Refine_target)
      Refine_targetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Refine_target.newBuilder() to construct.
    private Refine_target(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Refine_target() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Refine_target();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Refine_target(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.Builder subBuilder = null;
              if (target_ != null) {
                subBuilder = target_.toBuilder();
              }
              target_ = input.readMessage(cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(target_);
                target_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_Refine_target_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_Refine_target_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cmd.Lira.JonSharedCmdLira.Refine_target.class, cmd.Lira.JonSharedCmdLira.Refine_target.Builder.class);
    }

    public static final int TARGET_FIELD_NUMBER = 1;
    private cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget target_;
    /**
     * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
     * @return Whether the target field is set.
     */
    @java.lang.Override
    public boolean hasTarget() {
      return target_ != null;
    }
    /**
     * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
     * @return The target.
     */
    @java.lang.Override
    public cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget getTarget() {
      return target_ == null ? cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.getDefaultInstance() : target_;
    }
    /**
     * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
     */
    @java.lang.Override
    public cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTargetOrBuilder getTargetOrBuilder() {
      return getTarget();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (target_ != null) {
        output.writeMessage(1, getTarget());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (target_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTarget());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cmd.Lira.JonSharedCmdLira.Refine_target)) {
        return super.equals(obj);
      }
      cmd.Lira.JonSharedCmdLira.Refine_target other = (cmd.Lira.JonSharedCmdLira.Refine_target) obj;

      if (hasTarget() != other.hasTarget()) return false;
      if (hasTarget()) {
        if (!getTarget()
            .equals(other.getTarget())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTarget()) {
        hash = (37 * hash) + TARGET_FIELD_NUMBER;
        hash = (53 * hash) + getTarget().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cmd.Lira.JonSharedCmdLira.Refine_target parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmd.Lira.JonSharedCmdLira.Refine_target parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.Refine_target parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmd.Lira.JonSharedCmdLira.Refine_target parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.Refine_target parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmd.Lira.JonSharedCmdLira.Refine_target parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.Refine_target parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cmd.Lira.JonSharedCmdLira.Refine_target parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.Refine_target parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cmd.Lira.JonSharedCmdLira.Refine_target parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.Refine_target parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cmd.Lira.JonSharedCmdLira.Refine_target parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cmd.Lira.JonSharedCmdLira.Refine_target prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cmd.Lira.Refine_target}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cmd.Lira.Refine_target)
        cmd.Lira.JonSharedCmdLira.Refine_targetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_Refine_target_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_Refine_target_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cmd.Lira.JonSharedCmdLira.Refine_target.class, cmd.Lira.JonSharedCmdLira.Refine_target.Builder.class);
      }

      // Construct using cmd.Lira.JonSharedCmdLira.Refine_target.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (targetBuilder_ == null) {
          target_ = null;
        } else {
          target_ = null;
          targetBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_Refine_target_descriptor;
      }

      @java.lang.Override
      public cmd.Lira.JonSharedCmdLira.Refine_target getDefaultInstanceForType() {
        return cmd.Lira.JonSharedCmdLira.Refine_target.getDefaultInstance();
      }

      @java.lang.Override
      public cmd.Lira.JonSharedCmdLira.Refine_target build() {
        cmd.Lira.JonSharedCmdLira.Refine_target result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cmd.Lira.JonSharedCmdLira.Refine_target buildPartial() {
        cmd.Lira.JonSharedCmdLira.Refine_target result = new cmd.Lira.JonSharedCmdLira.Refine_target(this);
        if (targetBuilder_ == null) {
          result.target_ = target_;
        } else {
          result.target_ = targetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cmd.Lira.JonSharedCmdLira.Refine_target) {
          return mergeFrom((cmd.Lira.JonSharedCmdLira.Refine_target)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cmd.Lira.JonSharedCmdLira.Refine_target other) {
        if (other == cmd.Lira.JonSharedCmdLira.Refine_target.getDefaultInstance()) return this;
        if (other.hasTarget()) {
          mergeTarget(other.getTarget());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cmd.Lira.JonSharedCmdLira.Refine_target parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cmd.Lira.JonSharedCmdLira.Refine_target) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget target_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget, cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.Builder, cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTargetOrBuilder> targetBuilder_;
      /**
       * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
       * @return Whether the target field is set.
       */
      public boolean hasTarget() {
        return targetBuilder_ != null || target_ != null;
      }
      /**
       * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
       * @return The target.
       */
      public cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget getTarget() {
        if (targetBuilder_ == null) {
          return target_ == null ? cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.getDefaultInstance() : target_;
        } else {
          return targetBuilder_.getMessage();
        }
      }
      /**
       * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
       */
      public Builder setTarget(cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget value) {
        if (targetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          target_ = value;
          onChanged();
        } else {
          targetBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
       */
      public Builder setTarget(
          cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.Builder builderForValue) {
        if (targetBuilder_ == null) {
          target_ = builderForValue.build();
          onChanged();
        } else {
          targetBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
       */
      public Builder mergeTarget(cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget value) {
        if (targetBuilder_ == null) {
          if (target_ != null) {
            target_ =
              cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.newBuilder(target_).mergeFrom(value).buildPartial();
          } else {
            target_ = value;
          }
          onChanged();
        } else {
          targetBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
       */
      public Builder clearTarget() {
        if (targetBuilder_ == null) {
          target_ = null;
          onChanged();
        } else {
          target_ = null;
          targetBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
       */
      public cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.Builder getTargetBuilder() {
        
        onChanged();
        return getTargetFieldBuilder().getBuilder();
      }
      /**
       * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
       */
      public cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTargetOrBuilder getTargetOrBuilder() {
        if (targetBuilder_ != null) {
          return targetBuilder_.getMessageOrBuilder();
        } else {
          return target_ == null ?
              cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.getDefaultInstance() : target_;
        }
      }
      /**
       * <code>.cmd.Lira.JonGuiDataLiraTarget target = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget, cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.Builder, cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTargetOrBuilder> 
          getTargetFieldBuilder() {
        if (targetBuilder_ == null) {
          targetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget, cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.Builder, cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTargetOrBuilder>(
                  getTarget(),
                  getParentForChildren(),
                  isClean());
          target_ = null;
        }
        return targetBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cmd.Lira.Refine_target)
    }

    // @@protoc_insertion_point(class_scope:cmd.Lira.Refine_target)
    private static final cmd.Lira.JonSharedCmdLira.Refine_target DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cmd.Lira.JonSharedCmdLira.Refine_target();
    }

    public static cmd.Lira.JonSharedCmdLira.Refine_target getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Refine_target>
        PARSER = new com.google.protobuf.AbstractParser<Refine_target>() {
      @java.lang.Override
      public Refine_target parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Refine_target(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Refine_target> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Refine_target> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cmd.Lira.JonSharedCmdLira.Refine_target getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JonGuiDataLiraTargetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cmd.Lira.JonGuiDataLiraTarget)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>double target_longitude = 2;</code>
     * @return The targetLongitude.
     */
    double getTargetLongitude();

    /**
     * <code>double target_latitude = 3;</code>
     * @return The targetLatitude.
     */
    double getTargetLatitude();

    /**
     * <code>double target_altitude = 4;</code>
     * @return The targetAltitude.
     */
    double getTargetAltitude();

    /**
     * <code>double target_azimuth = 5;</code>
     * @return The targetAzimuth.
     */
    double getTargetAzimuth();

    /**
     * <code>double target_elevation = 6;</code>
     * @return The targetElevation.
     */
    double getTargetElevation();

    /**
     * <code>double distance = 7;</code>
     * @return The distance.
     */
    double getDistance();

    /**
     * <pre>
     * UUID as four fixed32 values (128 bits total)
     * </pre>
     *
     * <code>int32 uuid_part1 = 8;</code>
     * @return The uuidPart1.
     */
    int getUuidPart1();

    /**
     * <code>int32 uuid_part2 = 9;</code>
     * @return The uuidPart2.
     */
    int getUuidPart2();

    /**
     * <code>int32 uuid_part3 = 10;</code>
     * @return The uuidPart3.
     */
    int getUuidPart3();

    /**
     * <code>int32 uuid_part4 = 11;</code>
     * @return The uuidPart4.
     */
    int getUuidPart4();
  }
  /**
   * Protobuf type {@code cmd.Lira.JonGuiDataLiraTarget}
   */
  public static final class JonGuiDataLiraTarget extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cmd.Lira.JonGuiDataLiraTarget)
      JonGuiDataLiraTargetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JonGuiDataLiraTarget.newBuilder() to construct.
    private JonGuiDataLiraTarget(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JonGuiDataLiraTarget() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JonGuiDataLiraTarget();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JonGuiDataLiraTarget(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timestamp_ = input.readInt64();
              break;
            }
            case 17: {

              targetLongitude_ = input.readDouble();
              break;
            }
            case 25: {

              targetLatitude_ = input.readDouble();
              break;
            }
            case 33: {

              targetAltitude_ = input.readDouble();
              break;
            }
            case 41: {

              targetAzimuth_ = input.readDouble();
              break;
            }
            case 49: {

              targetElevation_ = input.readDouble();
              break;
            }
            case 57: {

              distance_ = input.readDouble();
              break;
            }
            case 64: {

              uuidPart1_ = input.readInt32();
              break;
            }
            case 72: {

              uuidPart2_ = input.readInt32();
              break;
            }
            case 80: {

              uuidPart3_ = input.readInt32();
              break;
            }
            case 88: {

              uuidPart4_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_JonGuiDataLiraTarget_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_JonGuiDataLiraTarget_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.class, cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TARGET_LONGITUDE_FIELD_NUMBER = 2;
    private double targetLongitude_;
    /**
     * <code>double target_longitude = 2;</code>
     * @return The targetLongitude.
     */
    @java.lang.Override
    public double getTargetLongitude() {
      return targetLongitude_;
    }

    public static final int TARGET_LATITUDE_FIELD_NUMBER = 3;
    private double targetLatitude_;
    /**
     * <code>double target_latitude = 3;</code>
     * @return The targetLatitude.
     */
    @java.lang.Override
    public double getTargetLatitude() {
      return targetLatitude_;
    }

    public static final int TARGET_ALTITUDE_FIELD_NUMBER = 4;
    private double targetAltitude_;
    /**
     * <code>double target_altitude = 4;</code>
     * @return The targetAltitude.
     */
    @java.lang.Override
    public double getTargetAltitude() {
      return targetAltitude_;
    }

    public static final int TARGET_AZIMUTH_FIELD_NUMBER = 5;
    private double targetAzimuth_;
    /**
     * <code>double target_azimuth = 5;</code>
     * @return The targetAzimuth.
     */
    @java.lang.Override
    public double getTargetAzimuth() {
      return targetAzimuth_;
    }

    public static final int TARGET_ELEVATION_FIELD_NUMBER = 6;
    private double targetElevation_;
    /**
     * <code>double target_elevation = 6;</code>
     * @return The targetElevation.
     */
    @java.lang.Override
    public double getTargetElevation() {
      return targetElevation_;
    }

    public static final int DISTANCE_FIELD_NUMBER = 7;
    private double distance_;
    /**
     * <code>double distance = 7;</code>
     * @return The distance.
     */
    @java.lang.Override
    public double getDistance() {
      return distance_;
    }

    public static final int UUID_PART1_FIELD_NUMBER = 8;
    private int uuidPart1_;
    /**
     * <pre>
     * UUID as four fixed32 values (128 bits total)
     * </pre>
     *
     * <code>int32 uuid_part1 = 8;</code>
     * @return The uuidPart1.
     */
    @java.lang.Override
    public int getUuidPart1() {
      return uuidPart1_;
    }

    public static final int UUID_PART2_FIELD_NUMBER = 9;
    private int uuidPart2_;
    /**
     * <code>int32 uuid_part2 = 9;</code>
     * @return The uuidPart2.
     */
    @java.lang.Override
    public int getUuidPart2() {
      return uuidPart2_;
    }

    public static final int UUID_PART3_FIELD_NUMBER = 10;
    private int uuidPart3_;
    /**
     * <code>int32 uuid_part3 = 10;</code>
     * @return The uuidPart3.
     */
    @java.lang.Override
    public int getUuidPart3() {
      return uuidPart3_;
    }

    public static final int UUID_PART4_FIELD_NUMBER = 11;
    private int uuidPart4_;
    /**
     * <code>int32 uuid_part4 = 11;</code>
     * @return The uuidPart4.
     */
    @java.lang.Override
    public int getUuidPart4() {
      return uuidPart4_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (targetLongitude_ != 0D) {
        output.writeDouble(2, targetLongitude_);
      }
      if (targetLatitude_ != 0D) {
        output.writeDouble(3, targetLatitude_);
      }
      if (targetAltitude_ != 0D) {
        output.writeDouble(4, targetAltitude_);
      }
      if (targetAzimuth_ != 0D) {
        output.writeDouble(5, targetAzimuth_);
      }
      if (targetElevation_ != 0D) {
        output.writeDouble(6, targetElevation_);
      }
      if (distance_ != 0D) {
        output.writeDouble(7, distance_);
      }
      if (uuidPart1_ != 0) {
        output.writeInt32(8, uuidPart1_);
      }
      if (uuidPart2_ != 0) {
        output.writeInt32(9, uuidPart2_);
      }
      if (uuidPart3_ != 0) {
        output.writeInt32(10, uuidPart3_);
      }
      if (uuidPart4_ != 0) {
        output.writeInt32(11, uuidPart4_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (targetLongitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, targetLongitude_);
      }
      if (targetLatitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, targetLatitude_);
      }
      if (targetAltitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, targetAltitude_);
      }
      if (targetAzimuth_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, targetAzimuth_);
      }
      if (targetElevation_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, targetElevation_);
      }
      if (distance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, distance_);
      }
      if (uuidPart1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, uuidPart1_);
      }
      if (uuidPart2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, uuidPart2_);
      }
      if (uuidPart3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, uuidPart3_);
      }
      if (uuidPart4_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, uuidPart4_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget)) {
        return super.equals(obj);
      }
      cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget other = (cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (java.lang.Double.doubleToLongBits(getTargetLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getTargetLongitude())) return false;
      if (java.lang.Double.doubleToLongBits(getTargetLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getTargetLatitude())) return false;
      if (java.lang.Double.doubleToLongBits(getTargetAltitude())
          != java.lang.Double.doubleToLongBits(
              other.getTargetAltitude())) return false;
      if (java.lang.Double.doubleToLongBits(getTargetAzimuth())
          != java.lang.Double.doubleToLongBits(
              other.getTargetAzimuth())) return false;
      if (java.lang.Double.doubleToLongBits(getTargetElevation())
          != java.lang.Double.doubleToLongBits(
              other.getTargetElevation())) return false;
      if (java.lang.Double.doubleToLongBits(getDistance())
          != java.lang.Double.doubleToLongBits(
              other.getDistance())) return false;
      if (getUuidPart1()
          != other.getUuidPart1()) return false;
      if (getUuidPart2()
          != other.getUuidPart2()) return false;
      if (getUuidPart3()
          != other.getUuidPart3()) return false;
      if (getUuidPart4()
          != other.getUuidPart4()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + TARGET_LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTargetLongitude()));
      hash = (37 * hash) + TARGET_LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTargetLatitude()));
      hash = (37 * hash) + TARGET_ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTargetAltitude()));
      hash = (37 * hash) + TARGET_AZIMUTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTargetAzimuth()));
      hash = (37 * hash) + TARGET_ELEVATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTargetElevation()));
      hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDistance()));
      hash = (37 * hash) + UUID_PART1_FIELD_NUMBER;
      hash = (53 * hash) + getUuidPart1();
      hash = (37 * hash) + UUID_PART2_FIELD_NUMBER;
      hash = (53 * hash) + getUuidPart2();
      hash = (37 * hash) + UUID_PART3_FIELD_NUMBER;
      hash = (53 * hash) + getUuidPart3();
      hash = (37 * hash) + UUID_PART4_FIELD_NUMBER;
      hash = (53 * hash) + getUuidPart4();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cmd.Lira.JonGuiDataLiraTarget}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cmd.Lira.JonGuiDataLiraTarget)
        cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTargetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_JonGuiDataLiraTarget_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_JonGuiDataLiraTarget_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.class, cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.Builder.class);
      }

      // Construct using cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        targetLongitude_ = 0D;

        targetLatitude_ = 0D;

        targetAltitude_ = 0D;

        targetAzimuth_ = 0D;

        targetElevation_ = 0D;

        distance_ = 0D;

        uuidPart1_ = 0;

        uuidPart2_ = 0;

        uuidPart3_ = 0;

        uuidPart4_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cmd.Lira.JonSharedCmdLira.internal_static_cmd_Lira_JonGuiDataLiraTarget_descriptor;
      }

      @java.lang.Override
      public cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget getDefaultInstanceForType() {
        return cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.getDefaultInstance();
      }

      @java.lang.Override
      public cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget build() {
        cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget buildPartial() {
        cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget result = new cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget(this);
        result.timestamp_ = timestamp_;
        result.targetLongitude_ = targetLongitude_;
        result.targetLatitude_ = targetLatitude_;
        result.targetAltitude_ = targetAltitude_;
        result.targetAzimuth_ = targetAzimuth_;
        result.targetElevation_ = targetElevation_;
        result.distance_ = distance_;
        result.uuidPart1_ = uuidPart1_;
        result.uuidPart2_ = uuidPart2_;
        result.uuidPart3_ = uuidPart3_;
        result.uuidPart4_ = uuidPart4_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget) {
          return mergeFrom((cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget other) {
        if (other == cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getTargetLongitude() != 0D) {
          setTargetLongitude(other.getTargetLongitude());
        }
        if (other.getTargetLatitude() != 0D) {
          setTargetLatitude(other.getTargetLatitude());
        }
        if (other.getTargetAltitude() != 0D) {
          setTargetAltitude(other.getTargetAltitude());
        }
        if (other.getTargetAzimuth() != 0D) {
          setTargetAzimuth(other.getTargetAzimuth());
        }
        if (other.getTargetElevation() != 0D) {
          setTargetElevation(other.getTargetElevation());
        }
        if (other.getDistance() != 0D) {
          setDistance(other.getDistance());
        }
        if (other.getUuidPart1() != 0) {
          setUuidPart1(other.getUuidPart1());
        }
        if (other.getUuidPart2() != 0) {
          setUuidPart2(other.getUuidPart2());
        }
        if (other.getUuidPart3() != 0) {
          setUuidPart3(other.getUuidPart3());
        }
        if (other.getUuidPart4() != 0) {
          setUuidPart4(other.getUuidPart4());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private double targetLongitude_ ;
      /**
       * <code>double target_longitude = 2;</code>
       * @return The targetLongitude.
       */
      @java.lang.Override
      public double getTargetLongitude() {
        return targetLongitude_;
      }
      /**
       * <code>double target_longitude = 2;</code>
       * @param value The targetLongitude to set.
       * @return This builder for chaining.
       */
      public Builder setTargetLongitude(double value) {
        
        targetLongitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double target_longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetLongitude() {
        
        targetLongitude_ = 0D;
        onChanged();
        return this;
      }

      private double targetLatitude_ ;
      /**
       * <code>double target_latitude = 3;</code>
       * @return The targetLatitude.
       */
      @java.lang.Override
      public double getTargetLatitude() {
        return targetLatitude_;
      }
      /**
       * <code>double target_latitude = 3;</code>
       * @param value The targetLatitude to set.
       * @return This builder for chaining.
       */
      public Builder setTargetLatitude(double value) {
        
        targetLatitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double target_latitude = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetLatitude() {
        
        targetLatitude_ = 0D;
        onChanged();
        return this;
      }

      private double targetAltitude_ ;
      /**
       * <code>double target_altitude = 4;</code>
       * @return The targetAltitude.
       */
      @java.lang.Override
      public double getTargetAltitude() {
        return targetAltitude_;
      }
      /**
       * <code>double target_altitude = 4;</code>
       * @param value The targetAltitude to set.
       * @return This builder for chaining.
       */
      public Builder setTargetAltitude(double value) {
        
        targetAltitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double target_altitude = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetAltitude() {
        
        targetAltitude_ = 0D;
        onChanged();
        return this;
      }

      private double targetAzimuth_ ;
      /**
       * <code>double target_azimuth = 5;</code>
       * @return The targetAzimuth.
       */
      @java.lang.Override
      public double getTargetAzimuth() {
        return targetAzimuth_;
      }
      /**
       * <code>double target_azimuth = 5;</code>
       * @param value The targetAzimuth to set.
       * @return This builder for chaining.
       */
      public Builder setTargetAzimuth(double value) {
        
        targetAzimuth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double target_azimuth = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetAzimuth() {
        
        targetAzimuth_ = 0D;
        onChanged();
        return this;
      }

      private double targetElevation_ ;
      /**
       * <code>double target_elevation = 6;</code>
       * @return The targetElevation.
       */
      @java.lang.Override
      public double getTargetElevation() {
        return targetElevation_;
      }
      /**
       * <code>double target_elevation = 6;</code>
       * @param value The targetElevation to set.
       * @return This builder for chaining.
       */
      public Builder setTargetElevation(double value) {
        
        targetElevation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double target_elevation = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetElevation() {
        
        targetElevation_ = 0D;
        onChanged();
        return this;
      }

      private double distance_ ;
      /**
       * <code>double distance = 7;</code>
       * @return The distance.
       */
      @java.lang.Override
      public double getDistance() {
        return distance_;
      }
      /**
       * <code>double distance = 7;</code>
       * @param value The distance to set.
       * @return This builder for chaining.
       */
      public Builder setDistance(double value) {
        
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double distance = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDistance() {
        
        distance_ = 0D;
        onChanged();
        return this;
      }

      private int uuidPart1_ ;
      /**
       * <pre>
       * UUID as four fixed32 values (128 bits total)
       * </pre>
       *
       * <code>int32 uuid_part1 = 8;</code>
       * @return The uuidPart1.
       */
      @java.lang.Override
      public int getUuidPart1() {
        return uuidPart1_;
      }
      /**
       * <pre>
       * UUID as four fixed32 values (128 bits total)
       * </pre>
       *
       * <code>int32 uuid_part1 = 8;</code>
       * @param value The uuidPart1 to set.
       * @return This builder for chaining.
       */
      public Builder setUuidPart1(int value) {
        
        uuidPart1_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * UUID as four fixed32 values (128 bits total)
       * </pre>
       *
       * <code>int32 uuid_part1 = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuidPart1() {
        
        uuidPart1_ = 0;
        onChanged();
        return this;
      }

      private int uuidPart2_ ;
      /**
       * <code>int32 uuid_part2 = 9;</code>
       * @return The uuidPart2.
       */
      @java.lang.Override
      public int getUuidPart2() {
        return uuidPart2_;
      }
      /**
       * <code>int32 uuid_part2 = 9;</code>
       * @param value The uuidPart2 to set.
       * @return This builder for chaining.
       */
      public Builder setUuidPart2(int value) {
        
        uuidPart2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uuid_part2 = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuidPart2() {
        
        uuidPart2_ = 0;
        onChanged();
        return this;
      }

      private int uuidPart3_ ;
      /**
       * <code>int32 uuid_part3 = 10;</code>
       * @return The uuidPart3.
       */
      @java.lang.Override
      public int getUuidPart3() {
        return uuidPart3_;
      }
      /**
       * <code>int32 uuid_part3 = 10;</code>
       * @param value The uuidPart3 to set.
       * @return This builder for chaining.
       */
      public Builder setUuidPart3(int value) {
        
        uuidPart3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uuid_part3 = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuidPart3() {
        
        uuidPart3_ = 0;
        onChanged();
        return this;
      }

      private int uuidPart4_ ;
      /**
       * <code>int32 uuid_part4 = 11;</code>
       * @return The uuidPart4.
       */
      @java.lang.Override
      public int getUuidPart4() {
        return uuidPart4_;
      }
      /**
       * <code>int32 uuid_part4 = 11;</code>
       * @param value The uuidPart4 to set.
       * @return This builder for chaining.
       */
      public Builder setUuidPart4(int value) {
        
        uuidPart4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uuid_part4 = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuidPart4() {
        
        uuidPart4_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cmd.Lira.JonGuiDataLiraTarget)
    }

    // @@protoc_insertion_point(class_scope:cmd.Lira.JonGuiDataLiraTarget)
    private static final cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget();
    }

    public static cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JonGuiDataLiraTarget>
        PARSER = new com.google.protobuf.AbstractParser<JonGuiDataLiraTarget>() {
      @java.lang.Override
      public JonGuiDataLiraTarget parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JonGuiDataLiraTarget(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JonGuiDataLiraTarget> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JonGuiDataLiraTarget> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cmd.Lira.JonSharedCmdLira.JonGuiDataLiraTarget getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Lira_Root_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_Lira_Root_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Lira_Refine_target_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_Lira_Refine_target_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Lira_JonGuiDataLiraTarget_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_Lira_JonGuiDataLiraTarget_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031jon_shared_cmd_lira.proto\022\010cmd.Lira\"?\n" +
      "\004Root\0220\n\rrefine_target\030\001 \001(\0132\027.cmd.Lira." +
      "Refine_targetH\000B\005\n\003cmd\"?\n\rRefine_target\022" +
      ".\n\006target\030\001 \001(\0132\036.cmd.Lira.JonGuiDataLir" +
      "aTarget\"\211\002\n\024JonGuiDataLiraTarget\022\021\n\ttime" +
      "stamp\030\001 \001(\003\022\030\n\020target_longitude\030\002 \001(\001\022\027\n" +
      "\017target_latitude\030\003 \001(\001\022\027\n\017target_altitud" +
      "e\030\004 \001(\001\022\026\n\016target_azimuth\030\005 \001(\001\022\030\n\020targe" +
      "t_elevation\030\006 \001(\001\022\020\n\010distance\030\007 \001(\001\022\022\n\nu" +
      "uid_part1\030\010 \001(\005\022\022\n\nuuid_part2\030\t \001(\005\022\022\n\nu" +
      "uid_part3\030\n \001(\005\022\022\n\nuuid_part4\030\013 \001(\005BKZIg" +
      "it-codecommit.eu-central-1.amazonaws.com" +
      "/v1/repos/jettison/jonp/cmd/lirab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cmd_Lira_Root_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cmd_Lira_Root_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_Lira_Root_descriptor,
        new java.lang.String[] { "RefineTarget", "Cmd", });
    internal_static_cmd_Lira_Refine_target_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cmd_Lira_Refine_target_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_Lira_Refine_target_descriptor,
        new java.lang.String[] { "Target", });
    internal_static_cmd_Lira_JonGuiDataLiraTarget_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cmd_Lira_JonGuiDataLiraTarget_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_Lira_JonGuiDataLiraTarget_descriptor,
        new java.lang.String[] { "Timestamp", "TargetLongitude", "TargetLatitude", "TargetAltitude", "TargetAzimuth", "TargetElevation", "Distance", "UuidPart1", "UuidPart2", "UuidPart3", "UuidPart4", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
